### ISSUE TITLE
Expose RevisionInfo through Document

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#1008]
The revision information (revdate, revnumber, revremark [docs](https://docs.asciidoctor.org/asciidoc/latest/document/revision-information/)) is only obtainable via attributes or using `readDocumentHeader` methods with provides a `RevisionInfo` class inside `DocumentHeader`.

As discussed in #970 readDocumentHeader does not provide any advantage over `load` and in fact it calls load under-the-hood, so it makes sense to deprecate it.
However, in order to do so `readDocumentHeader` we need to provide an equivalent to `RevisionInfo` class. In this case the Ruby implementation does not provide much guidance (imho). There's olny a method to obtain `reavdate` https://github.com/asciidoctor/asciidoctor/blob/e913d4fa0cde353c2659621e9680d96db0d855c4/lib/asciidoctor/document.rb#L757, so it's up to the user to read the other properties from attributes.

So, I suggest to add `RevisionInfo get revisionInfo()` to Document and expose the three fields as a single entity in a more Java-like way. With that, we can deprecate the readHeader methods.

**Comment by mojavelinux** [comment]
I also encourage you to check out how the Asciidoctor.js API provides access to this information: http://asciidoctor.github.io/asciidoctor.js/master/#documentrevisioninfo
