### ISSUE TITLE
All releases broken on SDKMAN!

### ISSUE THREAD

**Issue by marc0der** [asciidoctor/asciidoctorj#1009]
Hi all,

Hoping someone here can help me, please. I'm the project lead of SDKMAN.

I have noticed that the binaries published to SDKMAN from AsciidoctorJ are all hosted on Bintray. As you might have heard, they are currently in the process of "sunsetting" their service. Unfortunately, most of the AsciidoctorJ binaries are hosted on Bintray, so this needs to change urgently. As of today, they have prematurely started denying requests to their hosted binaries, and AsciidoctorJ is heavily affected by this. At the moment, it is not possible to install AsciidoctorJ through SDKMAN!

Here is a list of all the broken versions we currently hold:
```
[
        "1.5.2",
        "1.5.4.1",
        "1.5.5",
        "1.5.6",
        "1.5.7",
        "1.6.0",
        "1.6.1",
        "1.6.2",
        "2.0.0",
        "2.1.0",
        "2.2.0",
        "2.3.0",
        "2.3.1",
        "2.4.0",
        "2.4.2"
]
```

Do you have an alternate hosting solution in place for these binaries?
If so, could someone please help me by providing new URLs to the above binaries?
I really appreciate any help you can provide.

**Comment by robertpanzer** [comment]
Oops, of course I didn't think of this.
All releases should be also at
```
https://repo1.maven.org/maven2/org/asciidoctor/asciidoctorj/<version>/asciidoctorj-<version>-bin.zip
```
I can try to release them again with the correct URLs, but I won't be able to get this done today, but I should be able to do it tomorrow.

**Comment by robertpanzer** [comment]
The latest version, 2.4.3, was directly published to Maven central, so at least the latest version should be fine.

**Comment by marc0der** [comment]
Thanks, @robertpanzer! I'll delete all the defunct ones for now and let you republish them whenever you are ready to do so.

**Comment by robertpanzer** [comment]
@marc0der I think I have published all releases now again that you listed, pointing to Maven central now.
Could you please check if this is ok now?

**Comment by marc0der** [comment]
Looks great, thanks @robertpanzer! I've tested a sample, and everything looks like it's working :+1:
