### ISSUE TITLE
asciidoctorj error:Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by mahaairong** [asciidoctor/asciidoctorj#1024]
Hello everyOne!
Thanks for reading my tips.I have some questions .
My computer has 8 gigabytes of memory  and quad-core,jdk1.8,asciidoctor v2.0.14 asciidoctorj v2.4.2 
Use Assidoctorj to convert ADOC to PDF to report OutOfMemoryError:
![image](https://user-images.githubusercontent.com/83004959/115694166-3171e580-a393-11eb-8abc-d5a665ceb3ad.png)

use:
asciidoctorj -a pdf-theme=D:\resources\themes\custom_zh-theme.yml -a pdf-fontsdir=D:\resources\fonts -b pdf XXX.adoc

Where is the problem of memory overflow caused and how to solve it?
I would appreciate your reply!Thanks!

**Comment by abelsromero** [comment]
Is there any additional information you can provide? The stacktrace seems incomplete and does not show any Asciidoctorj reference I can recognize.
Ideally, if you can share a reproducable set of files, would be great.

**Comment by mahaairong** [comment]
> Is there any additional information you can provide? The stacktrace seems incomplete and does not show any Asciidoctorj reference I can recognize.
> Ideally, if you can share a reproducable set of files, would be great.

**Comment by mahaairong** [comment]
The files you refer to include styles(theme and fonts) and XXX.adoc?

- [ ] asciidoctorj -a pdf-theme=D:\resources\themes\custom_zh-theme.yml -a pdf-fontsdir=D:\resources\fonts -b pdf XXX.adoc

How can I send the files to you? Can I have your email address or the other way around?

**Comment by mahaairong** [comment]
> Is there any additional information you can provide? The stacktrace seems incomplete and does not show any Asciidoctorj reference I can recognize.
> Ideally, if you can share a reproducable set of files, would be great.

The files you refer to include styles(theme and fonts) and XXX.adoc?

 asciidoctorj -a pdf-theme=D:\resources\themes\custom_zh-theme.yml -a pdf-fontsdir=D:\resources\fonts -b pdf XXX.adoc
How can I send the files to you? Can I have your email address or the other way around?

**Comment by mojavelinux** [comment]
The best thing to do would be to create a repository here on GitHub and put the files into it. You can always remove the repository later once the problem has been sorted out.

**Comment by abelsromero** [comment]
Good news, I was able to get an OutOfMemory (while different mesage) using the CN example we have in the maven-examples repo.
Monitoring while playing with the theme it seems it's the treatment of fonts that causes the memory spikes. The maven example works because Maven by default allows for more memory. Here I can only recommend to increase the memory limit to your needs using `JAVA_OPTS` like:

```
$ JAVA_OPTS="-Xmx1024m" asciidoctorj -b pdf -a pdf-theme ...
```

**Comment by mahaairong** [comment]
> Good news, I was able to get an OutOfMemory (while different mesage) using the CN example we have in the maven-examples repo.
> Monitoring while playing with the theme it seems it's the treatment of fonts that causes the memory spikes. The maven example works because Maven by default allows for more memory. Here I can only recommend to increase the memory limit to your needs using `JAVA_OPTS` like:
> 
> ```
> $ JAVA_OPTS="-Xmx1024m" asciidoctorj -b pdf -a pdf-theme ...
> ```
> 
> NOTE: The fonts from the CN example we have are 100MB in file size, so I can only guess that we or prawn are loading them into memory.

I tried the method you gave me，using JAVA_OPTS :
![image](https://user-images.githubusercontent.com/83004959/115848362-567b5c80-a456-11eb-8491-f80f8f276ab3.png)
so i tried another method:
![image](https://user-images.githubusercontent.com/83004959/115848518-888cbe80-a456-11eb-868d-6b1a12215931.png)

Please take a look at it again,thanks!

**Comment by abelsromero** [comment]
The only thing that worked in my Win10 was setting the variable in the shell before the command with ` $env:JAVA_OPTS="-Xmx1024m"`.

If it doesn't work, you can try and get the actual arguments bing passed by disabling "echo off" in "asciidoctorj.bat".

**Comment by mahaairong** [comment]
> The only thing that worked in my Win10 was setting the variable in the shell before the command with ` $env:JAVA_OPTS="-Xmx1024m"`.
> 
> If it doesn't work, you can try and get the actual arguments bing passed by disabling "echo off" in "asciidoctorj.bat".

For the memory overflow problem, I did the following experiment:
1. Three computers with 8GB of RAM and the same document and style, only one can publish successfully with ASCIIDoctorj, but it will run out of memory if the ADOCC document contains a slightly larger image memory (e.g. 490KB).
2. Therefore, I changed to a 16G computer, which is the same as the case of Method 1. It is still a memory overflow error.So I decided it had nothing to do with the computer's physical memory configuration.
3. I have a hypothesis that the environment of ASCIIDoctorj depends on, is my configuration complete?My current environment is JDK 1.8, Aciidoctorj V2.4.3, Ruby V2.7.2.

**Comment by robertpanzer** [comment]
> So I decided it had nothing to do with the computer's physical memory configuration.

Totally right. AsciidoctorJ, or any Java program, can only use as much memory as you give the Java Virtual Machine (JVM).
The amount of memory available to the JVM is controlled via the option `-Xmx` as @abelsromero has pointed out.
So please try increasing this to a larger value like `$env:JAVA_OPTS="-Xmx4096m"` if 1024m does not suffice.
