### ISSUE TITLE
Publish 2.5.x docs

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#1028]
We just released v2.5.x but docs in https://docs.asciidoctor.org only contain version 2.4.
I can take care of the docs repo configuration but I'd need the v2.5.x branch created here :pleading_face: .

**Comment by robertpanzer** [comment]
Wait, didn't we say that we wanted to create a new v2.5.x branch only when it is clear that main will continue as v2.6.x or v3.0.x?

**Comment by abelsromero** [comment]
> Wait, didn't we say that we wanted to create a new v2.5.x branch only when it is clear that main will continue as v2.6.x or v3.0.x?

It's true that that's consistent with previous conversions but then I am cofused as how do we publish the docs for 2.5.0. We can update the labels https://github.com/asciidoctor/asciidoctorj/blob/ac6727e4ea753c51ea691d5b2bcc6aacb5f3ce3a/docs/antora.yml#L3-L7 and point the playbook to `main` but then we may fall again into publishing docs containing unreleased changes :dizzy_face:

**Comment by robertpanzer** [comment]
Otoh, whenever we merge a PR to main we also need to make sure to move the v2.5.x branch along.
Also we would need to tell potential new contributors that if they want to have a bug fix for v2.5.x that they would need to make a PR for main, and not v2.5.x... expect when main and v2.5.x really diverge. I find that also somehow confusing and would need to be documented (and updated again and again) whenever that happens.

Sure, always having to keep in mind that whenever a PR is merged that triggers a minor or major version update we also need to create the branch and update docs.asciidoctor.org is also error prone like you said.

Don't get me wrong, I can immediately push a v2.5.x branch pointing to the HEAD of main, but it's also a dedicated effort each time to update that, except for when a change is merged that triggers a major/minor update.

I think it would be good if all repos in the asciidoctor.org would behave the same in that regard.
@mojavelinux What is your opinion on that?

**Comment by mojavelinux** [comment]
For the repositories I maintain, I don't create a branch until I need the main branch for working on the next minor or major version. So as long as what's going on in main is for 2.5.x in this case, then the main branch can suffice as the release line branch.

There's always a small risk that you end up deciding after documenting something that you need to move it to the next minor/major, but I really see that as an acceptable tradeoff to having to maintain two active branches.

**Comment by abelsromero** [comment]
Then, I created this PR to update the main branch version for antora https://github.com/asciidoctor/asciidoctorj/pull/1029. With that we can point to it and publish the docs.

**Comment by abelsromero** [comment]
Already done
