### ISSUE TITLE
Performance regression in v2.5.0

### ISSUE THREAD

**Issue by kedar-joshi** [asciidoctor/asciidoctorj#1032]
Please check `master` and `bugfixes/performance-regression` branches from https://github.com/locationguru-solutions/web-application-reference.

The only change in branch `bugfixes/performance-regression` is upgrade to v2.5.0 and as a result builds are 10-15 seconds slower compared to `master` (as evident here https://github.com/locationguru-solutions/web-application-reference/actions).

**Comment by abelsromero** [comment]
I see executions taking similar times or higher prior to this change, have you appreciated other issues. Also, I am not confident that gh-actions environments are reliable to make performance measurements.

**Comment by kedar-joshi** [comment]
> Also, I am not confident that gh-actions environments are reliable to make performance measurements.

Agree but I am seeing similar performance drop on my local environment as well so GitHub actions results aren't totally off. Also, I am consistently able to reproduce it simply by changing version to `2.5.0`.

**Comment by abelsromero** [comment]
There's indeed something I got this numbers

![image](https://user-images.githubusercontent.com/5781153/116822985-1a48aa00-ab82-11eb-9491-aa67d77f73aa.png)

I narrowed it to only the document generation and collected the times with.

```sh
#/bin/bash

i=0
limit=50

while [ $i -le $limit ]
do
 mvn clean generate-resources -pl web-application | grep "Total time" | awk '{print $4}' >> out.txt
 ((i++))
done;

```

**Comment by robertpanzer** [comment]
We upgraded JRuby between 2.4.3 and 2.5.0. 
Can you check if there's still a difference if you fix the version of JRuby to the previous vs the new version?

**Comment by abelsromero** [comment]
I go same results isolating to only Asciidoctorj+PDF both with jruby 9.2.17.0.
Reproducer https://github.com/abelsromero/asciidoctorj-perf

![image](https://user-images.githubusercontent.com/5781153/116824415-5849cc00-ab8a-11eb-9226-7b0affa3d2f7.png)

**Comment by abelsromero** [comment]
With basic profiling it seems the time spike is in `preloadRequiredLibraries`, that goes from 18s to 49s in 2.5.0

![image](https://user-images.githubusercontent.com/5781153/116826182-0d808200-ab93-11eb-8e9e-732027a0d557.png)

![image](https://user-images.githubusercontent.com/5781153/116826174-06f20a80-ab93-11eb-9451-e4849324e2c3.png)

That's where we load the asciidoctor-pdf and is a call to jRuby https://github.com/asciidoctor/asciidoctorj/blob/9caaf1b2dc8889ee50f49dc49b7c90c30511f6d0/asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/RubyGemsPreloader.java#L78. Honestly I have no idea, in both cases we are using the same jRuby version and same asciidoctor-pdf gem. Only thing I can think of is rollback commits 1 by 1 untill we find the offender.

**Comment by robertpanzer** [comment]
I think I managed to isolate the difference.
We also upgraded concurrent-ruby from 1.0.5-java to 1.1.8.
If I take the current main HEAD and downgrade asciidoctor alone form 2.0.14 to 2.0.12 I also see sth like 20 seconds for loading the asciidoctor-pdf gem alone.

If I go to 2.4.3 that takes about 7 seconds.
Now if I bump concurrent-ruby to 1.1.8 the time for loading the asciidoctor-pdf gem also jumps to 20+ seconds:

Using 2.4.3 with the original dependencies gives me this:
```
Asciidoctor.create took 5865 msecs
Preloading took 7105 msecs
Asciidoctor.convert took 15860 msecs
Preloading took 1 msecs
Asciidoctor.convert took 3150 msecs
```
The dependencies were
```
Successfully installed temple-0.8.2
Successfully installed concurrent-ruby-1.0.5-java
Successfully installed tilt-2.0.9
Successfully installed thread_safe-0.3.6-java
Successfully installed slim-4.0.1
Successfully installed open-uri-cached-0.0.5
Successfully installed haml-5.0.4
Successfully installed erubis-2.7.0
Successfully installed rouge-3.26.0
Successfully installed coderay-1.1.3
Successfully installed asciidoctor-2.0.12
```

If I bump concurrent-ruby to 1.1.8 I get this
```
Asciidoctor.create took 8511 msecs
Preloading took 21932 msecs
Asciidoctor.convert took 29157 msecs
Preloading took 10 msecs
Asciidoctor.convert took 3264 msecs
```
The dependencies were 
```
Successfully installed temple-0.8.2
Successfully installed concurrent-ruby-1.1.8
Successfully installed tilt-2.0.9
Successfully installed thread_safe-0.3.6-java
Successfully installed slim-4.0.1
Successfully installed open-uri-cached-0.0.5
Successfully installed haml-5.0.4
Successfully installed erubis-2.7.0
Successfully installed rouge-3.26.0
Successfully installed coderay-1.1.3
Successfully installed asciidoctor-2.0.12
```

Now, when I downgrade concurrent-ruby to 1.1.7 I get better numbers again:
```
Asciidoctor.create took 5808 msecs
Preloading took 7135 msecs
Asciidoctor.convert took 14982 msecs
Preloading took 1 msecs
Asciidoctor.convert took 2833 msecs
```
The dependencies were 
```
Successfully installed temple-0.8.2
Successfully installed concurrent-ruby-1.1.7
Successfully installed tilt-2.0.9
Successfully installed thread_safe-0.3.6-java
Successfully installed slim-4.0.1
Successfully installed open-uri-cached-0.0.5
Successfully installed haml-5.0.4
Successfully installed erubis-2.7.0
Successfully installed rouge-3.26.0
Successfully installed coderay-1.1.3
Successfully installed asciidoctor-2.0.12
```
So it looks like sth has happened between concurrent-ruby 1.1.7 and 1.1.8. The differences between the 2 versions doesn't tell me much: https://github.com/ruby-concurrency/concurrent-ruby/compare/v1.1.7...v1.1.8

**Comment by abelsromero** [comment]
I run extra tests directly in Ruby with Asciidoctor 2.0.15 and concurrent 1.1.7 and 1.1.8 and there's a slight increase in variance (third row), but I would not say is conclusive.
![image](https://user-images.githubusercontent.com/5781153/116941880-d2548080-ac70-11eb-88f7-79d7661fcde1.png)

Unless there's some compeling reason (@mojavelinux ?) maybe we should revert to 1.1.7.

**Comment by mojavelinux** [comment]
Asciidoctor itself doesn't enforce one version of concurrent over another, so you are free to use whichever one you think is best. If this solves the performance issue, then I'd say go for it.

**Comment by robertpanzer** [comment]
As concurrent-ruby 1.0.5 seemed to have a specific version for java/jruby, I wonder how asciidoctor-pdf runs with concurrent-ruby 1.1.8 on jruby?

**Comment by abelsromero** [comment]
>  I wonder how asciidoctor-pdf runs with concurrent-ruby 1.1.8 on jruby?

Me too, and I am worried that at some point we need to upgrade.
Since we already have a reproducer (https://github.com/abelsromero/asciidoctorj-perf, need to polish readme only) and a possible fix, we could ask the jruby team for help in a non-critical manner.

**Comment by abelsromero** [comment]
I am testing this again with newer concurrent-ruby `1.1.19` and it's back to `1.1.17` times. There are no release notes and seeing the commit history I can only speculate about what fixed it :man_shrugging:.

**Comment by robertpanzer** [comment]
Thanks for the pointer @abelsromero! 🎉 
I'll also check how it looks here on my machine.

**Comment by robertpanzer** [comment]
I ran my test again with concurrent-ruby 1.1.7, 1.1.8 and 1.1.9 but 1.1.7 still seems to be the best (on my senior mac from 2014):
```
1.1.7
Asciidoctor.create took 5629 msecs
Asciidoctor.convert took 18613 msecs
Asciidoctor.convert took 4038 msecs

1.1.8
Asciidoctor.create took 6093 msecs
Asciidoctor.convert took 28191 msecs
Asciidoctor.convert took 2364 msecs

1.1.9
Asciidoctor.create took 5163 msecs
Asciidoctor.convert took 24633 msecs
Asciidoctor.convert took 2264 msecs
```
I just took current main, and ran this test:
```java
@RunWith(Arquillian.class)
public class TimeTest {

    @ArquillianResource
    private ClasspathResources classpath;

    @Test
    public void test() {
        String filename = "code-sample";
        File inputFile = this.classpath.getResource(filename + ".adoc");
        File outputFile1 = new File(inputFile.getParentFile(), filename + ".pdf");

        long t1 = System.currentTimeMillis();
        Asciidoctor asciidoctor = Asciidoctor.Factory.create();
        long t2 = System.currentTimeMillis();
        System.out.println("Asciidoctor.create took " + (t2 - t1) + " msecs");
        asciidoctor.convertFile(inputFile, options().backend("pdf").safe(SafeMode.UNSAFE).get());
        long t3 = System.currentTimeMillis();
        System.out.println("Asciidoctor.convert took " + (t3 - t2) + " msecs");


        long t4 = System.currentTimeMillis();
        asciidoctor.convertFile(inputFile, options().backend("pdf").safe(SafeMode.UNSAFE).get());
        long t5 = System.currentTimeMillis();
        System.out.println("Asciidoctor.convert took " + (t5 - t4) + " msecs");

        assertThat(outputFile1.exists(), is(true));

    }
}
```
