### ISSUE TITLE
FilenoUtil : Native subprocess control requires open access to the JDK IO subsystemPass

### ISSUE THREAD

**Issue by thschneider-lgn** [asciidoctor/asciidoctorj#1035]
At every start of AsciidoctorJ 2.4.3 with AdoptOpenJDK 16.0.1.900 I get the following message on console

`WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystemPass '--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED' to enable.`

**Comment by wimdeblauwe** [comment]
Same problem using Java 17 (via asciidoctor-maven-plugin 2.2.1):

```
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)
```

**Comment by lread** [comment]
Seems to be a JRuby issue https://github.com/jruby/jruby/issues/6721
