### ISSUE TITLE
Move DirectoryWalker and AsciidoctorDirectoryWalker to api

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#1038]
These componentes are located in the jruby package (and jar) but they have any dependency with JRuby and could be part of the API.
Is there any reason why they are not in api I am missing?

**Comment by mojavelinux** [comment]
It's very likely they were just left behind when the classes were moved to the api package. I vote in support for graduating them to the API.

**Comment by robertpanzer** [comment]
Moving the DirectoryWalker to the implementation module was a conscious decision at that time: https://github.com/asciidoctor/asciidoctorj/pull/760
I still see it as an implementation detail of the CLI, and commons-io probably has a more elaborate implementation for this task: http://commons.apache.org/proper/commons-io/apidocs/index.html?org/apache/commons/io/FileUtils.html (Search for `listFiles`)

If everybody still feels this belongs into the api we can of course do that.
I just wanted to reiterate the reasoning behind this decision.

**Comment by abelsromero** [comment]
> If everybody still feels this belongs into the api we can of course do that.
> I just wanted to reiterate the reasoning behind this decision.

The points are more than reasonable, and it's true the Walker is more of a "utils" thing easily replaceble with other libs. Probably is best to refactor the maven-plugin with a more agnostic method.

**Comment by mojavelinux** [comment]
Thanks for that clarification, Robert!
