### ISSUE TITLE
Impossible to highlighting source block with asciidoctorj

### ISSUE THREAD

**Issue by klod35** [asciidoctor/asciidoctorj#1045]
Hello,

I'm trying to generate some pdf document with asciidoctorj.
When i put a source block, the data are not highlighted.
Is there something to configure to activate this functionality.
Thank you in advance.

**Comment by robertpanzer** [comment]
Could you please provide a reproducer?
There should not be anything required besides configuring the highlighter to use by defining the attribute `:source-highlighter: rouge`

**Comment by abelsromero** [comment]
Closing since we have not been able to reproduce with the provided information for the time being.
