### ISSUE TITLE
Include asciidoctor-multipage

### ISSUE THREAD

**Issue by drdcd** [asciidoctor/asciidoctorj#1054]
This is quite simple - there was a [lengthy discussion](https://github.com/asciidoctor/asciidoctor/issues/626) about the need for multipage HTML output. Now that the [asciidoctor-multipage gem](https://github.com/owenh000/asciidoctor-multipage) is ready, it would be very nice to have it included in asciidoctorj.

**Comment by robertpanzer** [comment]
Hi Daniel,

Thanks for creating this ticket!
The focus of AsciidoctorJ atm is to deliver the Asciidoctor gem and make it available as a library and to build tools like the Maven or Gradle plugin. Other gems like asciidoctor-pdf are published as separate artifacts and can also be consumed as part of these build tools. 
When it comes to the AsciidoctorJ distribution it currently contains the AsciidoctorJ library (which is the only piece that delivers actual added value besides simply repackaging the original gem) plus a few gems that all are part of the asciidoctor organization. 

I would like to keep it this way and only include such libraries/gems that are part of this organization. 
Please feel free to rip off the build scripts as much as possible to package this gem as a jar that can be used with AsciidoctorJ, but as long as it's not part of this group I'd prefer to keep it as a separate module that users download themselves. 
I understand that it might be inconvenient for users having to download an extra jar, but it's also an extra effort to make sure that all the modules work together. 

Thanks, Robert

**Comment by abelsromero** [comment]
Closing this story. I think it's clear that it's not a goal for AsciidoctorJ to include such a gem.
We also have an example of how to integrate it in a build with the asciidoctor-maven-plugin https://github.com/asciidoctor/asciidoctor-maven-examples/tree/main/asciidoc-to-html-multipage-example in case someone needs directions.
