### ISSUE TITLE
Title page in PDF has not been generated via byte array stream

### ISSUE THREAD

**Issue by jasminesoap2222** [asciidoctor/asciidoctorj#1058]
The following simple contents has been converted to the pdf file with title page using asciidoctorj 2.5.2 and asciidoctorj-pdf 1.6.0. [test1_file.pdf](https://github.com/asciidoctor/asciidoctorj/files/7305828/test1_file.pdf)
However, in case of output the converted data to the byte array stream, there is no title page.[test1_stream.pdf](https://github.com/asciidoctor/asciidoctorj/files/7305827/test1_stream.pdf)

[contents]
```
:doctype: book

= Test Title: my subtitle
:author: alice
:revdate: 10.2021

This is a test adoc.
```

[code]
```
Options options = Options.builder().build();
options.setBackend("pdf");
options.setSafe(SafeMode.SERVER);

ByteArrayOutputStream bos = new ByteArrayOutputStream();
options.setToStream(bos);

String[] res = asciidoctor.convert(contents, options)
```

Any advice would be appreciated.

**Comment by abelsromero** [comment]
If memory serves, stream method assumes the content is to be embedded and disables the header and the footer.
Just enable it with `headerFooter(true)`.

```java
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        Options options = Options.builder()
            .backend("pdf")
            .safe(SafeMode.SERVER)
            .docType("book")
            .toStream(bos)
            .headerFooter(true)
            .build();

        asciidoctor.convert(contents, options);

        Files.write(Path.of("toStream.pdf"), bos.toByteArray());
```

**Comment by jasminesoap2222** [comment]
Thank you. Your help has solved it.

Moreover, I have met the other problems.
The generated title page has no background and logo images.
How does the asciidoctorj runtime load the image files in "resources/asciidoctor/images" folder on the web server ?


[contents]
```
:doctype: book

= Test Title
:author: Alice
:revdate: 10.2021
:title-logo-image: image:asciidoctor/images/logo.png[]
:title-page-background-image: image:asciidoctor/images/bg.png[]
```

Could I set the embed base64 image data to "title-logo-image" and "title-page-background-image" ?

**Comment by abelsromero** [comment]
For fine-grained customizations in PDF you should create a theme https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/theming-guide.adoc. Here is an example using maven as build tool https://github.com/asciidoctor/asciidoctor-maven-examples/tree/main/asciidoctor-pdf-with-theme-example.

**Comment by jasminesoap2222** [comment]
They have been solved.
Thank you.
