### ISSUE TITLE
Consider removing maven versions from the doc

### ISSUE THREAD

**Issue by oliviercailloux** [asciidoctor/asciidoctorj#1062]
Browsing the documentation, I stumbled upon several outdated version information about the `asciidoctorj` artifact (similar remarks hold about other artifacts). 

- The [README](https://github.com/asciidoctor/asciidoctorj/blob/main/README.adoc#distribution) indicates that the current version is 2.4.3.
- The [manual](https://docs.asciidoctor.org/asciidoctorj/latest/distribution/) says it is 2.5.1.

In fact, it is currently [2.5.2](https://search.maven.org/artifact/org.asciidoctor/asciidoctorj).

I suspect that trying to maintain such kind of tables up to date is not worth the burden. I suggest to link to [Maven central](https://search.maven.org/search?q=g:org.asciidoctor) and let the user determine the current version. You might also want to use a badge, see [here](https://github.com/oliviercailloux/JARiS/blob/master/README.adoc) for an example.

**Comment by robertpanzer** [comment]
Thanks for the heads up.
I'll update the versions.
I think the README is still the first place where a user looks for how to include a library, so I'd like to keep it there as well.
