### ISSUE TITLE
Test do not run in IntelliJ

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#1065]
When trying to run a rest class or method directly from IntelliJ tests fail with

![image](https://user-images.githubusercontent.com/5781153/141204225-7c66575b-c8a5-4713-9d0d-6fb357218bac.png)

**Comment by abelsromero** [comment]
Just mentioning it to let know I am looking into it because trying to work on anything else with this is just obnoxious.

So far I found that removing `polutedTest` task works, just need to find a permanent proper solution.

**Comment by abelsromero** [comment]
Seems the issue comes from the categories filter in `task pollutedTest`

```
useJUnit {
    includeCategories 'org.asciidoctor.categories.Polluted'
  }
```

The command according to the run configuration is `:asciidoctorj:test --tests "org.asciidoctor.jruby.cli.WhenAsciidoctorIsCalledUsingCli"` which works fine from the terminal. But IDEA somehow messes things injecting `--tests` into the `pollutedTest` (which runs before `test` task) and that obviously fails because the test task does not match the category.
That explains why, running the tests with `@Category(Polluted.class)` works, it's run before tests.

**Comment by abelsromero** [comment]
I reproduced the problem in a simple project an reported to Idea team https://youtrack.jetbrains.com/issue/IDEA-282425 :crossed_fingers:

**Comment by robertpanzer** [comment]
Thanks for picking this up.
Sometimes it's really annoying. For me personally it seems to depend on the weather whether I can debug the tests or not.

**Comment by abelsromero** [comment]
As local workarround just removing `test.dependsOn pollutedTest` works, but that's not something we want in the long run.

**Comment by abelsromero** [comment]
I narrowed it down to missing dependencies introduced in asciidoctorj-diagram v2.2.0.
```
  implementation 'org.asciidoctor:asciidoctorj-diagram-ditaamini:1.0.1'
  implementation 'org.asciidoctor:asciidoctorj-diagram-plantuml:1.2021.8'
```

Adding them allows the distribution to convert the example successfully and explains why running from a Java app worked, since the dependencies where pulled automatically as transitives in the later. However, v2.5.2 of distribution contains asciidoctor-diagram 2.1.2 but I assume the fix from from plantuml itself-

Now @robertpanzer, as a fix I'd suggest
1. Upgrade asciidoctorj-diagram to latest 2.2, just for maintenance.
2. Remove the `transitive=false` restriction from https://github.com/asciidoctor/asciidoctorj/blob/0796989a3ec6ef6e38f7baf05e39e5ca75789df1/asciidoctorj-distribution/build.gradle#L20 which prevents pulling the new libs.
3. Add some IT test to cover the reported issue. But I am not 100% on this because it feels something more on the territory of asciidoctorj-diagram, but without it we cannot avoid regressions on the CLI.

**Comment by abelsromero** [comment]
Is it necessary to handle them manually? I mean, why can't we just pull them as diagram's transitives?

**Comment by robertpanzer** [comment]
In general asciidoctor-diagram-plantuml and asciidoctor-diagram-ditaamini have their own release cycle, that's why they also have their own version numbering scheme.
So to always have the latest and greatest components in the distribution (Ok, I missed that part now apparently :D) we could rely on the transitive dependency or we would need to specify their versions explicitly depending on the order in which the three modules were released.
I think it would be cleaner to just always reference them explicitly.

**Comment by abelsromero** [comment]
> I think it would be cleaner to just always reference them explicitly.

I see, I went back to the module descriptor and those are runtime decendencies, makes sense then 👍

**Comment by abelsromero** [comment]
My mistake, in the PR https://github.com/asciidoctor/asciidoctorj/pull/1066, i mentioned this issue, but should have been #1064
