### ISSUE TITLE
Description of conversion process

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctorj#1068]
On this page: 
https://docs.asciidoctor.org/asciidoctorj/latest/extensions/conversion-process-overview/ (issue 2.5)
it says that 
"Block macro, inline macro, and block processors are called during processing in the order that they appear in the document."
I don't think this is true. When I test it (v2.5.2) by doing prinltns, the sequence is: block macro and block processors interleaved in the order that they appear in the document, then inlines in the order they appear in the document.
I only tried a single file-I don't know if it is affected by includes.

The same page says "The different extension types are called in different steps of the conversion process in the order shown in the table. Within each type:"
I have no idea what this means. Type? Table?

**Comment by mojavelinux** [comment]
>  then inlines in the order they appear in the document.

This is true for Asciidoctor as a whole and goes back to its inception. The inline elements are not processed until the convert phase, after all the blocks in the document have been parsed.

**Comment by robertpanzer** [comment]
> The same page says "The different extension types are called in different steps of the conversion process in the order shown in the table. Within each type:"
> I have no idea what this means. Type? Table?

This probably got under the wheels when moving the original into the structure for the Antora site.
The original is still available in an older revision of the repo, for example here: https://github.com/asciidoctor/asciidoctorj/blob/86320bc1ab65cc0473cd8f4767ad36980331df3f/docs/integrator-guide.adoc#extend-asciidoctorj-write-your-own-extensions
I'll look at creating a PR to fix this.

**Comment by rockyallen** [comment]
Thanks for the clarification.
