### ISSUE TITLE
Request for handling black listed licenses from blackduck

### ISSUE THREAD

**Issue by RamyaRohidas** [asciidoctor/asciidoctorj#1092]
b. FOSS with Blacklisted License		
		
Click here to check license status		
		
FOSS name	FOSS version	License
frame	1	GNU General Public License v2.0 only
ttfunk	1.7.0	GNU General Public License v2.0 or later   - asciidoctorj-pdf-1.6.2.jar!/gems/ttfunk-1.7.0/lib/ttfunk/
com.guicedee.services:bouncycastle	1.2.2.1	GNU General Public License v3.0 or later  -  jruby-stdlib-9.2.20.1.jar!/META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/bcpkix-jdk15on/1.68/bcpkix-jdk15on-1.68.jar!/org/bouncycastle/cert/

**Comment by mojavelinux** [comment]
Please do not post outputs of reports for your personal terms and conditions to this project. Besides, the reports is wrong anyway because ttfunk is licensed under the Matz's license for Ruby. If you post this again, you will be prohibited from opening issues in this project.
