### ISSUE TITLE
Distribution Page is Out-of-date

### ISSUE THREAD

**Issue by programming-wolf** [asciidoctor/asciidoctorj#1142]
The latest version mentioned on the [AsciidoctorJ Distribution page](https://docs.asciidoctor.org/asciidoctorj/latest/distribution/) is version 2.5.4. However, the most recent release on GitHub is version 2.5.7. 

In addition, maven central changed their URL to `central.sonatype.com` in the meantime, which they also announce on their website if you're redirected by an old link:
> On February 23, 2023, we started redirecting users from search.maven.org to central.sonatype.com. Launched in September of 2022, central.sonatype.com provides the main functionality of search.maven.org with enhanced search results, including security vulnerability and software quality information.

As a consequence, all links to files are broken on the distribution page and users are redirected to `central.sonatype.com`. They also changed the structure of the URLs, so for example the URL to the latest release is now `https://central.sonatype.com/artifact/org.asciidoctor/asciidoctorj/2.5.7`. 

If I may, I recommend to remove all the separate links to files and just link to the one URL on central.sonatype.com (as I personally would try to get all the information there). 

If you still want to link to the single files, they are now located in `https://repo1.maven.org/maven2/org/asciidoctor/asciidoctorj/2.5.7/`, as an example for v2.5.7 (I don't know if it's always `repo1` or if they can alternate between releases).

I first considered to create a pull request, but then decided to go for an issue to propose changes to the site structure itself. I hope this is ok.

**Comment by abelsromero** [comment]
> As a consequence, all links to files are broken on the distribution page and users are redirected to `central.sonatype.com`.

I was testing and I think we could make it so
* artifact points to versions
* the version points to the details as you suggested

```
:uri-maven-artifact-query: https://central.sonatype.com/artifact/org.asciidoctor/asciidoctorj/{artifact-version}/versions
:uri-maven-artifact-detail: https://central.sonatype.com/artifact/org.asciidoctor/asciidoctorj/{artifact-version}
```

> If I may, I recommend to remove all the separate links to files and just link to the one URL on central.sonatype.com (as I personally would try to get all the information there).

I personally like them, but I admit only the distribution is useful.
I noted the urls mostly work fine (only change to https, and remove tar which does not exist) because they use the API calls.

> I first considered to create a pull request, but then decided to go for an issue to propose changes to the site structure itself. I hope this is ok.

Feel free. I'd say it's easier to discuss actual code in fact.
