### ISSUE TITLE
Asciidoctor.convert() never returns Documents.

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#1175]
As mentioned by @abelsromero in #1171 the method `Asciidodctor.convert()` never returns a Document, even though the caller asks for a `org.asciidoctor.ast.Document`.
The implementation of this method should use the NodeConverter and try to convert the result returned by Asciidoctor.

**Comment by abelsromero** [comment]
Addressed in PR https://github.com/asciidoctor/asciidoctorj/pull/1171, I think we can close this issue?

**Comment by robertpanzer** [comment]
Yes, totally! Thanks for fixing it.
