### ISSUE TITLE
Remove test's report destination

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#1188]
I think this Gradle customization could be removed.

`asciidoctorj-core` and `asciidoctorj-wildfly-integration-test` customize the destination path of test reports with

```
  reports {
    html {
      destination file("$buildDir/reports/${task.name}")
    }
    junitXml {
      destination file("$buildDir/${task.name}-result")
    }
  }
```

But the default configuration for reports already separates them by task:
* HTML: build/reports/tests/${task.name}
* JUnitXml: build/test-results/${task.name}

Maybe this was necessary at some point but does not seem the case now. Removing it we can safe a few lines :grin: 

NOTE: if the change is applied, we need to update the path of the upload artifacts step in CI.

**Comment by robertpanzer** [comment]
Sounds good!
The more we can rely on the conventions the better.
