### ISSUE TITLE
Invalid 'http://asciidoctor.org' references

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#1195]
In docs, Javadocs, etc. there are several references to `http://asciidoctor.org` (around 30).

We should:
- [ ] Use only `https` references
- [ ] Update when necessary to point to the new docs site (https://docs.asciidoctor.org/)

For both:
- [ ] v3.0.0
- [ ] v2.5.9

**Comment by abelsromero** [comment]
Great, we can't assign multiple milestones to an issue :disappointed: I find GH goes to great lengths to not make life easier for maintainers.

**Comment by mojavelinux** [comment]
I tend to use tags for this instead.

**Comment by abelsromero** [comment]
> I tend to use tags for this instead.

It seems indeed the only option.
