### ISSUE TITLE
feature request: render asciidoc to markdown 

### ISSUE THREAD

**Issue by travisfw** [asciidoctor/asciidoctorj#1232]
Markdown being a common readable text format, why not support rendering asciidoc to markdown? Then when you need markdown for whatever non-asciidoc system, just render and paste it. I imagine it could be a lot easier to support than the other output formats.

**Comment by mojavelinux** [comment]
If it's something you need, then you are welcome to create it. Nothing is stopping you. But no one is just going to do it for you. That's now how OSS works. You need to be part of the solution.

If you want to use software that's already available, you can check out [downdoc](https://github.com/opendevise/downdoc/). It's written in JavaScript, so not currently available through Java/AsciidoctorJ. However, you could write a wrapper that calls it using a system command.

The alternative would be to create a converter for Asciidoctor or AsciidoctorJ that generates Markdown. If you need help with that, you can ask in the project chat.

**Comment by travisfw** [comment]
> If it's something you need, then you are welcome to […] create a converter for Asciidoctor or AsciidoctorJ that generates Markdown. If you need help with that, you can ask in the project chat.

Great. [I asked on Zulip.
](https://asciidoctor.zulipchat.com/#narrow/stream/279644-users.2Fasciidoctorj/topic/Help.20for.20creating.20a.20markdown.20backend/near/386951141 )

**Comment by mojavelinux** [comment]
We'll continue the discussion there.

Btw, there's a Markdown converter/backend for AsciidoctorJ of sorts. It just happens to be called the leanpub converter because it generates Markdown of the Leanpub variant (because there isn't just one Markdown to target).

See https://github.com/asciidoctor/asciidoctor-leanpub-converter
