### ISSUE TITLE
Include processor with all attributes resolution

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctorj#1252]
Hi,

I developed a custom include processor here https://github.com/asciidocfx/AsciidocFX/blob/master/src/main/java/com/kodedu/service/extension/processor/XrefIncludeProcessor.java

With this implementation, lines attribute is not resolved somehow ignored. What might I be missed ?

I simply want to process include directives as is in Asciidoctor but additionally process some information for AsciidocFX

Thank you.

**Comment by mojavelinux** [comment]
This question should be directed to the project chat at https://chat.asciidoctor.org.

**Comment by robertpanzer** [comment]
Closing since it was handled in the project chat.
