### ISSUE TITLE
Asciidoctorj does not preserve source file directory structure

### ISSUE THREAD

**Issue by netpyoung** [asciidoctor/asciidoctorj#1289]
## problem

Asciidoctorj does not preserve source file directory structure

## Environment

``` txt
$ ver

Microsoft Windows [Version 10.0.22631.4541]

$ java --version
java 22.0.2 2024-07-16
Java(TM) SE Runtime Environment (build 22.0.2+9-70)
Java HotSpot(TM) 64-Bit Server VM (build 22.0.2+9-70, mixed mode, sharing)

$ asciidoctorj --version
Java HotSpot(TM) 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
AsciidoctorJ 2.5.13 (Asciidoctor 2.0.23) [https://asciidoctor.org]
Runtime Environment: jruby 9.4.7.0 (3.1.4)
```

## status

I feel tired to installing gems so I tried to use asciidoctorj instead asciidoctor.

previous works like that.

`asciidoctor -R . -D public -a stylesheet=my-asciidoctor.css clojure-complete-html.adoc **/*.adoc`

[gh-pages dir](https://github.com/clojure-kr/clojure-complete/tree/gh-pages)

It preserve directory structure.

So I tried to use asciidoctorj. But Asciidoctorj does not preserve source file directory structure

`asciidoctorj -R . -D public -a stylesheet=my-asciidoctor.css clojure-complete-html.adoc **/*.adoc`

```
$ dir public
 Volume in drive D is D
 Volume Serial Number is 1E7F-2C07

 Directory of D:\temp\clojure-complete\public

11/28/2024  09:03 AM    <DIR>          .
11/28/2024  08:39 AM    <DIR>          ..
11/28/2024  09:03 AM             5,021 asciidoctor.html
11/28/2024  09:03 AM             3,161 atom.html
11/28/2024  09:03 AM            17,557 boot.html
11/28/2024  09:03 AM           223,366 clojure-and-gof-design-patterns.html
11/28/2024  09:03 AM             6,601 clojure-complete-html.html
11/28/2024  09:03 AM            67,496 clojure-complete-pdf.html
11/28/2024  09:03 AM           129,807 collections-and-sequences.html
11/28/2024  09:03 AM               680 demo.html
11/28/2024  09:03 AM             1,433 design-patterns.html
11/28/2024  09:03 AM            33,664 destructuring.html
11/28/2024  09:03 AM            14,461 development-environments.html
11/28/2024  09:03 AM             5,298 emacs.html
11/28/2024  09:03 AM            42,721 flow-controls.html
...
```

It was flatten. It seems like bug.

## Ref

- https://github.com/asciidoctor/asciidoctor/issues/1394

**Comment by robertpanzer** [comment]
Could you please try with asciidoctorj 3.0.0?

**Comment by robertpanzer** [comment]
I don't personally maintain the chocolatey packages.
I happily accept pull requests for these packages, but I don't maintain them myself.
Feel free to create a PR or an issue for that, but it feels unrelated to this ticket.
