### ISSUE TITLE
correctly substitute attributes in block macro target

### ISSUE THREAD

**Issue by domgold** [asciidoctor/asciidoctorj#213]
Using a custom block macro, when the target contains attributes, these attributes don't get replaced.

````
:my-attr: hello

mymacro::{my-attr}/world[]
````

The target passed to the block macro processor is `{my-attr}/world`, where I expect it to be `hello/world`.

I discovered this using asciidoctorj but it is probably handled in ruby.

**Comment by robertpanzer** [comment]
Closed as recommended by @domgold
