### ISSUE TITLE
Test suite is leaking memory

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctorj#221]
The test suite is leaking memory badly. That's the reason why the builds on Travis CI have been failing. Midway through the test suite, the JVM runs out of memory (unless you give it >= 2GB of headroom).

I think the problem is that instances of the JRuby runtime are being created through the Asciidoctor interface but cannot be GC'ed until after the whole suite is done. We need to find a way to shut down the JRuby runtime as the test progresses.

I was able to solve this when running on Travis CI by forking the JVM for each test class (i.e., `-DforkMode=always`). However, this is definitely not the ideal solution long term.

Part of me is wondering if we should use Arquillian as an embedded container to provide a pool of JRuby runtime instances. If that's deemed too heavyweight, please suggest an alternative way to pool the JRuby runtime instances so they can be managed and kept under control.

**Comment by robertpanzer** [comment]
I tried to reproduce the problem so that I could test it with my arquillian adapter.
But unfortunately the tests still run;-) with a max heap size of 256m with both Java 8 and 6.
Is there probably a better separation of tests in gradle 2.2.1?

Using the arquillian adapter would mean that it would have to be possible to pass the Ruby instance to JRubyAsciidoctor.create() so that it can be terminated by the adapter.

**Comment by robertpanzer** [comment]
And certainly I set forkEvery to 0.

**Comment by mojavelinux** [comment]
As I mentioned at JavaLand, I think we're going to let this one go and focus on switching the test suite to Arquillian. Then, the problem will be resolved in a much better way.

**Comment by mojavelinux** [comment]
Should we leave this open until we fix up the test suite or should we just close it knowing that we are working on a replacement?

**Comment by robertpanzer** [comment]
I'd close it.
Even though I tried hard I did not manage to provoke an OOM error.

I just went through the code in JRubyAsciidoctor and JavaEmbedUtils.initialize() and I am little bit confused about the many ways there are to create Ruby instances... It's a little confusing.

**Comment by mojavelinux** [comment]
Okay, let's close it.

> I am little bit confused about the many ways there are to create Ruby instances... It's a little confusing.

Hopefully reworking the test suite will bring both the experience and clarify we need.

**Comment by robertpanzer** [comment]
@mojavelinux Just found #156 again! That goes into the direction the arquillian container is currently using! :)

**Comment by mojavelinux** [comment]
Nice! We definitely want to get there. Lots of improvements can still be made.
