### ISSUE TITLE
Introduce the AbstractNode interface

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctorj#242]
Introduce the AbstractNode interface that serves as a proxy to the [AbstractNode](http://www.rubydoc.info/github/asciidoctor/asciidoctor/Asciidoctor/AbstractNode) in Asciidoctor. This new interface should be inserted into the hierarchy so that all other nodes descend from it.

The hierarchy should be as follows:

```
AbstractNode
    AbstractBlock
      Block
      Document
      Section
    Inline
```

NOTE: We'll also need to address lists and tables in the future, but let's start with what we have.

Here's what I think needs to be fixed in the hierarchy once AbstractNode is introduced:

* AbstractBlock should be an AbstractNode
* Document should be an AbstractBlock
* Inline should be an AbstractNode

We'll also need to deal with the shadow AST that we have to support structured documents. Ideally, we should only have one AST hierarchy, not two :)

**Comment by robertpanzer** [comment]
AbstractNode (or soon possibly ContentNode, see #371) is now part of AsciidoctorJ 1.6.0
