### ISSUE TITLE
Registering java extensions fails because java_import syntax

### ISSUE THREAD

**Issue by ktoso** [asciidoctor/asciidoctorj#250]
Hi guys,
a rather surprising problem I bumped into today, seems I'm unable to register extensions implemented in Java (well Scala, but I don't think it matters for the subject at hand) due to a syntax (?) problem with how `import_java` is being used in `JavaExtensionRegistry` here: https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-core/src/main/java/org/asciidoctor/extension/JavaExtensionRegistry.java#L63

I know a bit of JRuby and know that the syntax "should" be valid, yet if fails for me with:

```
org.jruby.exceptions.RaiseException: (NameError) undefined local variable or method `pl' for main:Object
    at RUBY.(root)(<script>:1)
    at pl.project13.scala.sbt.SbtAsciidoctor$$anonfun$asciidoctorSettings$6$$anonfun$apply$1.applyOrElse(SbtAsciidoctor.scala:81)
    at pl.project13.scala.sbt.SbtAsciidoctor$$anonfun$asciidoctorSettings$6$$anonfun$apply$1.applyOrElse(SbtAsciidoctor.scala:61)
    at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
    at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
    at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
    at scala.collection.TraversableLike$$anonfun$collect$1.apply(TraversableLike.scala:278)
```

The extension being an `pl.project13.scala.sbt.extension.HtmlLayoutWrapper`.

I found that quoting the imported class solves the problem, so instead of:

``` scala
          ruby.evalScriptlet(s"java_import ${p.getClass.getCanonicalName}")
          module.postprocessor(p)
```

doing:

``` scala
          val rubyRuntimeField = extensionRegistry.getClass.getDeclaredField("rubyRuntime")
          rubyRuntimeField.setAccessible(true)
          val ruby = rubyRuntimeField.get(extensionRegistry).asInstanceOf[Ruby]

          val asciidoctorModuleField = extensionRegistry.getClass.getDeclaredField("asciidoctorModule")
          asciidoctorModuleField.setAccessible(true)
          val module = asciidoctorModuleField.get(extensionRegistry).asInstanceOf[AsciidoctorModule]

          ruby.evalScriptlet(s"java_import '${p.getClass.getCanonicalName}'") // notice the ' here! this works!
          module.postprocessor(p)
```

This is on `asciidoctorj-1.5.2.jar` extecuted inside sbt `0.13.7`, and I don't think it's a classloader issue (worked around those already).

Anyway, if you'd be happy to accept a PR with the added quotes I'd happily submit one as I could throw out my ugly hacks from the sbt plugin then ;-)

Oh, and merry x-mas guys! :christmas_tree:

**Comment by axelschoener** [comment]
The problem is still present. I don't find it in the announced 1.5.2.1/1.5.3 milestones.
Will it be possible in the next release?
