### ISSUE TITLE
Create a subproject to bundle Asciidoctor Diagram

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctorj#265]
Create a subproject to bundle Asciidoctor Diagram as asciidoctorj-diagram.

It's just too painful to use a Ruby library in JRuby without bundling, so let's move forward with a parallel solution to Asciidoctor PDF and Asciidoctor EPUB3 for Asciidoctor Diagram.

**Comment by purplefox** [comment]
That would be great :)

(I would also be great if it was possible to use graphviz with asciidoctor-diagram without having to have it pre-installed and available on the PATH - this currently prevents us from using it as our Maven builds need to be self-contained with no extra setup steps required)

**Comment by mojavelinux** [comment]
I was actually thinking about bundling graphviz as part of the jar. Unfortunately, it's a native library, so that would mean either downloading it on demand for the current platform or bundling the binary for each major platform. It would be idea if there were something written in Java that could replace it. It seems like something is brewing in ZEST, but that could be a ways off yet: http://wiki.eclipse.org/Zest

**Comment by mojavelinux** [comment]
:+1:

This will no doubt be a very popular module!
