### ISSUE TITLE
Is there a way to center tables on the page?

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctorj#279]

**Comment by lordofthejars** [comment]
I don't know it doesn't seem. Probably this should be done by modifying css. I have inspected documentation of AsciiDoc and Asciidoctor and I have not found anything. Because this is an issue of Asciidoctor (and not AsciidoctorJ), can you open the issue there?

Thank you so much.

**Comment by mojavelinux** [comment]
Correct, we don't implement centering of tables. At the moment, we only support floating to the left or right. I agree this is probably something that should be handled in the CSS and controlled using a role. The question is whether we should provide a built-in role for this behavior. Something like "center" or "element-center" (to match "text-center").

```
[.center]
|===
|===
```

The CSS to center a block object (like a table) horizontally is:

```
.center {
  margin-left: auto;
  margin-right: auto;
}
```

Of course, the width of the table has to be less than 100%.

**Comment by mojavelinux** [comment]
If you open this in Asciidoctor core, I'd be glad to add a centering role to the CSS. That at least gets us started (we already have roles for left and right).

**Comment by mojavelinux** [comment]
The title of the issue should be something like "add a center CSS class to the default stylesheet"

**Comment by MagnusMG** [comment]
If anybody else stumbles upon this I can tell them that you can now (version 2.0.17) center a table by adding the role 'center' to it. For example:
```
[.center, cols="3,1,1", width=75%]
|===
|a|b|c
|===
```

Thanks, @mojavelinux, I guess you did that.
