### ISSUE TITLE
PDF with no cover page

### ISSUE THREAD

**Issue by kastork** [asciidoctor/asciidoctorj#280]
I've searched, but I can't find a way to get the document's title and author data to just be at the top of the first page.  PDF backend always renders the title info as a cover page, even for the article doc type -- is there a way?

I know I can just skip the document header and use the level one section as the title of the doc, but then numbering is strange because all my first level headings look like second level headings.

I figure I'm just missing something simple.

**Comment by lordofthejars** [comment]
Hi can you open this issue to https://github.com/asciidoctor/asciidoctor-pdf because this issue is related to pdf project. Thank you so much :)
