### ISSUE TITLE
Attributes.setCacheUri looks like a cut-and-paste error

### ISSUE THREAD

**Issue by ndw** [asciidoctor/asciidoctorj#288]
Somehow I don't think this is intended, though maybe it doesn't matter.

 public void setCacheUri(boolean hardbreaks) {
        this.attributes.put(CACHE_URI, toAsciidoctorFlag(hardbreaks));
    }

**Comment by mojavelinux** [comment]
Yes, this is definitely a typo. Thanks for pointing this out. @robertpanzer, this seems pretty simple to fix. The local variable has the wrong name. Can you correct?

**Comment by robertpanzer** [comment]
Sure!
Will do next week once I am back in Germany. 
I'll also try to add some javadoc to the other methods that links to the user manual because I think the attribute names sometimes do not explain what they do by themselves.

**Comment by mojavelinux** [comment]
Super! I'll assign it to you. I'll let you decide which branch to commit to, but since it's a non-functional change, I think it's fine to go into 1.6.0.

**Comment by robertpanzer** [comment]
I'd have said that I also fix it in master because it's so super easy:)

**Comment by mojavelinux** [comment]
Sounds good. Enjoy the rest of your trip, btw!

**Comment by robertpanzer** [comment]
Also fixed in 1.6.0 with https://github.com/asciidoctor/asciidoctorj/commit/60371415726b592da30e3328bf20202670ff8b0e

**Comment by mojavelinux** [comment]
+1

Thanks Robert!
