### ISSUE TITLE
Anchors don't seem to work in org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.6

### ISSUE THREAD

**Issue by RobWin** [asciidoctor/asciidoctorj#290]
Hello,

anchors (or section links) don't seem to work in org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.6.
I use org.asciidoctor:asciidoctor-gradle-plugin:1.5.2 and create HTML and PDF as follows.
HTML anchors do work.

```
asciidoctor {
    sources {
        include 'index.adoc'
    }
    backends = ['html5', 'pdf']
}
```

The index.adoc contains

```
:doctype: book
:toc: left
:toclevels: 2
:numbered:
:sectlinks:
:sectanchors:

include::paths.adoc[]
include::definitions.adoc[]
```

An AsciiDoc anchor (to Order) looks as follows:

```
==== Parameters
[options="header"]
|===
|Type|Name|Description|Required|Schema
|BodyParameter|body|order placed for purchasing the pet|false|<<Order>>
|===
```

Might it be an issue that I include the .adoc files into an index.adoc?

Kind regards,

Robert Winkler

PS: I use AsciiDoctorJ in https://github.com/RobWin/swagger2markup

**Comment by lordofthejars** [comment]
I am not suer anchors (section links) should work in pdf, have you tried using native pdf? I think that this will be a bug on pdf converter (if it is possible to do anchors in pdf of course)

**Comment by RobWin** [comment]
Which PDF converter is used in org.asciidoctor:asciidoctorj-pdf?

**Comment by lordofthejars** [comment]
The same as asciidoctor, in fact it is a direct call using JRuby

El dj., 16 abr., 2015 a les 9:17, Robert Winkler (<notifications@github.com>)
va escriure:

**Comment by lordofthejars** [comment]
No worries :) It is a bug on asciidoctor-pdf, in next version it will be fixed :)

**Comment by RobWin** [comment]
Why did you close the bug? Is the next version available?

**Comment by lordofthejars** [comment]
No but the bug is not related with this project but asciidoctor pdf
project. The good news is that there is a PR there waiting to be accepted
so next version will fix it. So we can say that it is not necessary to open
this issue in asciidoctor pdf project because it would be a duplicated

:)
El dv., 17 d’abr., 2015 a les 7.18 Robert Winkler <notifications@github.com>
va escriure:

**Comment by RobWin** [comment]
ok. thx for the clarification :)
