### ISSUE TITLE
Spring Boot and AsciiDoctorJ with JRuby

### ISSUE THREAD

**Issue by RobWin** [asciidoctor/asciidoctorj#291]
Hello,

I try to use AsciiDoctorJ in a Spring Boot App Controller.

````
String asciiDoc = Swagger2MarkupConverter.from(swagger).build().asString();
String asciiDocAsHtml = Asciidoctor.Factory.create().convert(asciiDoc, OptionsBuilder.options().backend("html5").headerFooter(true).safe(SafeMode.UNSAFE).docType("book")
                            .attributes(AttributesBuilder.attributes()
                                    .tableOfContents(true)
                                    .tableOfContents(Placement.LEFT)
                                    .sectionNumbers(true)
                                    .hardbreaks(true)
                                    .setAnchors(true)
                                    .attribute("sectlinks")));
```

But it fails in JRubyAsciidoctorModuleFactory.createAsciidoctorModule() in
```
 evaler.eval(runtime, script);
```

![image](https://cloud.githubusercontent.com/assets/5815046/7183930/a4de5f48-e45a-11e4-82a6-03469bf56f15.png)

It says it can't find JRuby?? But jruby-complete-1.7.16.1 is on the classpath. Sry if it's a noob question, but I'm new to JRuby. 
Do I have to install Ruby on my system? I hope not.

Kind regards,

Robert Winkler

**Comment by lordofthejars** [comment]
No worries :) It is a bug on asciidoctor-pdf, in next version it will be
fixed :)

El dj., 16 abr., 2015 a les 17:07, Robert Winkler (<notifications@github.com>)
va escriure:

**Comment by RobWin** [comment]
@lordofthejars Asciidoctor-pdf? Is this your answer to the other issue #290 ? ;-)

**Comment by lordofthejars** [comment]
Yes sorry I have mixed issues, no you don't need to have JRuby installed on
your system, but JRuby may have some problems finds gems (Which doesn't
seem your problem), in case you are using different classpath loaders like
OSGI but I think that in Spring Boot this is not a problem. Have you tried
converting a really simple hello world document?



El dj., 16 abr., 2015 a les 19:23, Robert Winkler (<notifications@github.com>)
va escriure:

@lordofthejars <https://github.com/lordofthejars> Asciidoctor-pdf? Is this

**Comment by RobWin** [comment]
Yes often in unit Tests. In general AsciiDoctorJ is working, but not in this Spring Boot controller.

**Comment by lordofthejars** [comment]
Is it possible to share the code in github so I can debug it?

El dj., 16 abr., 2015 a les 20:33, Robert Winkler (<notifications@github.com>)
va escriure:

**Comment by RobWin** [comment]
Yes. But might be not that easy to debug yet, because its just a submodule of springfox. https://github.com/RobWin/springfox/tree/master/springfox-staticdocs

**Comment by RobWin** [comment]
I will solve it differently now.
