### ISSUE TITLE
org.asciidoctor.extension.internal.ExtensionRegistryExecutor use badly service loader

### ISSUE THREAD

**Issue by rmannibucau** [asciidoctor/asciidoctorj#292]
Hi

Shouldnt org.asciidoctor.extension.internal.ExtensionRegistryExecutor use a ServiceLoader by classloader (ie use TCCL each time you create a new instance) to be able to pick up contextual extensions?

I particularly think to the case when adocj is in the container and some extensions in webapps for EE case

If not would be good to at least be able to switch this logic.

**Comment by robertpanzer** [comment]
You mean instead of a static field holding the ServiceLoader having a field or only a local variable in registerAllExtensions()?

Sounds reasonable to me. 
But I am unable to test that atm, on vacation without PC.

**Comment by robertpanzer** [comment]
BTW: ServiceLoader always uses TCCL if no other ClassLoader given;-)

public static <S> ServiceLoader<S> load(Class<S> service)


Creates a new service loader for the given service type, using the current thread's context class loader.
An invocation of this convenience method of the form

 ServiceLoader.load(service)
is equivalent to
 ServiceLoader.load(service,
                    Thread.currentThread().getContextClassLoader())

**Comment by lordofthejars** [comment]
You can always register the extension manually without using ServiceLoader
approach. I think it  is a workaround to that problem.

El dv., 24 abr. 2015 a les 16:50, Robert Panzer (<notifications@github.com>)
va escriure:

**Comment by rmannibucau** [comment]
sure but think it doesnt hurt to update it to get it working OOTB - not a big bug BTW, no need to fix it today ;)

**Comment by robertpanzer** [comment]
Fixed with 08aa3402c4d0f07786fa4ccb9fc40163d96c734e
