### ISSUE TITLE
AsciidoctorJ in an OSGi context

### ISSUE THREAD

**Issue by twasyl** [asciidoctor/asciidoctorj#293]
Hello,

I am using asciidoctorj in my project, within an OSGi context. I faced some issue regarding making it working and I wanted to share how I succeeded in case it may help someone else.

In a non OSGi context, the following line works fine for creating an `Asciidoctor` object:

``` java
Asciidoctor asciidoctor = Asciidoctor.Factory.create();
```

A simple unit test can demonstrate it. But in an OSGi context it doesn't because JRuby needs some paths to find the gems. In order to make it work, you will need two more classes (`RubyInstanceConfig` and `JavaEmbedUtils`) and a small modification of the previous line of code. The modifications take care of the class loaders because in OSGi, class loading is one of the most tricky point (IMHO)

``` java
RubyInstanceConfig config = new RubyInstanceConfig();
config.setLoader(this.getClass().getClassLoader());

JavaEmbedUtils.initialize(Arrays.asList("META-INF/jruby.home/lib/ruby/2.0", "gems/asciidoctor-1.5.2/lib"), config);

Asciidoctor asciidoctor = Asciidoctor.Factory.create(AsciidoctorMarkup.class.getClassLoader());
```

In few words what it does:
- the RubyInstanceConfig will use the class loader of the OSGi, where this code is placed ;
- the JavaEmbedUtils will specify the load paths of the required gems. If they are not specified, it won't work. Some times ago I didn't need to specify the `META-INF/jruby.home/lib/ruby/2.0` to make this work. But now I need otherwise I get an `org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- set`. I can not determine if it is an environment issue, a needed order in the dependencies, or something else ;
- the factory for the Asciidoctor object also specify the class loader to use.
- _Benefit:_ you don't need to extract the gems located in the asciidoctorj binaries, as mentioned in other posts.
- _Drawbacks:_ 
  - the version of asciidoctor is hard coded;
  - the version of ruby is hard coded.

The complete code can be found [here](https://github.com/twasyl/SlideshowFX/blob/master/SlideshowFX-asciidoctor/src/main/java/com/twasyl/slideshowfx/markup/asciidoctor/AsciidoctorMarkup.java).

I hope it could be helpful for someone else.
Cheers

**Comment by lefou** [comment]
Thanks for sharing this! Would be really cool to have this integrated into the documentation, though, as it might be overlooked later when this issue got closed.

**Comment by mojavelinux** [comment]
Finally, a clear solution for using AsciidoctorJ in OSGi! Thanks for working this out and documenting it, @twasyl. Would you be willing to resubmit as a pull request to patch it into the README.adoc? (Currently, the README.adoc serves as the user manual for AsciidoctorJ). I'm not super concerned where it goes as long as it makes it into that file. Perhaps the section after "JRuby instance".

I propose naming the new section, "Using AsciidoctorJ in an OSGi environment". wdyt?

**Comment by twasyl** [comment]
I'm OK with that name. I'll create a PR with the modification of the README. I think it's the right place to have this tracked instead of searching within the issues.
Cheers

**Comment by mojavelinux** [comment]
Excellent!

**Comment by lordofthejars** [comment]
I think we can close this issue

**Comment by mojavelinux** [comment]
Yep!
