### ISSUE TITLE
Allow JRuby mode to be specified

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctorj#296]
Right now we are defaulting the Ruby mode to 2.0, but not providing anyway to change this (that I can tell). It seems we are overridding whatever the user is setting. Expose this as an option, or honor the value set in `JRUBY_OPTS` or `-Djruby.compat.version` so that there is some way to override this value. This is particularly important when working with the Maven plugin.

We've encountered an issue whereby setting the Ruby mode to 2.0 has caused remote includes to note work. See https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/153

**Comment by mojavelinux** [comment]
If it is possible to set the JRuby mode, then this needs to be documented in the manual (aka README).

**Comment by mojavelinux** [comment]
I now believe that we should not be specifying the Ruby mode by default. (Experience has led me to change my opinion on this matter). We allow different versions of JRuby to be used, so by setting the Ruby mode, we cause issues rather than solving them. When JRuby 9.0.0.0 is used, for instance, we are downgrading the Ruby mode from 2.1 to 2.0.

I think the Ruby mode should be purely a user setting. We should allow it to be set however it is normally set in JRuby, plus perhaps we can have an option to the API as well. Most important, we should document how it works.

**Comment by robertpanzer** [comment]
Do you think it would work out to add a parameter `Map<String, String> runtimeConfig` to the  `Asciidoctor.Factory.create()` methods that contain properties to customize the Ruby config?

So an Asciidoctor instance with Ruby 1.9 could be created like this:

```java
List<String> loadPaths = ...
Map<String, String> rubyRuntimeProps = new HashMap<>();
rubyRuntimeProps.put("compatVersion", "1.9");
Asciidoctor asciidoctor = Asciidoctor.Factory.create(loadPaths, rubyRuntimeProps);
```

JRubyAsciidoctor would be in charge of recognizing these parameters and handle them appropriately.

The downside would be that we would reach 10 create methods in Asciidoctor.Factory.

The advantage is that it would keep the door open for supporting other runtimes, that surely will need some kind of configuration as well.

**Comment by mojavelinux** [comment]
This is a great question, but again I'm torn. It's probably very unlikely that you'd need to configure JRuby differently per Asciidoctor instance. On the other hand, if you are using different implementations, then you might find yourself using this configuration more often.

From looking at the JRuby docs (aka the wiki), it seems like it's more typical to configure JRuby globally per JVM using either a config file, JVM properties or the JRUBY_OPTS env var. What I think we should focus on first is that those option need to be honored...particularly the `compatVersion`. Once we are honoring them, then I think we can move forward and think about passing an options map to the API.

**Comment by mojavelinux** [comment]
To step back a bit on this, I really wonder if it's even the responsibility of AsciidoctorJ to be setting the Ruby mode in JRuby. JRuby provides an environment variable (JRUBY_OPTS) for this very purpose. We can support passing on an environment, as we do, and maybe that's enough. We've learned from experience that messing with the Ruby mode can actually cause problems because it puts JRuby into some sort of hybrid state. Just like all other Ruby's, JRuby should just support what it supports by default and we should use it that way.

**Comment by mojavelinux** [comment]
...and now that JRuby 9.0.0.0 is almost out, I don't think JRuby is going to be lagging behind anymore, which was sort of why the Ruby mode got introduced in the first place.

**Comment by robertpanzer** [comment]
I digged into the JRuby (1.7) sources.
It seems that the options are eventually all retrieved from system properties, reading an environment variable seems to be on top:
https://github.com/jruby/jruby/blob/jruby-1_7/core/src/main/java/org/jruby/util/cli/Options.java#L126
and then
https://github.com/headius/options/blob/master/src/main/java/com/headius/options/Option.java#L402

I also ran the AsciidoctorJ test suite commenting out the options `compat.version` and `compile.mode` and it still runs, so I am a bit unsure about the reasoning behind setting these options.
I checked that `RUBY_VERSION` is `1.9.3` after commenting out.
(Funny that I could no longer find the compat.version option on the JRuby head...)

What about setting the default options as they are today only if the system properties `jruby.compat.version` and `jruby.compile.mode` are not set respectively?

After commenting out setting the properties, starting AsciidoctorJ with the system property `jruby.compat.version=2.0` indicates `RUBY_VERSION=2.0`.

It would not cater for scenarios where AsciidoctorJ is used in multiple configurations requiring different settings but we would definitely be one step farther.
(Even though a caller could set the system props before and reset after the Asciidoctor instance is created.)

Wdyt?

**Comment by robertpanzer** [comment]
P.S.: We would also need a way to set these options from the CLI. 
We could for instance add an option `-R` to set a jruby option so that an invocation to render a file with compat version 1.9 would look like this:

```
asciidoctorj -Rcompat.version=1.9 my.adoc
```
This would result in setting the system property `jruby.compat.version`
Thereby you could set all options just as documented in https://github.com/jruby/jruby/wiki/ConfiguringJRuby

**Comment by robertpanzer** [comment]
Created PR #342 which implements this simplistic approach.
Let's discuss if this is a viable approach.

**Comment by mojavelinux** [comment]
> I also ran the AsciidoctorJ test suite commenting out the options compat.version and compile.mode and it still runs

That's to be expected given that Asciidoctor is still compatible with all versions of Ruby (from 1.8.7 to 2.2).

> I am a bit unsure about the reasoning behind setting these options.

I do recall the reasoning behind this change. Encoding is a nightmare in Ruby 1.9 (which JRuby faithfully honors). When the compat.version is set to 2.0, these encoding problems go away (as they were finally addressed in Ruby 2). I recommended that we add a way to set the compat.version to 2.0 (since JRuby 9.0.0.0 wasn't yet viable). I may have been too adamant about this change because we then decided to set the compat.version to 2.0 permanently. In hindsight, I see that this was a mistake since the Ruby 2 mode in JRuby 1.7 isn't complete enough.

> What about setting the default options as they are today only if the system properties jruby.compat.version and jruby.compile.mode are not set respectively?

I'm confident now that we shouldn't set the compat.version by default at all. Instead, we should only focus on honoring the user's setting. If the user doesn't set anything, neither do we.

> After commenting out setting the properties, starting AsciidoctorJ with the system property jruby.compat.version=2.0 indicates RUBY_VERSION=2.0.

Very nice.

The next step is to allow the caller to pass either an environment map or properties to the AsciidoctorJ API so as to isolate it from the system environment. By default, in this case, it should inherit the system environment setting JRUBY_OPTS. (We still isolate from the system Ruby and RubyGems environment, but that is a different thing, IMO).

**Comment by mojavelinux** [comment]
> We could for instance add an option -R to set a jruby option so that an invocation to render a file with compat version 1.9

I like the idea, but instead I think we should be consistent with the jruby command and support the `-J` flag to pass options to the JVM:

```
asciidoctorj -J-D=jruby.compat.version=2.0 sample.adoc
```

I realize it looks a bit clunky, but it's something users of JRuby are used to.

The benefit is that users will also be able to control other JVM settings.

I'd also be open to supporting the flag `--jrubyrc` to support passing in a file with these options in it. That also raises the question of how we handle the default $HOME/.jrubyrc file, but we can deal with that in a separate thread.

**Comment by mojavelinux** [comment]
The other benefit of the `-J` flag is that it doesn't tie the CLI too closely to JRuby. We know we are running on the JVM. We don't know for sure what language we'll be using though (once we support more than one).

**Comment by mojavelinux** [comment]
Actually, I think this makes it obvious what the AsciidoctorJ API should do. The AsciidoctorJ API should accept the equivalent to what would be the `-J` flag. Once again, that keeps us from getting tied to closely to JRuby and instead view it as passing in JVM options to the AsciidoctorJ API.

**Comment by robertpanzer** [comment]
> Am 26.06.2015 um 22:54 schrieb Dan Allen <notifications@github.com>:
> 
> I like the idea, but instead I think we should be consistent with the jruby command and support the -J flag to pass options to the JVM:
> 
> asciidoctorj -J-D=jruby.compat.version=2.0 sample.adoc
I agree 100%, the only issue I have with -Djruby.compat.version=xy is that the compat.version property in some .rc file is documented. But I had to look up the sources to find out that this maps to a system properly jruby.compat.version. 
The docs from JRuby for this could be ... enhanced

**Comment by mojavelinux** [comment]
> The docs from JRuby for this could be ... enhanced

100% agreement. That goes for a lot of the JRuby docs :)

**Comment by robertpanzer** [comment]
I'll try to get sth running like this once I'm sober again 🍻;-)

**Comment by mojavelinux** [comment]
Whooooooooooo

**Comment by robertpanzer** [comment]
I've just seen that the asciidoctorj start script sets these system properties as well: :)
https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-distribution/build.gradle#L27

> I like the idea, but instead I think we should be consistent with the jruby command and support the -J flag to pass options to the JVM:

Sounds like a good idea.
In JRuby these options are parsed in the shell script and the string after the -J is added to the java launch command.
Should we go this far as well?
As far as I understand the application plugin it does not support options like this out of the box, so we would have to write the scripts ourselves (and take the current ones as a starting point.)
(This would pretty much reduce the changes in the Java code;-) )

> I'd also be open to supporting the flag --jrubyrc to support passing in a file with these options in it. That also raises the question of how we handle the default $HOME/.jrubyrc file, but we can deal with that in a separate thread.

To me both sound like a good idea. (But would again require some code changes in Java;-) )

**Comment by robertpanzer** [comment]
Opened PR #344 that completely removes setting of any JRuby related options.
This should be a first step until we are clear how we want to enable setting the JRuby options by the user.

One strange thing that I am seeing when trying to learn how JRuby handles this:
I tried:
```jruby -J-Djruby.compat.version=1.9 -e 'puts RUBY_VERSION'```
and it says `2.0.0`.

I checked what the script does and it correctly sets the Java system property ruby.compat.version. 
When I set it to an illegal value I get an error message.
Nevertheless the script always prints `2.0.0`.
When trying the same in embedded in AsciidoctorJ the system property is correctly evaluated and `RUBY_VERSION` evals to ' 1.9.3' .

Even with a file '~/.jrubyrc'  that contains 'compete.version=1.9'  the script prints '2.0.0'.
Maybe someone could check if he sees the same output...

**Comment by robertpanzer** [comment]
I finally managed to resolve my strange problem, that a java option passed to jruby is not processed:
I tried it on Windows!
On Windows these parameters are simply not evaluated at all! 

That means that for a `test.rb` with content
```puts RUBY_VERSION```

`jruby.sh -J-Djruby.compat.version=2.0 test.rb`
will show `2.0.0`.
`jruby.bat -J-Djruby.compat.version=2.0 test.rb`
will show `1.9.3`.

**Comment by robertpanzer** [comment]
Merged #344.
So at least AsciidoctorJ is no longer blocking options that were set externally.

No I also found out how JRuby options are processed in JRuby:
On Unix this is done in the `jruby.sh`: It takes the `-J` options, checks the following substring for special options like `-X...` etc and appends it to the invocation of java, so that `jruby -J-Djruby.compat.version=2.0` results in an invocation of `java -Djruby.compat.version=2.0`.

On Windows this is done in native code that can be found at https://github.com/jruby/jruby-launcher/blob/master/argparser.cpp#L341-L348

**Comment by mojavelinux** [comment]
>  I also found out how JRuby options are processed in JRuby

Amazing. This seems to be one of those rabbit hole issues. Always going deeper! :)

**Comment by robertpanzer** [comment]
BTW: The environment variable `JRUBY_OPTS` is also handled by `jruby.sh`. :)

**Comment by robertpanzer** [comment]
That reminds me that we have no way at the moment to modify these settings for users that start the `asciidoctorj` script.

**Comment by robertpanzer** [comment]
And the decribed `JRUBY_OPTS` described in the README only works on Windows! To set the ruby mode to 2.0 on unix it is necessary to set `JRUBY_OPTS=--2.0`.

**Comment by mojavelinux** [comment]
For the record, I'm fine if the instructions are different per platform. All users really want to know is what to type when. If we can give them that, we've succeeded I think.

**Comment by mojavelinux** [comment]
> To set the ruby mode to 2.0 on unix it is necessary to set JRUBY_OPTS=--2.0.

Of course, this is going to go away pretty soon anyway as soon as JRuby 9.0.0.0 is released. So if the instructions seem strange, it's really just a short-term thing. And experience now tells me that setting the Ruby mode is a bad idea anyway. (the compile.mode is a different matter because that actually does mean something).

**Comment by mojavelinux** [comment]
To be clear, as soon as JRuby 9.0.0.0 final is released, we should start pushing for it really hard because it's going to be much better for our users.

**Comment by robertpanzer** [comment]
> For the record, I'm fine if the instructions are different per platform. All users really want to know is what to type when. If we can give them that, we've succeeded I think.

For the "integrator" it will be the same for all platforms. 

For the user of the asciidoctorj script there is no way to make these settings other than modifying the script!
So we still have to think about a solution for this.

**Comment by mojavelinux** [comment]
Can't we inject additional code into the generated script? Ideally, we want to emulate the behavior of JRUBY_OPTS I think. I guess that means diving into the Gradle user guide again and trying to figure out how we can customize the script. :scream:

**Comment by robertpanzer** [comment]
The template engine seems to be rather limited to only allow a set of options and names.
It think to make it fully customizable it would mean to implement an own ScriptEngine:
https://docs.gradle.org/current/groovydoc/org/gradle/jvm/application/tasks/CreateStartScripts.html#getUnixStartScriptGenerator()
https://docs.gradle.org/current/groovydoc/org/gradle/jvm/application/scripts/ScriptGenerator.html

The question is if we really need generated scripts?
One point for example that I don't like about them, is that I have to modify the classpath in the script if I want to add the asciidoctorj-diagram extension. I would prefer to add all jars in the lib directory to the classpath.
(OK, now we have the `--classpath` option to help around this extra work)

**Comment by robertpanzer** [comment]
This is the template:
https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
Not really customizable.
Maybe it's best to take this as a starting point and go our own way.

**Comment by robertpanzer** [comment]
Just want to note here that JRuby properties can now be set via a .jrubyrc file in case someone finds this issue while trying to figure out how to do that. See #347

**Comment by mojavelinux** [comment]
I like the options as they are currently implemented. I'd like to avoid going deeper into the rabbit hole for now as these options aren't that critical. Messing with start scripts is an overhead I don't think we want to take on.

As I mentioned, so long as there is some way to set them (which there clearly is now), I think we should take a step back and focus on more high priority tasks. If someone comes along and really wants to propose a more drastic change, then I think we can reconsider then.

**Comment by robertpanzer** [comment]
Just to wrap up how it's implemented (and documented in the README) beginning with AsciidoctorJ 1.6.0:

AsciidoctorJ now no longer sets any JRuby options.
Instead it runs with the defaults, that is compat.version defaults to 1.9.3 and compile.mode to JIT.

Runtime options can be defined as follows when using the CLI:
Like JRuby AsciidoctorJ will consume `.jrubyrc` files, i.e. a `~/.jrubyrc` with content `compat.version=2.0` will make JRuby run in a 2.0 (semi-)compatible mode.
System properties can also be passed to the `asciidoctorj` script via the environment variable `ASCIIDOCTORJ_OPTS`: `export ASCIIDOCTORJ_OPTS=-Djruby.compat.version=2.0` will also make JRuby run in a 2.0 compatible mode.
Java options like `-Xserver` can be defined using the environment variable `JAVA_OPTS`.

**Comment by mojavelinux** [comment]
Super.

And to further clarify, we should say that those defaults for compat.version and compile.mode are if you are using JRuby 1.7.x. If you are using JRuby 9.0.0.0, then JRuby effectively becomes a Ruby 2.2 implementation.

A very useful flag to pass to JRuby is the `--dev` flag. This flag tells JRuby to run as fast as possible optimized for short operations (such as the `asciidoctorj`) command. Do you know if it's possible to pass this flag to JRuby? We might even want to consider enabling it by default in asciidoctorj.

I also think we should strongly consider switching to JRuby 9.0.0.0 for AsciidoctorJ 1.6.0 (while we're making big changes). By the time AsciidoctorJ 1.6.0 is out, JRuby 9.0.0.0 will be released and we should definitely be looking forward. I've been using it and I can't see any reason to hold back.

**Comment by robertpanzer** [comment]
I fear that these parameters are not supported yet.
As documented in https://github.com/jruby/jruby/wiki/Improving-startup-time `--dev` results in a number of settings that could be mimicked via `JAVA_OPTS` and `ASCIIDOCTORJ_OPTS` but not as comfortable as `--dev`.
The option `--dev` is processed in `jruby.sh` (https://github.com/jruby/jruby/blob/master/bin/jruby.bash#L281) as well as in the java code itself (https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/util/cli/ArgumentProcessor.java#L553) 

What we could do is also accept a subset of the arguments accepted by the ArgumentProcessor and invoke `RubyInstanceConfig.processArguments` with a filtered list of command line arguments.
(Probably passing these arguments to a new `Asciidoctor.Factory.create()` method.)

What do you think?

:+1: for JRuby 9.0.0.0.
Haven't tried it yet but haven't heard anything bad about it yet.

**Comment by robertpanzer** [comment]
BTW the Java options changed by `--dev` are already set by default in our `asciidoctorj` script.

**Comment by robertpanzer** [comment]
```
# Add default JVM options here. You can also use JAVA_OPTS and ASCIIDOCTORJ_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-client" "-Xmn128m" "-Xms256m" "-Xmx256m" "-Xverify:none" "-XX:+UseFastAccessorMethods" "-XX:+TieredCompilation" "-XX:TieredStopAtLevel=1" "-XX:+DisableExplicitGC"'
```

**Comment by mojavelinux** [comment]
:+1: Then we may already be covered.
