### ISSUE TITLE
StackOverflowError when creating asciidoctor object

### ISSUE THREAD

**Issue by pmagon** [asciidoctor/asciidoctorj#299]
In  asciidoctorj-1.6.0: 

    System.out.println ("CREATE");
    Asciidoctor asciidoctor = JRubyAsciidoctor.create ();
    System.out.println ("OK");

The second "System.out.println" breaks.... It seems that "System.out" has been changed on "create"
If I save and restore "System.out" after the call I get the same error on "asciidoctor.convertFiles"...

Robert Panzer said:

> I think the StackOverflow comes from here:
>https://github.com/asciidoctor/asciidoctorj/blob/asciidoctorj-1.6.0/asciidoctorj-core%2Fsrc%2Fmain%2Fjava%2Forg%2Fasciidoctor%2Finternal%2FJRubyAsciidoctor.java#L40

>This is what we already discussed about.
>It does not occur in the gradle tests because Gradle injects its own JUL Logger which breaks the cycle between catching System.out and forwarding it to the default ConsoleHandler which again does a System.out.

**Comment by mojavelinux** [comment]
Even more reason we need to revert the code that's modifying System.out.

**Comment by robertpanzer** [comment]
There is surely a reason for capturing System.out.
If it is a requirement to do so we should look if there is another solution for this.

**Comment by mojavelinux** [comment]
There's already a solution coming. I really want to just remove the code and let it be handled the proper way once the change is made in core. See https://github.com/asciidoctor/asciidoctor/issues/44. AsciidoctorJ shouldn't be trying to solve this problem, IMO.
