### ISSUE TITLE
Upgrade the Slim gem

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctorj#307]
Upgrade the Slim gem (to either 2.1.0 or 3.0.3).

AsciidoctorJ currently bundles Slim 2.0.3. The Slim templates in https://github.com/asciidoctor/asciidoctor-backends require Slim 2.1.0 or better. Therefore, it's not possible to use these templates with AsciidoctorJ without using new version of Slim loaded from an external path.

We probably want to consider upgrading related gems as well, such as Tilt. We also need to figure out if there are any migration issues and document those.

**Comment by mojavelinux** [comment]
cc @jirutka

**Comment by LightGuard** [comment]
I don't recall upgrade issues with slim

On Tuesday, May 12, 2015, Dan Allen <notifications@github.com> wrote:

> cc @jirutka <https://github.com/jirutka>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctorj/issues/307#issuecomment-101466104>
> .
>


-- 
Sent from Gmail Mobile

**Comment by mojavelinux** [comment]
There is at least one incompatibility between Slim 2 and 2.1 in how whitespace at the end of content is declared.

**Comment by LightGuard** [comment]
Ah. Not anything we hit when we upgraded.

On Tuesday, May 12, 2015, Dan Allen <notifications@github.com> wrote:

> There is at least one incompatibility between Slim 2 and 2.1 in how
> whitespace at the end of content is declared.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctorj/issues/307#issuecomment-101508572>
> .
>


-- 
Sent from Gmail Mobile
