### ISSUE TITLE
Regression from jruby 1.7.6 dependency

### ISSUE THREAD

**Issue by jexp** [asciidoctor/asciidoctorj#313]
We ran into this issue when trying to run a build that uses asciidoctorj on an special machine. Are there plans to release an 1.5.3 or 1.5.2.1 with jruby 1.7.20 soonish?

https://github.com/jruby/jruby/issues/2032

**Comment by robertpanzer** [comment]
If we bring a fix for AsciidoctorJ 1.5.2 with an upgraded Ruby version we might also consider going from the jruby-complete module to jruby.
See also #230 and http://discuss.asciidoctor.org/Using-asciidoctorj-pdf-from-gradle-td2731.html

**Comment by tomeast** [comment]
We hit this as well - reverting back to 1.5.1 for now.

**Comment by mojavelinux** [comment]
@tomeast You don't need to revert. Just set the JRuby dependency explicitly. JRuby isn't bundled in AsciidoctorJ, so it's possible to just force the version to be changed. In fact, I even recommend trying JRuby 9.0.0.0 if you're experimenting with JRuby versions.

**Comment by tomeast** [comment]
Thanks for the quick response! Confirmed that explicitly specifying JRuby 9.0.0.0 got us back in business with the latest asciidoctorj.

**Comment by mojavelinux** [comment]
:+1:

**Comment by robertpanzer** [comment]
Fixed with #396
