### ISSUE TITLE
Publish Asciidoctor Arquillian extension

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#318]
#310 added an Arquillian extension that allows to inject Asciidoctor instances, the ClasspathResources and a TemporaryFolder into the test case.

@abelsromero indicated that he'd like to reuse it in the Asciidoctor Maven plugin.
Therefore the Arquillian extension should be published.

I tried to do sth like that but failed due to apparently lacking knowledge about gradle and the nebula publishing plugin.

There are at least two ways to publish the Arquillian extension:

- Make an own publication asciidoctorj-arquillian-extension with an own pom.xml
- Add the Arquillian extension as an additional artifact to the asciidoctorj module with the classifier `tests`.
  What I dislike about this is that it is afaict difficult to define the dependencies of this artifact, i.e. arquillian-container-impl-base etc. so that they are pulled when depending on the asciidoctorj tests artifact.

**Comment by robertpanzer** [comment]
When adding a second publication to asciidoctorj-core I end up with this error:
```
* What went wrong:
A problem occurred configuring project ':asciidoctorj-diagram'.
> Publishing is not yet able to resolve a dependency on a project with multiple different publications.
```

So apparently the Maven Publishing plugin does not fully work with multi module builds:
https://issues.gradle.org/browse/GRADLE-2966

**Comment by robertpanzer** [comment]
Added #319 that adds a new module that publishes the arquillian extension classes from the asciidoctorj-core module.

**Comment by mojavelinux** [comment]
I feel less alone now that someone else is experiencing the problems I was running into when setting up publishing with the Gradle build. I love Gradle, super powerful, but the publishing plugins are extremely poorly done, worse than Maven plugins :/

Perhaps you remember my tweets on this topic: https://twitter.com/mojavelinux/statuses/539145426817933312

**Comment by mojavelinux** [comment]
I never got around to writing up the problem, but I can summarize it rather simply. I should need to put in 50 hacks to make publishing work. It's way too brittle at the moment. The plugin needs to be much more intelligent and aware of what's going on and just do the right thing.

**Comment by mojavelinux** [comment]
Remember Indiana Jones stepping through the room where one false footstep meant death?

![image](https://cloud.githubusercontent.com/assets/79351/7997829/9f40e0e4-0af0-11e5-8d13-abfe6a14efa3.png)

Kind of like that.

**Comment by lordofthejars** [comment]
:laughing:
