### ISSUE TITLE
Asciidoctorj-1.6.0: Add --cp cmdline parameter to distribution

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctorj#320]
Add a `--cp <classpath>` command-line parameter to allow the `asciidoctorj` to search the provided classpaths for additional Java/Groovy/JVM-lang backends.

**Comment by robertpanzer** [comment]
I wonder if it would be sufficient to set the context classloader to a URLClassLoader with the given paths.

**Comment by mojavelinux** [comment]
Isn't this already the default behavior? ...to look for backends on the classpath? Or are you talking about scanning so that you don't have to use the service loader?

**Comment by robertpanzer** [comment]
I think the point is that Schalk has a jar with a converter and possibly extensions somewhere in the filesystem.
And he wants to set that classpath when starting Asciidoctor via the asciidoctorj command line script.

At the moment it is only possible to set the loadpath which is passed directly to the Ruby runtime.
This will only ensure that own Ruby extensions and converters can be used from anywhere on the file system.

**Comment by ysb33r** [comment]
> Isn't this already the default behavior? ...to look for backends on the classpath? Or are you talking about scanning so that you don't have to use the service loader?

When packed as a distribution the wrapper script will set the classpath to be only that of the JARs in the distribution.

> I think the point is that Schalk has a jar with a converter and possibly extensions somewhere in the filesystem.
And he wants to set that classpath when starting Asciidoctor via the asciidoctorj command line script.

And that is exactly what I want to achieve.

**Comment by robertpanzer** [comment]
@ysb33r Did you have sth like this in mind? #321

**Comment by robertpanzer** [comment]
Fixed in asciidoctorj-1.6.0 with a6d524c3dc1

**Comment by mojavelinux** [comment]
:+1:
