### ISSUE TITLE
Link to Javadoc in README

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctorj#324]
We really need to make the Javadoc for AsciidoctorJ available somewhere online and link to it from the docs.

We can reserve a subdirectory (or subdomain) on asciidoctor.org to host it. We might even be able to use the gh-pages branch on this repository to host it. I'm also open to a third-party service (similar to what rubydoc.info provided).

Ideas welcome.

**Comment by johncarl81** [comment]
Hmm, how about via Maven Central:

https://oss.sonatype.org/service/local/repositories/releases/archive/org/asciidoctor/asciidoctorj/1.5.2/asciidoctorj-1.5.2-javadoc.jar/!/index.html

**Comment by mojavelinux** [comment]
That's right. Okay, so we could setup a redirect on asciidoctor.org to find it easier. Perhaps asciidoctor.org/docs/asciidoctorj/api?

**Comment by mojavelinux** [comment]
We could also use javadoc.io as pointed out by Alexander Reelsen.

http://www.javadoc.io/

**Comment by mojavelinux** [comment]
Let's link to javadoc.io since it provides easy access to toggle between versions.

See http://www.javadoc.io/doc/org.asciidoctor/asciidoctorj/1.5.4

**Comment by johncarl81** [comment]
LGTM :+1:

**Comment by mojavelinux** [comment]
I'm not sure where to put the link, so for now I just made it a badge (using a custom shield from shields.io). If you have an example of where projects tend to put the link to the Javadoc, please chime in.

**Comment by mojavelinux** [comment]
See https://github.com/asciidoctor/asciidoctorj/pull/421

**Comment by mojavelinux** [comment]
Ironically, this gets you one step from the Asciidoclet Javadoc as well :)

**Comment by mojavelinux** [comment]
The Asciidoclet Javadoc look really nice. AsciidoctorJ really needs that...especially the intro page :)

**Comment by johncarl81** [comment]
:smiley: Yeah, @benevans work on the stylesheet and overview pages really brought Asciidoclet to the next level.

I thought we were using Asciidoclet (#35)... maybe the conversion to gradle negated this.  I could create another PR with Asciidoclet integration for gradle if that's still desired.

**Comment by johncarl81** [comment]
FYI: https://github.com/asciidoctor/asciidoclet/pull/55

**Comment by robertpanzer** [comment]
The last time I tried to activate Asciidoclet I stumbled over Gradle + the Nebula Publishing Plugin: https://github.com/asciidoctor/asciidoctorj/issues/190
Not sure if it would help to upgrade the Gradle and Nebula deps but the combination of these two seems to be very brittle, so it could be quite some work.

**Comment by mojavelinux** [comment]
I'd definitely like to see that solved, but I know that touching the publishing plugin can be a rabbit hole.
