### ISSUE TITLE
Add support for defining backend name for a converter in the converter class itself

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#334]
Currently the backend name of a converter is only defined when it is registered at the converter registry: `asciidoctor.javaConverterRegistry().register(MyConverter.class, "mybackendname")`

This came up in the discussion in #332:

It should be possible to define at least one backend name in the converter class itself so that the converter can be registered without a backend name: `asciidoctor.javaConverterRegistry().register(MyConverter.class)`

Options are:
- Allow the converter writer to add an annotation to the `Converter` implementation like `@Backend("mybackendname")`
- Add a method `String getBackendName()` to the `Converter` class so that the converter writer is forced to define a backend name. (Even though the abstract base class `AbstractConverter` could return `null`.)

When no default backend name is defined by the converter `register(Class)` could throw an IllegalArgumentException.

**Comment by mojavelinux** [comment]
:+1: 

I think it makes the most sense to advocate for the use of an annotation here and not even provide an alternative. This is purely metadata and I think giving the developer more than one way of specifying it is just misleading. I think we should only consider the static method if we can identify a use case that the annotation doesn't cover.

**Comment by robertpanzer** [comment]
Fixed with #341
