### ISSUE TITLE
Asciidoctorj-1.6.0: Is 'colspan' correctly propagated to API?

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctorj#345]
If I have the following document snippet

```
[chapter]
== Columns that span

|===
|A cell in column 1, row 1|A cell in column 2, row 1|A cell in column 3, row 1

3*|Same cell content in columns 1, 2, and 3

|Cell in column 1, row 3|Cell in column 2, row 3|Cell in column 3, row 3
|===
```

I would expect the `Cell.getColspan()` for the second row to be `2` and `Row.getCells().size() == 1`
Instead what I get is `0` for `getColspan()` and `Row` having three cells with the same content.

I am not sure whether this is a bug in the Ruby->Java translation, an issue in the supplied document snippet or simply my miusunderstanding.

**Comment by robertpanzer** [comment]
I think you got the wrong prefix for the column.
`3*` multiplies the column 3 times.
But if I got you correctly you wanted one column to span over 3 table columns.
You can do that via `3.+|One cell content in columns 1, 2, and 3`

I just pushed a test case:
https://github.com/asciidoctor/asciidoctorj/commit/a4cd1e41feadfdac85baa4f8cb719a3b8b693d11

What I find a bit counterintuitive is that "normal" columns show a collapse of 0.

**Comment by robertpanzer** [comment]
I meant colspan, not collapse. 
.... Autocorrect

**Comment by mojavelinux** [comment]
> What I find a bit counterintuitive is that "normal" columns show a colspan of 0.

Although odd, this is by design as a way to distinguish when a colspan is set and when it isn't. It's actually null when a colspan is not set and a numeric string value when it is set. Maybe not the best way, but that's the story.

**Comment by ysb33r** [comment]
> You can do that via 3.+|One cell content in columns 1, 2, and 3

Thanks. Didn't spot that.

**Comment by robertpanzer** [comment]
I didn't want to complain if I made the impression. 

> Although odd, this is by design as a way to distinguish when a colspan is set and when it isn't.
> 
I didn't think about that case and returning 0 is surely better than returning nil, as this would result in many NPEs in Java extensions:-)

**Comment by ysb33r** [comment]
> I didn't think about that case and returning 0 is surely better than returning nil, as this would result in many NPEs in Java extensions:-)

Indeed.

**Comment by ysb33r** [comment]
Closing - question has been answered.

**Comment by mojavelinux** [comment]
In that case, the default should be 1 rather than 0. If no colspan is set, then the effective value is that it spans 1 column (same for rowspan).
