### ISSUE TITLE
How to handle the attribute attribute_entries?

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#346]
@ysb33r realized while writing table support for his leanpub converter that `AbstractNode.getAttributes().toString()` fails because the attributes hash contains the key `:attribute_entries` (a symbol) and this is not expected at the moment.
The value for this key is a hash that again contains attributes.
In this case it's the counters for tables, figures etc. that are stored in this subhash.

But also if attributes are declared before a table they will appear nested in this subhash:

```
:attr: value
|===
...
|===
```
In this case `AbstractNode#attributes[:attribute_entries]` contains the key `attr`.
(Does that make any sense at all to do so? I am unsure, I just realized it while playing with it.)

What I'd like to discuss as part of this issue is how we want to handle this entry.
Options that come to my mind at the moment are:

A. Ignore this entry as the `AbstractNode#attr` also does not handle this key. Downside would be that there would be no other way to access these values if required.
B. Flatten the nested map so that the content of the nested map. Downside would be that there would be no way to distinguish _real_ attributes from the nested ones.
C. Like A but add a new accessor to the Java interface `AbstractNode` to give access to the subhash.
D. Like A but only add an accessor for the counter. Downside would be that there would be no way to access the other nested attributes.

Another problem I realized is that if you add a positional attribute to a table the (top-level) attributes contains a key `1` (the number, not the string).
How should we handle that?
Add an own accessor `List<String> AbstractNode.getPositionalAttributes()`?

**Comment by mojavelinux** [comment]
I'm inclined to say we should not yet expose this in AsciidoctorJ. This subhash is an artifact of the internal implementation of core and something we've been meaning to change.

For more background, see this issue: https://github.com/asciidoctor/asciidoctor/issues/692

Long story short...document-level attributes need to be nodes in the tree so we don't have to hang them off the side of the next block like we currently do. There are historical reasons for why it is the way it is, but suffice to say we really need to fix this behavior.

**Comment by robertpanzer** [comment]
Committed change to ignore all attributes whose key is not a string.

**Comment by mojavelinux** [comment]
:+1:
