### ISSUE TITLE
Asciidoctorj-1.6.0 support for source_location

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctorj#351]
`AbstractBlock` is missing `source_location` (I guess it should eb called `getSourceLocation` in Java). Although these values are only set when `sourcemap` is passed as an option, the current interface does not allow access to this asciidoctor-ruby attribute at all.

**Comment by mojavelinux** [comment]
>  these values are only set when sourcemap is passed as an option

That may eventually change. It was added as a preview feature. Once we determine it's complete and stable, we may consider enabling it by default, or at least when using the API.

**Comment by robertpanzer** [comment]
Opened #352 to add this functionality
