### ISSUE TITLE
Please add a way to unregister a specific extension (make extension API symmetric)

### ISSUE THREAD

**Issue by lefou** [asciidoctor/asciidoctorj#359]
When registering a extension class, e.g. via the `JavaExtensionRegistry`, there is no way to unregister the same extension besides unregistering all. In `ExtensionRegistry` there is no unregister support at all.

To implement extension support in OSGi via the Whiteboard Pattern (see #297) a way to unregister an extension is needed.

**Comment by mojavelinux** [comment]
Seems reasonable to add. In the current design in core we store extensions by groups, so the first step would be to allow a single group to be unregistered. If necessary, we could go deeper.

It appears like we need to open an issue in core, right?

**Comment by lefou** [comment]
@mojavelinux With core do you mean the Ruby project?

**Comment by robertpanzer** [comment]
I think so. Otherwise I would probably have to modify `Asciidoctor::Extensions::Registry.@groups` directly.

**Comment by mojavelinux** [comment]
Correct, "core" means Asciidoctor Ruby. As Robert points out, without a
method he needs to go for internal access, which is not ideal. Best to
strike at the root first.

**Comment by lefou** [comment]
Im still looking forward to https://github.com/asciidoctor/asciidoctor/issues/1701 as a prerequisite of this issue, so that we can have proper OSGi support with 1.6.x.

**Comment by mojavelinux** [comment]
I'm starting to finalize the 1.5.6 release, so I'll make sure this gets in.

**Comment by lefou** [comment]
https://github.com/asciidoctor/asciidoctor/pull/2265 brings direct support for unregistration of plug-ins.
It would be great, if we could have that functionality also available in the Java API. @robertpanzer, do you see opportunity to work on this? If not, do you mind to give me some hint so that I or others can try to add it?

**Comment by mojavelinux** [comment]
That's absolutely the intention. We'll want to add an unregisterExtension to the Asciidoctor class. This compliments the existing unregisterAllExtensions method. It should accept either a single string or a collection of strings. These strings are group names.

See https://github.com/asciidoctor/asciidoctor/blob/a38de38a15a6bde00d82f687a52601894b096d60/lib/asciidoctor/extensions.rb#L1402-L1410

@robertpanzer Asciidoctor core uses symbols for the group names. However, I've added logic to coerce the argument to a symbol. Let me know if you need me to do this or whether I can assume the argument is a symbol.

**Comment by robertpanzer** [comment]
I can try to get my fingers on it next week.

If anybody wants to have a try before the first thing would be indeed to complement the method unregisterAllExtensions method and add the way into Ruby here:
https://github.com/asciidoctor/asciidoctorj/blob/asciidoctorj-1.6.0/asciidoctorj-core/src/main/resources/org/asciidoctor/internal/asciidoctorclass.rb 

It will be interesting to see what names are being used at the moment when registering extensions.
Without looking at the code I cannot tell atm.

**Comment by mojavelinux** [comment]
That's going to be the trickery part. We need to figure out where and how a group name is assigned to the registry from AsciidoctorJ. In reality, there is not just one registry, but an arbitrary number of registries each stored under a group name. If a group name is not specified, a name is generated. Right now, that name is created in sequence as extgrp${index}, where ${index} is a zero-based sequence. But the Ruby API accepts a name as an argument.

What we could do is have AsciidoctorJ create a group for each extension registered, using the extension class as the group name.

**Comment by robertpanzer** [comment]
Maybe it would make sense then to have AsciidoctorJ generate a name and make the register methods return a registration object on which unregister could be called?

So for example `JavaExtensionRegistry.preprocessor()`  would automatically generate a random name and pass it to the Ruby implementation.

```java
Registration reg = asciidoctor.javaExtensionRegistry().preprocessor(foo); // foo could be a string, class or instance
// ... do whatever
// and then
reg.remove();
```

In this case it would actually be good that we didn't apply a method chaining approach for registering multiple processors because it would make such an approach impossible.

The same could be done with the RubyExtensionRegistry.

Wdyt?

**Comment by robertpanzer** [comment]
Downside of this proposal would be though that it would make the API binary incompatible, leaving the build plugins behind again...

**Comment by mojavelinux** [comment]
As I mentioned in the pull request, it should be possible to supply an explicit group name. It's crucial for organizing groups of extensions.

To avoid breaking binary compatibility (if that's something we decide to pursue), we could accept a group name as another argument to the method. A string would be an explicit group name. A boolean would indicate whether to auto-generate and return a registration object.

Another possible idea, though harder to implement, is to introduce a new chain that hangs off the "group" method. This method would start a group. Then you would register all extensions through that group object, and it could also be used to unregister the group. That would definitely sidestep the whole API compatibility issue...and it would also be very logical.
