### ISSUE TITLE
Make Processor.getRubyRuntimeFromNode() protected?

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#364]
In AsciidoctorJ 1.5.2 you could get a Ruby runtime in a Processor via the member `Processor.rubyRuntime`.
We eliminated that in AsciidoctorJ 1.6.0 for a good reason, just think of a processor instance registered to multiple Asciidoctor instances and therefore multiple Ruby runtimes.

There seems to be a need though to get access to the current Ruby runtime.
In Processor we have a method `Processor.getRubyRuntimeFromNode()` that is private at the moment.
This would allow to get access to the proper Ruby runtime.

Should we make that method protected?
I think it would be good to do so, because it might help people solve problems where we cannot deliver solutions ourselves with the product fast enough.
On the other hand this would bring back Ruby artifacts back to the Processor class that we just got rid of.

Wdyt?

**Comment by robertpanzer** [comment]
Maybe it would be also possible to externalize this accessor to sth like `JRubyRuntimeContext.get(AbstractNode)` so that we still keep Ruby out of the Processor API.

**Comment by mojavelinux** [comment]
I'm in favor of deprecating it.

Although what I'm about to suggest isn't a best practice, it is still possible to get the Ruby runtime in the following way:

```
node.__ruby_object().getRuntime()
```

That's because any object that is being proxied by Ruby allows access to the underlying infrastructure via the RubyObjectHolderProxy interface (probably with some casting in Java).

(This assumption may no longer be valid in AsciidoctorJ 1.6.0, but I know it works in 1.5.2).

...I think the clean solution though, is a util / helper method as you have proposed.

**Comment by robertpanzer** [comment]
> `node.__ruby_object().getRuntime()`

This will work sometimes with AsciidoctorJ 1.5.2. 
It depends on where you get the objects from.
For example the objects returned from `AbstractBlock.blocks()` are converter to `BlockImpl` instances that also have the Ruby wrapper as `delegate`.
If you get the `document()` instead this will work.

In AsciidoctorJ 1.6.0 this will never work, because we try as hard as possible to wrap the Ruby objects ourselves. (If it works it's a bug ;-) )

I am also in favor of adding a new method `JRubyRuntimeContext.get(AbstractNode)` that returns the appropriate Ruby runtime.

**Comment by mojavelinux** [comment]
> In AsciidoctorJ 1.6.0 this will never work

I'm actually very glad to hear that. That's an indicator that the AST in AsciidoctorJ is real and not just a veneer. :+1:

**Comment by robertpanzer** [comment]
Added a public method `JRubyRuntimeContext.get(AbstractNode)` and use that also from the `Processor` base class.
