### ISSUE TITLE
Bundle rouge gem in AsciidoctorJ PDF

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctorj#368]
Bundle the rouge gem in AsciidoctorJ PDF when we relesae 1.5.0-alpha.9. The rouge gem is a new source highlighter that will come available in Asciidoctor PDF 1.5.0.alpha.9. See https://github.com/asciidoctor/asciidoctor-pdf/issues/247

**Comment by abelsromero** [comment]
I guess this could be closed, or at least add a milestone note for tracking?

**Comment by mojavelinux** [comment]
Yep!

**Comment by robertpanzer** [comment]
Fixed with 5e8c338c081306e1be009e6b8e05495dd7967368
