### ISSUE TITLE
Set the JRuby version correctly in the JRuby Gradle plugin

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctorj#369]
In order to get the JRuby Gradle plugin to use the same version of JRuby throughout, an additional property needs to be set. Currently, the build sets the `defaultVersion` property in the `jruby` stanza. It also needs to set the `execVersion`.

See https://github.com/asciidoctor/asciidoctorj/blob/master/build.gradle#L145

The build script should read as:

```
jruby {
  defaultRepositories = false
  defaultVersion = jrubyVersion
  execVersion = jrubyVersion
}
```

**Comment by robertpanzer** [comment]
Implemented as proposed. Fixed with https://github.com/asciidoctor/asciidoctorj/commit/a057b492efad6da05fd980a19227f78d2ef7ab71
