### ISSUE TITLE
PDF backend not rendering block titles for lists

### ISSUE THREAD

**Issue by k-mack** [asciidoctor/asciidoctorj#382]
Hi, 

I'm using the Gradle plugins to build my documents, and I'm having trouble getting the PDF backend to render block titles for lists and checklists. They do render for plain text. Below is the example I'm using.

= Tests

\.Test1
Test

\.Test2
\* Test

\.Test3
\- Test

\.Test4
\- [ ] Test

They render with the HTML5 backend but not with the PDF backend.

Any help would be great. Thanks.

**Comment by mojavelinux** [comment]
This is not yet implemented in Asciidoctor PDF. Currently, only paragraph titles are rendered.

Could you file this in Asciidoctor PDF? I'll schedule it for the first beta.

https://github.com/asciidoctor/asciidoctor-pdf/issues

**Comment by k-mack** [comment]
Tracking under https://github.com/asciidoctor/asciidoctor-pdf/issues/316

**Comment by mojavelinux** [comment]
:+1: Thanks!
