### ISSUE TITLE
Does return type PreprocessorReader of Preprocessor.process() make any sense?

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#383]
I am just writing about implementing a Preprocessor and I am stumbling about the return type of the `process()` method.
At the moment it is expected to return a `PreprocessorReader`.
If the method returns `null` the current implementation of Asciidoctor uses the original PreprocessorReader that was also passed to the `process()` method.
As it is at the moment "impossible" to create an own `PreprocessorReader` or `Reader` I am wondering if it makes any sense to let this method return anything.
I don't see any value in that at the moment. 

Instead at the moment a Java Preprocessor will probably get the content from the Reader, modify it, and restore the new content back into the original Reader which is then reused by the next Preprocessor or the Asciidoctor parser.

While it doesn't seem very nice to work like that, creating an own, filtering Reader seems to be much more difficult.

Wdyt? Should we 
1. try to support own Java Readers in the future and keep the return type or 
2. should we stay with the current model where returning anything else than the original Reader does not make any sense and change the return type to `void`?

**Comment by mojavelinux** [comment]
The void return type probably makes the most sense at the moment. We can then explore how to allow a new reader to be returned, but that may require testing with and possible changes to core.

**Comment by robertpanzer** [comment]
Changed return type of the process method to void in #384
