### ISSUE TITLE
DocBook backend outputs incorrect table column numbers

### ISSUE THREAD

**Issue by ndw** [asciidoctor/asciidoctorj#391]
Testing

````
|===
2+| Span
| Column | Column
| Column | Column
| Column | Column
|===
````

translates (in part) into:

````
<informaltable frame="all" rowsep="1" colsep="1">
<tgroup cols="2">
<colspec colname="col_1" colwidth="50*"/>
<colspec colname="col_1" colwidth="50*"/>
<tbody>
...
````

Note that `colname="col_1"` appears twice.

**Comment by ndw** [comment]
Actually this may be a bug in all the back ends, I saw it first in AsciiDoctorJ which I have integrated into my XML toolchain, but the ordinary `asciidoctor` command line tool exhibits the same bug.

**Comment by mojavelinux** [comment]
This is definitely an issue in Asciidoctor core. I've figured out a fix. Could you reopen in that repository?

**Comment by ndw** [comment]
Moved: asciidoctor/asciidoctor#1556 .

**Comment by mojavelinux** [comment]
Thanks Norman!
