### ISSUE TITLE
ContentNode.hasRole() always returns false if multiple roles are present on a node.

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#393]
ContentNode.hasRole() unfortunately maps to `role?` which returns true if the given string exactly matches the `role` attribute.
Instead it should map to `has_role?` which returns true if the given role is part of the attribute.

**Comment by mojavelinux** [comment]
As odd as it seems, `role?` is intended to check if the role attribute is set and optionally if the whole role value equals the value passed in. `has_role?` would definitely be the method you want to map to.

**Comment by robertpanzer** [comment]
Yes, I somehow missed this as the tests go well if there's at most one role;-)
Fixed with https://github.com/asciidoctor/asciidoctorj/commit/6b5e6ea22b7c1cc36a515d2d24f12f3fd1f47b6d
