### ISSUE TITLE
AsciidoctorJ 1.5.3 classes are compiled for Java 8

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#398]
Somehow gradle looses the information that it should compile the classes for Java 6, as specified in gradle.properties and the root build.gradle file.

Debug output shows that no target version is passed to the Java compiler, so that the classes are created for Java 8 if a JDK 8 is used.

It would be great if someone with some more gradle expertise could have a look at that, maybe @ysb33r or @melix 

I'll try to get a 1.5.3.1 published asap.

**Comment by ysb33r** [comment]
PR on the way.

**Comment by robertpanzer** [comment]
:+1: Thank you!

**Comment by ysb33r** [comment]
That should hopefully do it.
