### ISSUE TITLE
Trouble with asciidoctorj-pdf version 1.5.0-alpha.10

### ISSUE THREAD

**Issue by charleech** [asciidoctor/asciidoctorj#403]
Hi,

I've been noticed that the latest version of  `asciidoctorj-pdf:1.5.0-alpha.10` is available at the Maven Central. Thank you for your effort. It is a good works.

My project use `asciidoctor-maven-plugin:1.5.2.1`. I'm trying to update its dependency to  `asciidoctorj-pdf:1.5.0-alpha.10` and found some trouble about the `asciidoctorj-pdf:1.5.0-alpha.10`  as the following: -

1. There is no bundled `rouge` .
2. The `prawn-icon:1.0.0` does not has the `fontawesome`.

Could you please help to advise further? Thank you very much for your help in advance. I'm looking forward to hearing from you soon.

Regards,

Charlee Ch.

**Comment by mojavelinux** [comment]
It appears that we lost all the fonts from prawn-icon. I think we need a double star matcher here because the fonts are in subfolders.

```
include "gems/*/data/fonts/*"
```

Rouge is an optional dependency, so AsciidoctorJ PDF needs to declare it explicitly in build.gradle.

Robert, how would you like to proceed? Perhaps we can name the AsciidoctorJ PDF version 1.5.0.alpha.10.1?

**Comment by robertpanzer** [comment]
Darn it!
I was pretty sure that I copied the dependencies and gemFiles from the branched file. 
Apparently I did not.

**Comment by robertpanzer** [comment]
> Robert, how would you like to proceed? Perhaps we can name the AsciidoctorJ PDF version 1.5.0.alpha.10.1?

Yes, sounds good.
I just will have to give on taking the gem version from the project version and set it directly:
```
asciidoctorPdfGemVersion = project(':asciidoctorj-pdf').version.replace('-', '.')
```

**Comment by mojavelinux** [comment]
Probably just comment that out and make a note about it that it's temporary, then revert it after you publish. That way, you don't forgot to change it back.
