### ISSUE TITLE
Add integration tests for the distribution

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#405]
Apparently JRuby behaves differently when loading gems that are exploded in the file system or when they are packaged in a jar.
The current unit tests test the pdf converter and the diagram extension only with exploded gems.

Tests should be added that render a PDF and diagrams using the jars built by asciidoctorj-diagram and asciidoctorj-pdf.

**Comment by mojavelinux** [comment]
> Apparently JRuby behaves differently when loading gems that are exploded in the file system or when they are packaged in a jar.

That doesn't surprise me.

> Tests should be added that render a PDF and diagrams using the jars built by asciidoctorj-diagram and asciidoctorj-pdf.

Definitely.

**Comment by robertpanzer** [comment]
Fixed with #405
