### ISSUE TITLE
" (UnknownFont) Icon font not found for set: fa " with  asciidoctorj-pdf:1.5.0-alpha.10

### ISSUE THREAD

**Issue by Robin7Ma** [asciidoctor/asciidoctorj#406]
Hi, I used asciidoctor-maven-plugin:1.5.2 and asciidoctorj-pdf (1.5.0-alpha.9) in my maven project, and it works fine. 

But when I update asciidoctorj-pdf  version to 1.5.0-alpha.10, It happened some error, I compared the fonts and themes with them, but not found any different, How can I fix it?

There's the error output in maven :

    [ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2:process-asciidoc (generate-pdf-docs) on project kdm-rdp-rest-docs: Execution generate-pdf-docs of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2:process-asciidoc failed: (UnknownFont) Icon font not found for set: fa -> [Help 1]

My English is not good, I hope you can understand my meaning.
Thank you!

**Comment by mojavelinux** [comment]
Effectively, AsciidoctorJ 1.5.0.alpha.10 was broken. Please use 1.5.0.alpha.10.1, which addresses this issue.

**Comment by mojavelinux** [comment]
> I hope you can understand my meaning.

Perfectly!

**Comment by Robin7Ma** [comment]
Another Error:

    [ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2:process-asciidoc (generate-pdf-docs) on project kdm-rdp-rest-docs: Execution generate-pdf-docs of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2:process-asciidoc failed: (NoMethodError) undefined method `activate' for nil:NilClass -> [Help 1]

**Comment by robertpanzer** [comment]
With the latest asciidoctorj-pdf you have to make sure that you also use asciidoctorj 1.5.3.2. 
I guess that asciidoctorj-pdf wants the thread_safe 0.3.5 gem which is packaged in asciidoctorj 1.5.3.2. asciidoctorj 1.5.2 still contains thread_safe 0.3.4. 

When using the maven plugin you will probably have to wait for a new release.

**Comment by Robin7Ma** [comment]
Yes, you are right, maybe I was short-tempered : )

Thanks for your help and you've done.

**Comment by mojavelinux** [comment]
The Maven plugin should be able to work with the newer version of AsciidoctorJ and AsciidoctorJ PDF, but you do need to specify both in the dependencies section of the plugin configuration. Of course, the release of Asciidoctor Maven plugin 1.5.3 will make this automate.

**Comment by Robin7Ma** [comment]
OK, patient waiting for Asciidoctor 1.5.3.
Thanks again.

**Comment by mojavelinux** [comment]
:+1:
