### ISSUE TITLE
asciidoctorj-epub3: undefined method `activate' for nil:NilClass since 1.5.0-alpha.6

### ISSUE THREAD

**Issue by robertoschwald** [asciidoctor/asciidoctorj#415]
Updated dependency in gradle project from 1.5.0-alpha.4 to .6. Now I receive:

Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `activate' for nil:NilClass
	at RUBY.try_activate(/Users/myuser/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/1.7.21/e061b9f399a5e8d5cfcca84d4a6baf879111e83c/jruby-complete-1.7.21.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems.rb:198)
	at RUBY.require(/Users/myuser/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/1.7.21/e061b9f399a5e8d5cfcca84d4a6baf879111e83c/jruby-complete-1.7.21.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:126)

This is a Grails 3.0.10 gradle project. Switched back to 1.5.0-alpha.4 for now.

**Comment by robertpanzer** [comment]
Hi Roberto,

could you please add the full stacktrace?
With this extract I can unfortunately not see what gem is actually required.

Robert

**Comment by robertoschwald** [comment]
Here it is:

[gradle_with_epub3_alpha.6_logs.txt](https://github.com/asciidoctor/asciidoctorj/files/78722/gradle_with_epub3_alpha.6_logs.txt)


Project containing the plugin and artifacts, see: https://github.com/robertoschwald/grails-audit-logging-plugin (audit-logging/build.gradle file)

**Comment by robertpanzer** [comment]
Hmmm, not very enlightening.
But it seems a bit as if asciidoctorj 1.5.3.2 is used.
Could you also please set the version of asciidoctorj to 1.5.4?

**Comment by robertoschwald** [comment]
I'm using the gradle asciidoctor-gradle-plugin 1.5.3, which has the dependency defined:

asciidoctor
+--- org.asciidoctor:asciidoctorj:1.5.3.2
|    +--- org.jruby:jruby-complete:1.7.21
|    \--- com.beust:jcommander:1.35
\--- org.asciidoctor:asciidoctorj-groovy-dsl:1.0.0.preview2
     +--- org.codehaus.groovy:groovy-all:1.8.9
     \--- org.asciidoctor:asciidoctorj:1.5.1 -> 1.5.3.2 (*)

How can I change artifact versions of gradle buildScript dependencies to get ascidoctorj 1.5.4?

**Comment by robertpanzer** [comment]
You can find a description here: https://github.com/asciidoctor/asciidoctor-gradle-plugin#configuration

This should do the trick:

```groovy
asciidoctorj {
    version = '1.5.4'
}
```

**Comment by robertoschwald** [comment]
Added 

asciidoctorj {
  version = '1.5.4'
}

to build.gradle, same error. I'm not sure if asciidoctorj 1.5.4 is really used in this case, because info log shows:

Applying dependency management to configuration 'asciidoctor' in project 'audit-logging'
[Asciidoctor] asciidoctorj: 1.5.3.2
[Asciidoctor] asciidoctorj-groovy-dsl: 1.0.0.preview2
Configuring agent
Resolving dependency management for configuration 'agent' of project 'audit-logging'
Resolved versions: {}
...

:audit-logging:asciidoctor (Thread[main,5,main]) started.
:audit-logging:asciidoctor
Executing task ':audit-logging:asciidoctor' (up-to-date check took 0.07 secs) due to:
  Output file /eclipse-common/workspace2/grails-audit-logging-plugin/audit-logging/build/docs/index.html has changed.
  Output file /eclipse-common/workspace2/grails-audit-logging-plugin/audit-logging/build/docs/index.epub has been removed.
  Output file /eclipse-common/workspace2/grails-audit-logging-plugin/audit-logging/build/docs/index.pdf has been removed.
Resolving dependency management for configuration 'asciidoctor' of project 'audit-logging'
Resolved versions: {}
:audit-logging:asciidoctor FAILED
:audit-logging:asciidoctor (Thread[main,5,main]) completed. Took 7.948 secs.

FAILURE: Build failed with an exception.

...
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `activate' for nil:NilClass

**Comment by robertoschwald** [comment]
When switching back to         

    classpath 'org.asciidoctor:asciidoctorj-epub3:1.5.0-alpha.4'

it works again:

Resolving dependency management for configuration 'asciidoctor' of project 'audit-logging'
Resolved versions: {}
Wrote EPUB3 to /builddir/workspace2/grails-audit-logging-plugin/audit-logging/build/docs/index.epub
:audit-logging:asciidoctor (Thread[main,5,main]) completed. Took 16.901 secs.

**Comment by robertpanzer** [comment]
It would be great if you could try to manually convert your document using `asciidoctorj -b epub3 my.adoc` after downloading the distribution from http://search.maven.org/remotecontent?filepath=org/asciidoctor/asciidoctorj/1.5.4/asciidoctorj-1.5.4-bin.zip

This would help to see if we have a regression in asciidoctorj or if there is a problem in the combination with the gradle plugin.

**Comment by robertoschwald** [comment]
I will do that. Here is the internal call to asciidoctor with gradle using alpha.4. 
Maybe that sheds some light into it:

[DEBUG] [org.asciidoctor.internal.JRubyAsciidoctor] asciidoctor -B /builddir/grails-audit-logging-plugin/audit-logging/src/docs -S UNSAFE -b epub3 -a source-highlighter=coderay -a experimental=true -a icons=font -a setanchors=true -a idprefix -a idseparator=- -a toc2 -a numbered -a revnumber=2.0.1-SNAPSHOT -a revdate=2016-01-05 -a projectdir=../.. -a rootdir=../../.. -a project-name=audit-logging -a project-group=org.grails.plugins -a project-version=2.0.1-SNAPSHOT /builddir/grails-audit-logging-plugin/audit-logging/src/docs/index.adoc

**Comment by robertoschwald** [comment]
With asciidoctorj 1.5.4 standalone, it works:

$ asciidoctorj -v -B /builddir/grails-audit-logging-plugin/audit-logging/src/docs -S UNSAFE -b epub3 -a source-highlighter=coderay -a experimental=true -a icons=font -a setanchors=true -a idprefix -a idseparator=- -a toc2 -a numbered -a revnumber=2.0.1-SNAPSHOT -a revdate=2016-01-05 -a projectdir=../.. -a rootdir=../../.. -a project-name=audit-logging -a project-group=org.grails.plugins -a project-version=2.0.1-SNAPSHOT /builddir/grails-audit-logging-plugin/audit-logging/src/docs/index.adoc

/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:33 warning: `&' interpreted as argument prefix
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:40 warning: `&' interpreted as argument prefix
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/builder.rb:185 warning: `&' interpreted as argument prefix
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/package.rb:158 warning: instance variable @ordered not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/spine.rb:50 warning: instance variable @rendition_specified not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/spine.rb:50 warning: instance variable @rendition_specified not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/spine.rb:50 warning: instance variable @rendition_specified not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/spine.rb:50 warning: instance variable @rendition_specified not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/spine.rb:50 warning: instance variable @rendition_specified not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/spine.rb:50 warning: instance variable @rendition_specified not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/spine.rb:50 warning: instance variable @rendition_specified not initialized
/usr/local/asciidoctorj-1.5.4/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar!/gems/gepub-0.6.9.2/lib/gepub/metadata.rb:90 warning: instance variable @xml not initialized
Wrote EPUB3 to /builddir/grails-audit-logging-plugin/audit-logging/src/docs/index.epub
Time to read and parse source:  null
Time to render document:  null
Total time to read, parse and render:  null

**Comment by robertpanzer** [comment]
Awesome!

A last possibility that I could imagine would be to configure the asciidoctorj version like a dependency on an extension, i.e.:

```groovy
dependencies {
    asciidoctor 'org.asciidoctor:asciidoctorj:1.5.4'
}
```

If that doesn't as well we should try to get help from the folks of the gradle plugin.

**Comment by robertoschwald** [comment]
Added explicit dependency and to buildscript dependencies as classpath dependency. It seems it gets resolved to 1.5.4 then, but the error is the same:

Tasks to be executed: [task ':audit-logging:asciidoctor', task ':audit-logging:docs']
:audit-logging:asciidoctor (Thread[main,5,main]) started.
:audit-logging:asciidoctor
Executing task ':audit-logging:asciidoctor' (up-to-date check took 0.042 secs) due to:
  Output file /builddir/grails-audit-logging-plugin/audit-logging/build/docs/index.html has changed.
  Output file /builddir/grails-audit-logging-plugin/audit-logging/build/docs/index.epub has been removed.
  Output file /builddir/grails-audit-logging-plugin/audit-logging/build/docs/index.pdf has been removed.
Resolving dependency management for configuration 'asciidoctor' of project 'audit-logging'
Resolved versions: {org.asciidoctor:asciidoctorj=1.5.4}
Using version '1.5.4' for dependency 'org.asciidoctor:asciidoctorj:1.5.4'
Using version '1.5.4' for dependency 'org.asciidoctor:asciidoctorj:1.5.1'
:audit-logging:asciidoctor FAILED
:audit-logging:asciidoctor (Thread[main,5,main]) completed. Took 6.371 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':audit-logging:asciidoctor'.
> Error running Asciidoctor

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':audit-logging:asciidoctor'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
...
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `activate' for nil:NilClass

**Comment by robertpanzer** [comment]
OK, that leaves me a bit clueless.
Maybe @ysb33r or @aalmiray has an idea?

**Comment by ancho** [comment]
@robertoschwald 

Change the version of asciidoctorj-pdf to 1.5.0-alpha.11 and asciidoctorj-epub3 to 1.5.0-alpha.6

Add the following to your build.gradle file:

```
asciidoctorj {
   version = '1.5.4'
}
```

Works for me.

```
./gradlew clean docs
:audit-logging:clean
:audit-logging:asciidoctor
:audit-logging:docs

BUILD SUCCESSFUL

Total time: 20.291 secs

tree build
build
└── docs
    ├── audit-logging-2.0.1-SNAPSHOT.epub
    ├── audit-logging-2.0.1-SNAPSHOT.pdf
    ├── ghpages.html
    ├── index.html
    └── templates

2 directories, 4 files

**Comment by robertoschwald** [comment]
thanks! great.

**Comment by ysb33r** [comment]
Glad that worked now. The trick is to look at dependencies as you did the first time (but probably not the second time). By putting the epub, pdf etc dependencies on `buildscript.dependencies.classpath` we create a bit of a problem in that they might resolve to an older version, which then messes up the location of the correct `asciidoctorj` jar.

i need to test this, but I think the better solution for the future is to put the extra jars on the `project.dependencies.asciidoctor` configuration. (If this does not work we should fix it).

**Comment by robertpanzer** [comment]
Thanks for the great help, @ancho & @ysb33r !!!
