### ISSUE TITLE
rouge syntax highlighting for HTML

### ISSUE THREAD

**Issue by kastork** [asciidoctor/asciidoctorj#429]
The syntax highlighter, rouge is included in asciidoctor-pdf.  It solves the problem of getting line numbers in code listings when rendering pdf.

But if you also render html5, the code listing is not styled.

I've tried putting the options in both the document header and in the attributes of the asciidoctor block of the gradle build file, but nothing seems to get the styling put into the html.

Any suggestions?

**Comment by mojavelinux** [comment]
Rouge is currently only supported in Asciidoctor PDF. We added it as a prototype to see how it goes. I'm happy to say it has performed well. And with GitHub now using it by default in GitHub Pages, there's even more reason to go all in on it.

To get it into the html5 converter in AsciidoctorJ, we first need to integrate it in core. See https://github.com/asciidoctor/asciidoctor/issues/1040. I'm happy to make that part of the next release.

**Comment by mojavelinux** [comment]
FYI, rouge is now supported in the HTML5 converter starting in Asciidoctor 2.

**Comment by robertpanzer** [comment]
Rouge is also part of Asciidoctorj since 2.0.0
