### ISSUE TITLE
Support to unset attributes in AttributesBuilder

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#430]
AttributesBuilder has the `arguments` [method](https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-core/src/main/java/org/asciidoctor/AttributesBuilder.java#L578) that allows to pass a chain of command line attributes.
It allows to update attributes that have been set previously. But when you want to unset an attribute it just adds a new entry in the internal map instead of updating the current one. 
Even if Asciidoctor (Ruby core) deals with it properly, I think it should be better to remove the attribute and add the new unset one.

As example, the next code
```
AttributesBuilder builder = AttributesBuilder.attributes()
builder.arguments("stylesheet=my-theme.css toc").print()
builder.arguments("stylesheet=my-theme2.css toc=left").print()
builder.arguments("data-uri mysample.adoc").print()
builder.arguments("stylesheet!").print()
builder.unsetStyleSheet().print()
```
generates the following map of attributes, you can see that stylesheet appears twice.
```
stylesheet -> my-theme2.css
stylesheet! -> ""
mysample.adoc -> ""
data-uri -> ""
toc -> left
```

**Comment by robertpanzer** [comment]
If I see it correctly `Asciidoctor::Cli::Options` also simply puts the attributes into a hash without checking if the negated attribute is already set (or the other way around): https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/cli/options.rb#L80-L89

For well-defined attributes Core coalesces them, see https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/document.rb#L214-L223 and following.

I think the trick that this works is that in Ruby a Hash preserves the insertion order when iterating over the elements.

This certainly gets lost when passing a `java.util.HashMap` from Java.

What do you think about not processing the entries in the attribute builder but also trying to preserve the order by using a `java.util.LinkedHashMap`? 
Because the `!`-semantics only seem to apply for a list of defined attributes.

At least for me this test succeeds. (Sorry for adding this here but I don't have access to gist where I am atm)

```groovy
package org.asciidoctor

import org.jruby.Ruby
import org.jruby.javasupport.JavaEmbedUtils
import org.jruby.runtime.builtin.IRubyObject
import spock.lang.Specification

public class WhenAMapIsPassedToRuby extends Specification {

    public static interface TestIntf {
        public String process(Map<String, Object> m);
    }

    def 'when a HashMap is passed the order is not preserved in Ruby'() {
        given: 'A HashMap'
        Map<String, Object> map = prepare(new HashMap<>())
        when: 'it is processed in Ruby'
        String result = rubyProcessor.process(map)
        then: 'the order is not preserved'
        result != 'EFCDAB'
    }

    def 'when a LinkedHashMap is passed the order is preserved in Ruby'() {
        given: 'A LinkedHashMap'
        Map<String, Object> map = prepare(new LinkedHashMap<String, Object>())
        when: 'it is processed by Ruby'
        String result = rubyProcessor.process(map)
        then: 'the order is preserved'
        result == 'EFCDAB'
    }

    TestIntf getRubyProcessor() {
        Ruby ruby = Ruby.newInstance();
        IRubyObject rubyObject = ruby.evalScriptlet('''
            class TestIntf
                def process m
                    ret = ''
                    m.each do |key, value|
                        ret << key << value
                    end
                    ret
                end
            end
            TestIntf.new
            ''')
        JavaEmbedUtils.rubyToJava(ruby, rubyObject, TestIntf)
    }

    Map<String, Object> prepare(Map<String, Object> map) {
        map.put('E', 'F')
        map.put('C', 'D')
        map.put('A', 'B')
        map
    }
}
```

**Comment by abelsromero** [comment]
I really don't have a strong opinion on this since it obviously works, and it's not likely to happen that someone reuses an AttributesBuilder instance.
But here I see an opportunity to improve the Java API independently from the ruby implementation. 
Also for me there’s a wording issue. According to the user manual the `!` is used to `unset` an attribute, and the Java API provides a way to unset attributes. So I would expect the same behauvior from the method and the `!` notation. However, doing `arguments("stylesheet!")` and `unsetStyleSheet()` does not have the same effect since the second removes the value from the map.

In the end, as I say "no strong opinion" and you lead here, so I'd accept any proposal for you :smile:

**Comment by robertpanzer** [comment]
Hmmm... `unsetStylesheet()` should already add the `stylesheet!` argument: https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-core/src/main/java/org/asciidoctor/Attributes.java#L401-L403

And in fact this passes:
```java
Attributes attributes = attributes().unsetStyleSheet().get();
assertThat(attributes.map().containsKey("stylesheet!"), is(true));
```

But now I found the place where Asciidoctor removes an attribute if the `!` version is set: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/document.rb#L361 :

```ruby
    attr_overrides.delete_if do |key, val|
      verdict = false
      # a nil value undefines the attribute
      if val.nil?
        attrs.delete(key)
      else
```

The more I think about it, the more I come to the conclusion that we need to switch to a `LinkedHashMap`.

I just hacked this example that reveals the current strange behavior:
```java
    @Test
    public void attributes_and_unsetting_attributes_are_applied_in_order()
        throws IOException {

        Attributes attributes = AttributesBuilder.attributes()
            .attribute("b!", null)
            .attribute("b", "B")
            .get();

        Options options = options().attributes(attributes).get();

        org.asciidoctor.ast.Document doc = asciidoctor.loadFile(classpath.getResource("rendersample.asciidoc"), options.map());

        assertThat(doc.getAttr("b"), is((Object) "B"));
    }
```

This test currently fails!
But it succeeds when `Attributes` uses a `LinkedHashMap`.

(Note that it depends on the concrete implementation of the `HashMap`. I tested with Java 1.8.0_51 on Windows. Other versions might behave differently and the test succeeds with a HashMap in the same env when using the attributes `a` and `a!`...

Nevertheless we can also additionally remove the `stylesheet` attribute in `unsetStylesheet()`.

**Comment by abelsromero** [comment]
Now I see my error, my test was hasty and I jumped to conclusions.
LinkedHashMap is definetly the way to go: just respect what Ruby does with maps and let asciidocotor do the work.
I run an extra test, and LinkedHashMap even respects the key insertion order when puting a value more than once with the same key.
**Case closed!**

**Comment by robertpanzer** [comment]
You didn't make an error, you helped discover an issue!
Thank you!!!

**Comment by mojavelinux** [comment]
> LinkedHashMap is definetly the way to go: just respect what Ruby does with maps and let asciidocotor do the work.

Exactly. You both got right to the issue.

I haven't been very comfortable relying on this behavior, which is one of the reasons why I proposed a proper abstract/type over the attribute registry in the future. See https://github.com/asciidoctor/asciidoctor/issues/692.

**Comment by mojavelinux** [comment]
:+1:
