### ISSUE TITLE
AsciidoctorJ should provide a public API for requiring paths in the Ruby runtime

### ISSUE THREAD

**Issue by aalmiray** [asciidoctor/asciidoctorj#432]
Seen in the `AsccidoctorTask` found in the `asciidoctor-gradle-plugin`

    if (requires) {
        for (require in requires) {
            // FIXME AsciidoctorJ should provide a public API for requiring paths in the Ruby runtime
            asciidoctor.delegate.rubyRuntime.evalScriptlet(
                'require \'' + require.replaceAll('[^A-Za-z0-9/\\\\.\\-_]', '') + '\'')
        }
    }

**Comment by aalmiray** [comment]
Please note that `JRubyAsciidoctor` has a protected filed of type `JRubyTime` and it's not exposed to the outside world. The only way to define required gems is through reflection. This feature is needed to:
 - simplify `asciidoctor-gradle-plugin`
 - finish enabling `gemPath` support in jbake (see https://github.com/jbake-org/jbake/issues/267)

**Comment by mojavelinux** [comment]
Absolutely. And, in fact, such an API is definitely included in Asciidoctor 1.6.0 and already backported to 1.5.4. See https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-core/src/main/java/org/asciidoctor/Asciidoctor.java#L605-L617

**Comment by aalmiray** [comment]
great! Perhaps we can make something happen at Javaland's Hackergarten :smirk:

**Comment by aalmiray** [comment]
@mojavelinux what's the release plan for 1.6.0?

**Comment by robertpanzer** [comment]
With all the required code already available I think we can close this issue for AsciidoctorJ, right?

Would be great to fix this in JavaLand! :beers:

**Comment by aalmiray** [comment]
definitely!

**Comment by mojavelinux** [comment]
@aalmiray 1.6.0 is still a ways off. We'll probably see a 1.5.5 release next, but I'm going to really try to make that the last 1.5.x release before we switch master over to 1.6.0. Having said that, we can continue putting out 1.6.0 pre-releases in the meantime.

**Comment by mojavelinux** [comment]
:+1:
