### ISSUE TITLE
Conversion option template_dirs

### ISSUE THREAD

**Issue by jueadams** [asciidoctor/asciidoctorj#436]
Hi there,

I tried using the option **template_dirs** by specifying the directory as a path (string) for a slim template with no success. I got:

```
Exception in thread "main" org.jruby.exceptions.RaiseException: (NoMethodError) asciidoctor: FAILED: C:/axb/_docs/test_guide.adoc: Failed to parse source, undefined method `each' for "C:\\axb\\_docs\\backends\\slim\\docbook45":String
	at RUBY.load(C:/MultiPlatform/ruby/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1362)
	at RUBY.convert(C:/MultiPlatform/ruby/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1458)
	at RUBY.convert_file(C:/MultiPlatform/ruby/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1562)
	at RUBY.convertFile(<script>:68)
	at org.jruby.gen.InterfaceImpl579737299.convertFile(org/jruby/gen/InterfaceImpl579737299.gen:13)
```

From the error (undefined method `each')  it seems a list is expected rather than a directory. I've tried both:

```
	if (cmd.hasOption("T")) {
		String d = cmd.getOptionValue("T");
		File b = new File( d );
		File[] list = b.listFiles();
		options.put("template_dirs", d );
	}

	// Run the conversion
	if (cmd.hasOption("f")) {
	String f = cmd.getOptionValue("f");
	
    String html = asciidoctor.convertFile(
        	new File( f ),
            options
        );
    System.out.println(html);
   }

```

If the data is given as a list (the content of the directory/files) it fails that way:

```
Exception in thread "main" org.jruby.exceptions.RaiseException: (NoMethodError) asciidoctor: FAILED: C:/axb/_docs/test_guide.adoc: Failed to parse source, undefined method `nil_or_empty?' for #<Java::JavaIo::File:0x7ff19c33>
	at RUBY.load(C:/MultiPlatform/ruby/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1362)
	at RUBY.convert(C:/MultiPlatform/ruby/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1458)
	at RUBY.convert_file(C:/MultiPlatform/ruby/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1562)
	at RUBY.convertFile(<script>:68)
	at org.jruby.gen.InterfaceImpl579737299.convertFile(org/jruby/gen/InterfaceImpl579737299.gen:13)
```

What data type is the option **template_dirs**? Do I wrong or is this a bug in the current version?

Many thanks for any help in advance

**Comment by abelsromero** [comment]
I think the issue is because the option should be set as a List<String> instead of File.

Seeing the example code seems you are directly building the options map. Truth be told, building options is not easy unless you have a clear idea of what happens under-the-hood.
To avoid problems, I strongly recommend using the [OptionsBuilder](https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-core/src/main/java/org/asciidoctor/OptionsBuilder.java). It offers many methods that take care of conversions. In your case, you could do something like this:
```
OptionsBuilder options = OptionsBuilder.options();

if (cmd.hasOption("T")) {
    String d = cmd.getOptionValue("T");
    options.templateDir(new File( d ));
}

. . .

String html = asciidoctor.convertFile(
            new File( f ),
            options
        );
```

Also, have a look at the [AttributesBuilder](https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-core/src/main/java/org/asciidoctor/AttributesBuilder.java).

**Comment by jueadams** [comment]
Hi Abel Salgado,

thanks a lot for your (very fast) response, You saved my (first) day (diving into AsciidoctorJ).

Yes, you're right. It works as you recommended. I'll always use the  **attributes and options builder classes** to prevent such pitfalls.

Thanks a lot.

**Comment by abelsromero** [comment]
Glad it was helpfull.

You'll be interesting in checking the [Integrator's guide](https://github.com/asciidoctor/asciidoctorj/blob/asciidoctorj-1.6.0/docs/integrator-guide.adoc) that @robertpanzer has prepared for version 1.6.0.
It's a WIP thing and there some differences with the current version (1.5.4), for instance the extension API has been greatly improved, but nevertheless I think it's a great introduction to the API. Also, let us know if you think that anything can be improved.

**Comment by jueadams** [comment]
Hi Abel Salgado,

thanks a lot, again. I read the Integrator's Guide (and the documents referenced from this Guide). I'm really impressed what is possible going from Ruby to JRuby to make the code available on a JVM.

I'm working on a smaller project that uses Asciidoc as an abstraction layer for creating several type of reports  - rendered in the very end to HTML or PDF. I was seeking for a replacement of the Python implementation of the Asciidoc processor Asciidoc (issued by Stuart Rackham) and came accross Asciidoctor ...

Asciidoc is a very interesting piece of software but the regex approach for building the parser blocks is not that easy to understand (and not well documented). I managed to create a backend for my needs (based on Bootstrap) but it took some days of re-engineering to understand how its works. It is possible to cross-compile the python code to have a standalone solution w/o the need of a Python runtime but this changes the behavoiur (the run-time environment) of Asciidoc in some way.

The **Asciidoctor way** seems to me the better solution. Techniclly from the (more modern/flexible) code base prospective **and** the possibilities to use the same code for JAVA and JavaScript. The template approch using standard tools  (I'm intended to use HAML) makes it much more easier - **and faster/more stable** - to create a backend/template for Asciidoctor if needed.

Yes, I'll definitively put some comments on your project. As always things can be improved, I'll give my 50 Cent on it. My project is focussing more on how  Asciidoctor can be used as a product rather than to integrate Asciidoctor as an API in customized code. But anyway, some documentation, that I need to write, may helpful for other people if they dive into Asciidoctor the first day/s. And it might be an real world example using Asciidoc/Asciidoctor to see what is ePublishing/eDocument Factory all about.

It will took some more days to port the Bootstrap backend from Asciidoc to Asciidoctor (and a bunch of other helpful code/JavaScripts) but I think around Easter a first version can be presented. What do you think  would be the best place (in Asciidoctor's envrionment) to present such a project/use case?

**Comment by mojavelinux** [comment]
> some documentation, that I need to write, may helpful for other people if they dive into Asciidoctor the first day/s.

We are always looking for more documentation, so this would be a very welcomed contribution in whatever form you are willing to share it.
