### ISSUE TITLE
Register a Treeprocessor with Class argument

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctorj#443]
When I register a Treeprocessor with a Class argument, JRuby raises an exception:
```
Exception in thread "main" org.jruby.exceptions.RaiseException: (NameError) undefined local variable or method `fr' for main:Object
	at RUBY.(root)(<script>:1)
```

Given the following code:
```java
package fr.edf.distribution.automation.asciidoctor.extension;

import java.util.List;
import java.util.Map;

import org.asciidoctor.ast.AbstractBlock;
import org.asciidoctor.ast.Block;
import org.asciidoctor.ast.Document;
import org.asciidoctor.extension.Preprocessor;
import org.asciidoctor.extension.PreprocessorReader;
import org.asciidoctor.extension.Treeprocessor;

public class LunrTreeprocessor extends Treeprocessor {
  // ...
}
```
```java
public class LunrExtension implements ExtensionRegistry {

	public void register(Asciidoctor asciidoctor) {
		JavaExtensionRegistry javaExtensionRegistry = asciidoctor.javaExtensionRegistry();
		javaExtensionRegistry.treeprocessor(LunrTreeprocessor.class);
	}
}
```

If I register `LunrTreeprocessor` with `javaExtensionRegistry.treeprocessor("fr.edf.distribution.automation.asciidoctor.extension.LunrTreeprocessor");` or `javaExtensionRegistry.treeprocessor(new LunrTreeprocessor());` this is working fine.

I'm using AsciidoctorJ 1.5.4

**Comment by mojavelinux** [comment]
This is the 'ol JRuby only understands certain package prefix problem.

> JRuby recognizes the top-level Java packages java, javax, javafx, org, and com. You can also type in a fully qualified class name basically as in Java, for example, java.lang.System or org.abc.def.className ..."

See http://stackoverflow.com/questions/32423423/importing-jar-file-in-ruby-how-to-use-the-class

**Comment by robertpanzer** [comment]
That's a bingo! :-)

We already had a similar issue in the past and all extension registration methods were fixed, except for... exactly this one.

**Comment by robertpanzer** [comment]
BTW 1.6.0 should not be affected because the handling of extensions is completely different there: The actual processor implementation is never directly passed to JRuby, but generated Ruby proxies instead.

**Comment by mojavelinux** [comment]
:+1:

**Comment by Mogztter** [comment]
Perfect thanks!
