### ISSUE TITLE
Getting Started with AsciidoctorJ on asciidoctor.org still references 1.5.2 version

### ISSUE THREAD

**Issue by ygra** [asciidoctor/asciidoctorj#445]
Cf. [here](http://asciidoctor.org/docs/asciidoctorj/#distribution). People blindly copy/pasting the Maven XML would then get an outdated version.

**Comment by LightGuard** [comment]
Thanks for catching this! It's easy for things to get out of sync. Would
you like to help us out and submit a patch for this issue?

On Tuesday, April 12, 2016, ygra <notifications@github.com> wrote:

> Cf. here <http://asciidoctor.org/docs/asciidoctorj/#distribution>. People
> blindly copy/pasting the Maven XML would then get an outdated version.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctorj/issues/445>
>


-- 
Sent from Gmail Mobile

**Comment by mojavelinux** [comment]
I went ahead and merged the patch. The next move is to use a remote include pointing to the tag instead of copy-paste. We've already done that with a few READMEs already.

**Comment by ygra** [comment]
@mojavelinux thanks for that. I thought there should be a way of referencing the README from this project instead to keep it up to date, but I couldn't figure it out, so I just merged the changes over.

**Comment by mojavelinux** [comment]
Here's an example: https://github.com/asciidoctor/asciidoctor.org/blame/master/man/asciidoctor.adoc

The extra attributes are required to workaround a shortcoming in Awestruct at the moment. Normally, it should just be a single line.

**Comment by mojavelinux** [comment]
We're not switching over to includes just yet while we sort out these bugs. But it's coming.
