### ISSUE TITLE
Update asciidoctorj-diagram to use asciidoctor-diagram 1.4.0

### ISSUE THREAD

**Issue by hughwphamill** [asciidoctor/asciidoctorj#462]
Getting the following exception in 1.3.1

`asciidoctor-diagram: ERROR: Failed to generate image: PlantUML image generation failed: Bad Request java.io.IOException: Could not find GraphViz 'dot' tool`

In the standard example project https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-diagram-example

Even though this project makes the following statment

> Asciidoctor Diagram bundles both the ditaa and PlantUML libraries and will use them to generate diagrams.

There seems to have been an issue addressed in 1.4.0 of asciidoctor-diagram for this problem

https://github.com/asciidoctor/asciidoctor-diagram/issues/71

But this is not included in 1.3.1 (latest) of asciidoctorj-diagram

**Comment by robertpanzer** [comment]
Hi Hugh,

good point, we will surely also upgrade and release asciidoctorj-diagram with the next release of asciidoctorJ.
Nevertheless there are certain diagram types that require graphviz to be installed, so the new version will probably try not to locate graphviz over-eagerly, but depending on the type of diagram you will still need to install it.

Cheers
Robert

**Comment by hughwphamill** [comment]
Thanks Robert, 

It might be worth updating the example doc to be a bit clearer on that at the same time. 

Any idea of the time frame? 

Thanks for a fantastic project! 

Regards, 
Hugh

**Comment by weissreto** [comment]
Hi 
I also suffering from the same issue. Please release as soon as possible.

**Comment by robertpanzer** [comment]
Released asciidoctorj-diagram 1.5.0

**Comment by mojavelinux** [comment]
:+1:

**Comment by hughwphamill** [comment]
:+1:
