### ISSUE TITLE
checkVersion Task fails for 4-digit version numbers

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#479]
When trying to build a release with a 4-digit version number like 1.5.4.1 the check version task fails with an exception:
```
* Where:
Script '/Users/robertpanzer/dev/asciidoctorj/gradle/versioncheck.gradle' line: 40

* What went wrong:
Execution failed for task ':asciidoctorj:checkVersion'.
> com.github.zafarkhaja.semver.UnexpectedCharacterException (no error message)
```

**Comment by ancho** [comment]
The java-semver library throws an exception if a version does not match the criteria of a semantic version. A 4 digit number is not valid. I actually don't know how maven handles this situation internally.
But it really doesn't matter in this situation.
I'll catch the exception and log a warning. PR follows...

**Comment by robertpanzer** [comment]
👍 For now I simply skipped the task.

**Comment by ancho** [comment]
Hmm...maybe the tasks should be more isolated. At present the check task depends on checkVersion.
If something goes wrong in case of an exception the whole build will fail.
The tasks should be a helper not a blocker. I suggest to remove the task dependency.
