### ISSUE TITLE
Publish AsciidoctorJ on sdkman

### ISSUE THREAD

**Issue by hho** [asciidoctor/asciidoctorj#495]
[SDKMAN!](http://sdkman.io) is an awesome way to install and manage JVM-based command line tools.
AsciidoctorJ is available on there, but only in version 1.5.2, which is almost 2 years old.

Please consider publishing new releases there, too. It enables people to install AsciidoctorJ simply with `sdk install asciidoctorj`.

They offer a [vendor API](http://sdkman.io/vendors.html), so you can easily automate the release of new versions, and they even have a Gradle plugin doing the job which you could integrate in your build.

**Comment by marc0der** [comment]
I would love to help getting your team set up to publish new releases. Like @hho said, it's very easy to get you up and running and we have a gradle plugin that makes it even simpler to integrate.

**Comment by ancho** [comment]
:+1:

**Comment by robertpanzer** [comment]
Would be great to get a PR for that! :+1:

**Comment by marc0der** [comment]
It's very simple to do, as documented on our site. We usually leave it up to vendors to do it themselves as they need to integrate this with their own build pipeline.

Also, I'll need to set you up with a key token pair to make the api calls.

**Comment by ancho** [comment]
I can setup the configuration in the afternoon if you want. In case nobody else screams for it....  :stuck_out_tongue:

**Comment by robertpanzer** [comment]
:+1: Awesome!

**Comment by ancho** [comment]
So, all you need to do is to figure out who has the valid key/token pair. Or maybe better get a new one from @marc0der 
The credentials will be read from your local gradle.properties file, analogous to bintray credentials.

**Comment by marc0der** [comment]
I haven't ever generated any for the AsciidoctorJ project, so whoever is going to own this should probably contact me by email. We could exchange by PGP or Keybase if you already have an account.

**Comment by hho** [comment]
This seems to have been resolved by #496 – asciidoctorj 1.5.4.1 is now on sdkman.

Huge thanks to everyone involved!
