### ISSUE TITLE
renderFile() does not close AsciiDoc source file

### ISSUE THREAD

**Issue by nerk** [asciidoctor/asciidoctorj#524]
From a Swing GUI application, I invoke something like

```
Asciidoctor.Factory.create().renderFile(new File("c:/tmp/test.ad"), new Options());
```

As long as the application is open, "c:/tmp/test.ad" cannot be deleted because Asciidoctor does not properly close the file. I am using AsciidoctorJ 1.5.4.1 with  JRuby 1.7.25.

**Comment by robertpanzer** [comment]
Interesting!

AsciidoctorJ itself does not open the file but pass the abolute file name to Asciidoctor, which then consumes the file.
@mojavelinux Can you say sth to this issue?

Alternatively you could call `Asciidoctor.render(Reader, Writer, Map<String,String>)`.
With this method the reader will be consumed in Java.
The method does not close the reader, but you have it in your hands to do it yourself.

**Comment by nerk** [comment]
Yes. As a workaround I currently read the whole file into a string and invoke convert().

**Comment by mojavelinux** [comment]
I didn't realize `::File.new` creates an *open* file object in Ruby (unlike Java where it's just a model object). That means we need to call `.close` on it if we instantiate it.

Can you file an issue in Asciidoctor core?

**Comment by mojavelinux** [comment]
(Btw, you should be using convertFile, not renderFile).

**Comment by nerk** [comment]
@mojavelinux Thanks! Issue filed in Asciidoctor core:

https://github.com/asciidoctor/asciidoctor/issues/1897

**Comment by mojavelinux** [comment]
Thanks!
