### ISSUE TITLE
Distribution scripts contain an unused entry in classpath

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#530]
Current scripts generated with `application` plugin include a reference to the self distribution project in the first entry of the CLASSPATH variable.

```
CLASSPATH=$APP_HOME/lib/asciidoctorj-1.5.5-SNAPSHOT-bin.jar:$APP_HOME/lib/asciidoctorj-1.5.5-SNAPSHOT.jar:$APP_HOME/lib/asciidoctorj-diagram-1.5.1.jar:$APP_HOME/lib/asciidoctorj-epub3-1.5.0-alpha.6.jar:$APP_HOME/lib/asciidoctorj-pdf-1.5.0-alpha.11.jar:$APP_HOME/lib/jruby-complete-1.7.25.jar:$APP_HOME/lib/jcommander-1.35.jar
```

This is a side effect of doing the `application` plugin configuration in a separated project (which I think is the right approach) and does not affect the distribution from working at all.
Even when this is a silly minor inconsistency, it is easy to fix, just adding `classpath = configurations.getByName('compile').asFileTree` to `startScripts` does the trick.

**Comment by mojavelinux** [comment]
:+1:
