### ISSUE TITLE
asciidoctorj master doesn't build any longer

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#533]
It seems like asciidoctorj-pdf transitively depends on addressable without any version restrictions.
As the latest version seems to depend on Ruby 2 and we're using JRuby 1.7.25 which is not fully compatible with Ruby 2, the build currently crashes with this error:
```
:asciidoctorj-pdf:jrubyPrepareGems
ERROR:  Error installing /Users/robertpanzer/.gradle/caches/modules-2/files-2.1/rubygems/addressable/2.5.0/242707eb62374fa2d0e0c7899fe5dc0921528f90/addressable-2.5.0.gem:
        addressable requires Ruby version >= 2.0.
ERROR:  Error installing /Users/robertpanzer/.gradle/caches/modules-2/files-2.1/rubygems/public_suffix/2.0.4/7dda2cf2963589eb9bdcf01959def289b10262f2/public_suffix-2.0.4.gem:
        public_suffix requires Ruby version >= 2.0.
:asciidoctorj-pdf:jrubyPrepareGems FAILED
```

**Comment by abelsromero** [comment]
I think this supports the idea of splitting `asciidoctorj-pdf` on it's own project with different publication version and dependencies so that Asciidoctorj 1.5.5 does not include it.

_Btw, jRuby 1.7.26 is available, does it make sense to upgrade Asciidoctorj?_

**Comment by robertpanzer** [comment]
> Btw, jRuby 1.7.26 is available, does it make sense to upgrade Asciidoctorj?

I will provide a PR shortly that upgrades the version of JRuby.
