### ISSUE TITLE
images with closing tags

### ISSUE THREAD

**Issue by misfir3** [asciidoctor/asciidoctorj#538]
We are using asciidoctorj with thymeleaf and when we attempt to use images in asciidoc, thymeleaf throws template exceptions due to image tags with no end-tag. is there an option/config to do this or can it be added to close such elements ... (e.g.)
`<img src="foo.png" />`
?

**Comment by mojavelinux** [comment]
You just need to set the backend to xhtml instead of html and Asciidoctor will produce XHTML-compliant output.

This is covered in the [XHTML section](http://asciidoctor.org/docs/user-manual/#xhtml) of the user manual.
