### ISSUE TITLE
linkcss attribute value is ignored

### ISSUE THREAD

**Issue by coy123** [asciidoctor/asciidoctorj#543]
Setting the linkcss attribute using `attributes.setLinkCss(false);` makes no difference. asciidoctor.css is linked instead of embedded. This seems to be the same issue as [this asciidoctor-maven-plugin
 issue](https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/93).

**Comment by coy123** [comment]
I achieved inline css using `options.setSafe(SafeMode.SAFE);` without setting the linkcss attribute. I don't suppose this is the way it was intended.

**Comment by mojavelinux** [comment]
You are correct. When using the API, you must set the safe mode flag (typically to SAFE) to get certain features, one of which is linkcss behavior. See http://asciidoctor.org/docs/user-manual/#running-asciidoctor-securely

**Comment by coy123** [comment]
Is this by design? I get that the safe mode should not have access to files but that shouldn't restrict unsafe mode from having inline styles. As I was reading the documentation, I figured that I could use linkcss attribute to have inline style. I didn't really bother to read the secure part, because it wasn't intuitive and said nowhere in the description of linkcss. If this is the design, it should at least be declared that linkcss attribute can only be set false in safe mode.

**Comment by mojavelinux** [comment]
Yes, it is by design to have the default safe mode set to SECURE (the highest). If you set the safe mode to SAFE, then you can control whether to link or embed the CSS.

**Comment by mojavelinux** [comment]
>  it should at least be declared that linkcss attribute can only be set false in safe mode.

This is documented. If you would like it to be documented more clearly, feel free to propose an edit.
