### ISSUE TITLE
Path substitutions in diagram block macro

### ISSUE THREAD

**Issue by jvmlet** [asciidoctor/asciidoctorj#544]
Hello
I'm getting the below error :
````
asciidoctor-diagram: ERROR: Failed to generate image: No such file or directory - D:/DHP/asp_core/pipeline/pipeline-initializer/src/docs/asciidoc/{dotdir}/graph.dot
````
when I generate the `svg` using  `graphviz` macro block:
````
graphviz::{dotdir}/graph.dot[format="svg", align="center",opts="inline"]
````

This [issue ](https://github.com/asciidoctor/asciidoctor-diagram/issues/133) was fixed in `asciidoctor-diagram:1.5.4`

My gradle script looks like this :

````
buildscript {
    repositories {
        mavenCentral()
        maven {            url "https://plugins.gradle.org/m2/"        }

    }
    dependencies {
       classpath "org.asciidoctor:asciidoctor-gradle-plugin:1.5.3"
        classpath 'org.asciidoctor:asciidoctorj-diagram:1.5.0'
    }
}
apply plugin: "org.asciidoctor.convert"
    asciidoctorj {
        version = '1.5.4'
    }
    asciidoctor {

        requires = ['asciidoctor-diagram']
        backends  'html5'

        sources {
            include 'file.adoc'
        }
        attributes  'dotdir':file('dotDit')
    }

````
Would you please help me to resolve this ?
Thanks

**Comment by abelsromero** [comment]
If you're are using Gradle, you can use `asciidoctor-diagram` v1.5.4 gem directly, instead of using the asciidoctorj wrapper which is v 1.5.0.
This is no easy task, but here is an example that does the same with `asciidoctor-pdf` https://gist.github.com/mojavelinux/3f5839d332fd554c46bb020d9170bba8

Quick summary:
- You use `com.github.jruby-gradle.base` to download a the gems in the build directory.
- Then, tell AsciidoctorJ to import those gems and use (require) them https://gist.github.com/mojavelinux/3f5839d332fd554c46bb020d9170bba8#file-build-gradle-L47-L48

**Comment by jvmlet** [comment]
Thanks, @abelsromero , this helps
No I'm facing another issue: extension treats the path as relative and tries to evaluate it against current directory :
````
No such file or directory - D:/DHP/asp_core/pipeline/pipeline-initializer/src/docs/asciidoc/$D:/DHP/asp_core/pipeline/pipeline-initializer/graph.dot
````

According to the [documenttion](https://github.com/asciidoctor/asciidoctor-diagram/blob/master/examples/features.adoc#loading-diagrams-from-external-files), it should honor the absolute path:
`
When the target is a relative path it is resolved with respect to the location of the document being processed. 
`
Here is the gradle script :
````
asciidoctor {
    attributes  'dotdir': project.projectDir.absoluteFile
}
````

and adoc snippet:

`
graphviz::${dotdir}/graph.dot[format="svg", align="center",opts="inline"]
`

**Comment by mojavelinux** [comment]
The problem is the `$` in the graphviz macro. An AsciiDoc attribute does not have a leading `$`. This is confusing the path resolver.

**Comment by jvmlet** [comment]
Thanks, @mojavelinux  and @abelsromero , the issue is resolved, `$` sign came from SpEL I used to work with...
