### ISSUE TITLE
asciidoctorj-pdf: update asciidoctor-pdf gem

### ISSUE THREAD

**Issue by thetric** [asciidoctor/asciidoctorj#546]
The [latest release](https://github.com/asciidoctor/asciidoctor-pdf/releases/tag/v1.5.0.alpha.15) of `asciidoctor-pdf` contains some interesting bug fixes.  Is it possible to update the gem version or to enable the user to specify a custom version?  For the `asciidoctorGemVersion` it is [possible](https://github.com/asciidoctor/asciidoctorj/blob/master/build.gradle#L47) for the user to provide a version.

**Comment by abelsromero** [comment]
If you need it, it is possible to use the gem directly from both AsciidoctorJ the Gradle plugin([example](https://gist.github.com/mojavelinux/3f5839d332fd554c46bb020d9170bba8)) or the Maven plugin  (with more or less effort depending on the case) as any other Asciidoctor Ruby extension/converter/etc.

What is you're case?

**Comment by thetric** [comment]
I'm using the Gradle plugin. The linked example helps me a lot. Thanks for your quick answer :+1
