### ISSUE TITLE
Upgrade to asciidoctor-diagram 1.5.5 not working

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#562]
This issue continues asciidoctor/asciidoctor-diagram/issues/159

The Jars in Asciidoctor-Diagram are now loaded by a ServiceLoader.
Therefore they are not available to the Classloader.
It looks like the jars have to be unpacked and the Services files have to be merged.

**Comment by rdmueller** [comment]
I guess this is the reason why there isn't a asciidoctorj-Diagram 1.5.5 release yet?
...and this blocks an upgrade to asciidoctorj 1.5.6 because it seems to need diagram.1.5.5 in order to work:
https://github.com/asciidoctor/asciidoctor-diagram/issues/154 

it there any way I can support fixing this bug?

**Comment by robertpanzer** [comment]
I have no idea how to fix this atm.
A fix in Asciidoctorj would be to set the TCCL to the JRubyClassLoader. 
I am reluctant though to do this because it would very likely break all extensions that rely on the TCCL, for example extensions running in a JavaEE environment. 

A fix in asciidoctor-diagram would be to not only load extensions via the TCCL but also the classloader that loaded the asciidoctor-diagram CommandServer that loads the processors per diagram type, which should be the JRubyClassLoader: https://github.com/asciidoctor/asciidoctor-diagram-java/blob/f411d662fddc3e06d99108687122769d1270ed42/server/src/main/java/org/asciidoctor/diagram/CommandServer.java#L40

**Comment by mojavelinux** [comment]
The related issue is now closed. Does that mean this issue is resolved?

**Comment by robertpanzer** [comment]
Oh yes! Thanks!
