### ISSUE TITLE
Add MacOS build to TravisCI

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#566]
While checking another project I saw they integrate macOs in their travis configuration and I think we should do too. Doesn't seem that hard.

The only issue I have detected is setting up 2 builds that install graphviz:
-  for linux we can try the new apt addon https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-with-the-APT-Addon
- for mac we can try to use the included homebrew

I'd like to keep everything clean in the .travisci file, but if we can't, worst case scenario, we have to make a sh with some `if (macOs) do_this this, else do_that`.

One thing I don't get and may affect is this hostname thing here https://github.com/asciidoctor/asciidoctorj/blob/master/.travis.yml#L8

**Comment by mojavelinux** [comment]
I think this is a good idea. My only slight concern is the number of builds in the job. I think we should pick one version of JRuby and the JVM to test on OS X. The matrix testing doesn't need to be repeated.

**Comment by ancho** [comment]
If I remember correctly it was a workaround to get openjdk7 working on travis.
It should be obsolete with https://docs.travis-ci.com/user/hostname.

See https://github.com/travis-ci/travis-ci/issues/5227 for reference.

**Comment by abelsromero** [comment]
Just reporting, I did not get much progress on this topic 😞 

Many things got mixed with this.
Travis is migrating to Ubuntu Trusty and changing some configurations (https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming?utm_source=web&utm_medium=banner&&utm_campaign=trusty-default). Since current travis job was created some time ago it still uses the old infrastructure and work. The build on my fork uses the new and requires more changes to work.
On top of that, there seems to be some issue with how the JAVA path is set and only Java8 build works: https://github.com/travis-ci/travis-ci/issues/8206.
I'd advise to stop this until this is fixed, I will follow on the topic.

**Comment by mojavelinux** [comment]
Thanks for that info, Abel. Perhaps we should make the improvements you
identified one at a time, starting with the upgrade to Trusty.
