### ISSUE TITLE
Drop the CONTEXT_ prefix used by constants in Contexts annotation

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctorj#569]
I don't think the CONTEXT_ prefix is needed for the names of constants in the Contexts annotation. To me, it's already understood that we're talking about a context. Thus, the names should be like:

```
Contexts.OPEN
```

If there's a reason for the CONTEXT_ prefix, then I think it should be documented in the interface so the reason is clear.

**Comment by robertpanzer** [comment]
I think we can close this issue.
The PR was shipped with v1.6.0-alpha.5.
