### ISSUE TITLE
Question: Is it correct to use acsiidoctorj to parse markdown files?

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [asciidoctor/asciidoctorj#574]
Sorry, maybe it's a stupid question, but I'am a newer in asciidoc format. Acsiidoc format very similar to markdown. Is it correct to use acsiidoctorj to parse md files?

**Comment by abelsromero** [comment]
I am afraid not.
But as you correctly say, it's very similar. Here are some notes about compatibly and migration http://asciidoctor.org/docs/user-manual/#convert-markdown-to-asciidoc.

If you are considering a change, you can try https://github.com/bodiam/markdown-to-asciidoc to convert documents automatically. Btw it's integrated in the IntelliJ [AsciiDoc ](https://plugins.jetbrains.com/plugin/7391-asciidoc)plugin.
Also, just in case you need to go back (honestly, can't see why, but still), you can convert AsciiDoc to Markdown using the trick explained [here](https://stackoverflow.com/questions/26430433/convert-asciidoc-to-markdown).

**Comment by AndrienkoAleksandr** [comment]
@abelsromero, thank you.
