### ISSUE TITLE
Add CI build for Java 9

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#591]
It looks like JRuby (>=9.1.14.0) and AsciidoctorJ are ready to run on Java 9 (>=9.0.1).
The CI build on Travis should also run the build on Java 9.

It looks like the version of Gradle that we use at the moment, 2.14.1, doesn't run on Java 9.
Therefore I guess the hardest part of this task is to upgrade the build to a current version of Gradle.

It would be also nice to see if it's already time to migrate the build to Kotlin or if Groovy is still the way to go. (Is Gradle called Kradle then? :wink: )

**Comment by mojavelinux** [comment]
Yeah for Java 9 support in JRuby! Too bad about Gradle, though.

I wonder if it would be possible to fork the tests so that the version of Java we use for tests doesn't affect the version we use to run Gradle.

I support the effort to explore Kradle as another route.

**Comment by jmini** [comment]
Pull requests:

* `master` branch: #614
* `asciidoctor-1.6.0` branch: #611 

Thank you @tisoft

I guess this issue can now be closed.

**Comment by jmini** [comment]
I tested it on windows (see #608)

```
gradlew.bat publishToMavenLocal -Pskip.signing

FAILURE: Build failed with an exception.

* What went wrong:
Task 'publishToMavenLocal' not found in root project 'asciidoctor'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
```

Do I need to install a Java 9 JDK in order to run it?

**Comment by tisoft** [comment]
No, you don't need Java9. It just doesn't fail to compile on Java 9 anymore (in the 1.6.0 branch)

I just checked the publishToMavenLocal task and it works for me. Could you paste the complete output?

**Comment by jmini** [comment]
Never mind, my mistake. It works as expected.

**Comment by jmini** [comment]
Pull request to add java 9 CI on the `master` branch => #628
