### ISSUE TITLE
(RuntimeError) can't modify frozen NilClass on getParent()

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctorj#593]
When `getParent()` is called on the root `ContentNode` (where `null` is expected), a ruby `RuntimeError` is thrown.

Code to reproduce it:

    public static void main(String[] args) {
        String s = "== A small Example\n" +
                "\n" +
                "Lorem ipsum dolor sit amet:\n";

        org.asciidoctor.Asciidoctor asciidoctor = org.asciidoctor.Asciidoctor.Factory.create();
        org.asciidoctor.ast.Document document = asciidoctor.load(s, new java.util.HashMap<String, Object>());
        org.asciidoctor.ast.ContentNode parent = document.getParent(); // Runtime error here!
        System.out.println(parent);
    }

Using `org.asciidoctor: asciidoctorj:1.6.0-alpha.6` as dependency.

Error is:
> Exception in thread "main" org.jruby.exceptions.RaiseException: (RuntimeError) can't modify frozen NilClass

---

The code works with `org.asciidoctor:asciidoctorj:1.5.6` (the code needs to be modified, because the API changed):

    public static void main(String[] args) {
        String s = "== A small Example\n" +
                "\n" +
                "Lorem ipsum dolor sit amet:\n";

        org.asciidoctor.Asciidoctor asciidoctor = org.asciidoctor.Asciidoctor.Factory.create();
        org.asciidoctor.ast.Document document = asciidoctor.load(s, new java.util.HashMap<String, Object>());
        org.asciidoctor.ast.AbstractNode parent = document.getParent();
        System.out.println(parent);
    }

This works: `parent` is `null` as expected.

**Comment by robertpanzer** [comment]
Thanks for finding this issue :+1:
Should be fixed with #594

**Comment by robertpanzer** [comment]
Will be fixed with 1.6.0-alpha.7

**Comment by jmini** [comment]
Please add the `1.6.0-alpha.7` milestone to this issue. I do not have the permission to do it myself. Thank you.

**Comment by robertpanzer** [comment]
Thanks for the heads up! :)
