### ISSUE TITLE
Infinite recursion

### ISSUE THREAD

**Issue by ham1** [asciidoctor/asciidoctorj#595]
I am working on a small PR to fix some static analysis issues when I found this infinite loop:

https://github.com/asciidoctor/asciidoctorj/blob/0b76a6aee5429c2c97863a64bd85ae8c1b9c1061/asciidoctorj-core/src/main/java/org/asciidoctor/ast/CellImpl.java#L26-L27

I presume this is a bug but I don't know enough about the project to fix it.

**Comment by robertpanzer** [comment]
Good catch. Thank you!
I'll create a fix for this.

**Comment by robertpanzer** [comment]
The 1.6.0 branch doesn't seem to be have this bug.
