### ISSUE TITLE
Java 7

### ISSUE THREAD

**Issue by ham1** [asciidoctor/asciidoctorj#598]
It looks like gradle (and the codebase) is set up to use Java 6, but release 1.5.6 states that Java 7 is now required, https://github.com/asciidoctor/asciidoctorj/releases/tag/v1.5.6:

> That means that asciidoctorj-pdf no longer supports Java 6 but requires at least Java 7.
Also the AsciidoctorJ distribution by default requires Java 7

**Comment by robertpanzer** [comment]
Thanks for the issue, maybe the clarification was too subtle.
We generally want to provide AsciidoctorJ 1.5.x for Java 6.
So anyone who just uses the dependency org.asciidoctor:asciidoctorj should still be able to use it with Java 6. This should in particular keep Maven or Grade builds safe who build the documentation to HTML with Java 6, for example as part of Maven sites.
Changing the required version of Java with a minor release should be avoided in my opinion, even if it only affects a rather small number of users.

Now asciidoctor-pdf, the basis for asciidoctorj-pdf requires a newer version of Ruby (>= 2.0.0 afaik).
But this version is only fully supported by JRuby >= 9.0.0.0 and that one requires Java 7.
To provide a seamless experience for users of the full distribution we decided to ship JRuby 9.x.x.x with the distribution.

Did that make it a bit clearer?

**Comment by ham1** [comment]
Yeah, I understand now. Thanks.
