### ISSUE TITLE
createInline missing (?)

### ISSUE THREAD

**Issue by SevereOverfl0w** [asciidoctor/asciidoctorj#621]
https://www.javadoc.io/doc/org.asciidoctor/asciidoctorj/1.6.0-alpha.6 in the javadoc, I can't find `createInline()`. I found it in the source code though. But I don't seem able to call it.

It being missing from the javadoc is definitely suspect in this regard.

**Comment by robertpanzer** [comment]
Hi Dominic, 
where did you find this?
The method was renamed to createPhraseNode(): https://github.com/asciidoctor/asciidoctorj/tree/asciidoctorj-1.6.0#inline-macro-processor
I agree, if we still refer to createInline anywhere in the asciidoctorj-1.6.0 branch, we should replace it.

**Comment by SevereOverfl0w** [comment]
Ah, I'm not on the 1.6.0 branch for doing my code searching! I just read the README blindly. Thanks for the swift response.
