### ISSUE TITLE
How to install to local m2 repository ?

### ISSUE THREAD

**Issue by agoncal** [asciidoctor/asciidoctorj#626]
Disclaimer : I'm totally new to Gradle and Ruby. 

I want to build the asciidoctorj-epub3 artifact with the latest 1.5.0-alpha.8.dev. So I've been playing with Gradle and Ruby. I've managed to build the artifact, but now, I would like to install it automatically on my local m2 repository (so my other projects can do it).

I've been looking and trying [several](https://stackoverflow.com/questions/6122252/gradle-alternate-to-mvn-install) [ways](https://stackoverflow.com/questions/2572811/gradle-make-a-3rd-party-jar-available-to-local-gradle-repository) to do this, but so far I've failed.

Do you know a way to tell the Gradle build to install the artifacts into the local M2 Repo ?

Thanks

**Comment by robertpanzer** [comment]
If the build works, this should do the trick:
```
asciidoctorj> ./gradlew asciidoctorj-epub3:publishToMavenLocal
```
Or even shorter:
```
asciidoctorj> ./gradlew asciidoctorj-epub3:pTML
```

**Comment by mojavelinux** [comment]
FYI, I'll be releasing Asciidoctor EPUB3 tomorrow. All the issues are in. All that's left is to cut it.

**Comment by agoncal** [comment]
@robertpanzer I get the following : 

```
$ ./gradlew asciidoctorj-epub3:publishToMavenLocal

> Configure project : 
No Signatory configured for project asciidoctorj. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-diagram. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-distribution. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-epub3. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html

Configuration(s) specified but the install task does not exist in project :asciidoctorj-distribution.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':asciidoctorj-epub3:signPom'.
> Cannot perform signing task ':asciidoctorj-epub3:signPom' because it has no configured signatory
```

**Comment by agoncal** [comment]
@mojavelinux Really ? That's awesome. I was trying to give it another try and build it myself... nearly there, but then, Gradle kicked in ;o)

**Comment by robertpanzer** [comment]
Ah, forgot that by default it signs the poms and requires the respective signatory to be configured unless you explicitly skip this by setting the project property `skip.signing`
I hope that this works:
```
asciidoctorj> ./gradlew asciidoctorj:epub3:pTML -Pskip.signing
```

**Comment by agoncal** [comment]
Yes, with `-Pskip.signing` it works.

Thnks

**Comment by mojavelinux** [comment]
@robertpanzer Would you be willing to release AsciidoctorJ EPUB3 now that 1.5.0.alpha.8 is out? It didn't introduce any new dependencies, so I suspect it should be a straightforward upgrade.

**Comment by robertpanzer** [comment]
Of course. I’ll do a release at latest over the weekend.

**Comment by robertpanzer** [comment]
Couldn't resist. :)
Already published the new version to bintray.
I hope that there's no issues with it, we should probably add some tests for the epub3 backend like we have for pdf.

**Comment by agoncal** [comment]
@robertpanzer @mojavelinux Thank you guys. I just tried the latest version and it works !!! Well, of course it works ;o)  I was waiting for the :xrefstyle: for EPUB, and it works.

Really appreciate guys !

**Comment by mojavelinux** [comment]
Thank you, thank you @robertpanzer! I'm so happy it's both published and working. Time for :beers: !

**Comment by robertpanzer** [comment]
Thanks! But it looks like it wasn't that perfect. Forgot to rely on the released version of asciidoctorj.
I guess that's another reason for extracting these modules into separate repos.
