### ISSUE TITLE
TOC image/title link

### ISSUE THREAD

**Issue by jmcc0nn3ll** [asciidoctor/asciidoctorj#642]
I am rendering out a toc positioned to the left (html5) and I would like to be able to make something in that area clickable back to the main project site for Jetty.  Right now I have a css background image shoved up there for appearances but nothing clickable and the overridden 'Table of Contents' text can't take a link through the :toc-title: directive. Adding javascript to do it after page load seems awfully heavy-handed.

Is there an established way I should be doing this?  Is the expectation to use some sort of custom html template? Alternately if you point me where I ought to look maybe I could make a PR that lets a link get passed?

**Comment by robertpanzer** [comment]
You probably want to create this ticket in https://github.com/asciidoctor/asciidoctor.
AsciidoctorJ is just a Java API for this project.

Looking at the code of the HTML5 backend though it doesn't seem to be possible right now to do that, the toc seems to be fixed: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L292-L318

**Comment by jmcc0nn3ll** [comment]
Thanks! I'll take a look and open it over there if it looks reasonable.

**Comment by mojavelinux** [comment]
> the overridden 'Table of Contents' text can't take a link through the :toc-title: directive

If you force substitutions to be applied eagerly, you can pass a link through the toc-title as follows:

```
:toc-title: pass:n[https://example.org[Linked Text]]
```

See https://asciidoctor.org/docs/user-manual/#attribute-entry-subs to find an explanation.

If you want to do deeper customization of the table of contents, then you'll want to use a custom converter template. For details about that, see https://github.com/asciidoctor/asciidoctor.org/issues/80.

**Comment by jmcc0nn3ll** [comment]
I am back to working on this and converting the eclipse jetty site in general to better tie it and the jetty docs together.  There seems many ways to accomplish deeper customization, is slim still a good route to accomplish things like this and more heavy-handed changes? Our needs are relatively modest, we just need to generate the static website across a couple of github repositories and then glue it together in a third.

**Comment by mojavelinux** [comment]
If you want a simple way to customize the HTML, I strongly recommend using templates. It gives you 100% control over the HTML that Asciidoctor generators, and opens up a lot of possibilities. The templates can be loaded from a directory regardless of whether you're using Asciidoctor or AsciidoctorJ.

You can find an example I just posted today about using custom templates here (except in this case it applied to DocBook): https://github.com/asciidoctor/asciidoctor/issues/2974#issuecomment-442617591

(when using AsciidoctorJ, you don't need the extra dependencies as they are already provided for you).

**Comment by jmcc0nn3ll** [comment]
Thanks, that is the direction I am taking things now, much appreciated. I just need to take a look at the maven plugin closer, it doesn't seem able to layer templates, I had to drop all of the backend-html5 files into the template directory to make it work.  but that is another issue...for now I'll close this issue out.
