### ISSUE TITLE
Getting indexed attribute by key in inline macro returns null in 1.6.0-alpha.6

### ISSUE THREAD

**Issue by coreagile** [asciidoctor/asciidoctorj#653]
Greetings,

I'm working on an inline macro that relies on positional parameters. It seems the following code should do the same thing, but it doesn't:

```java
public Object process(ContentNode parent, String target, Map<String, Object> attributes) {
    // returns correct value
    String value = String.valueOf(attributes.entrySet().stream().findFirst().get().getValue());

    // returns "1=<correct value>"
    System.out.println(attributes.entrySet().iterator().next());

    // returns null -- this seems broken to me!
    System.out.println(attributes.get(attributes.keySet().iterator().next()));
}
```

Am I doing something wrong? Is there a bug?

Thanks!

**Comment by robertpanzer** [comment]
Hi Stephen,

to access positional attributes the preferred way is to annotate the processor with the `@PositionalAttributes` annotation to map positional attributes to attribute names.
For an example look here: https://github.com/asciidoctor/asciidoctorj/blob/asciidoctorj-1.6.0/asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/AnnotatedLongInlineMacroProcessor.groovy#L9

(Sorry for responding so late)

Cheers,
Robert

**Comment by coreagile** [comment]
Thanks for letting me know. I'm using your library in Clojure (see https://itl.calmabiding.me/doc/trunk/docs/index.html#itl.asciidoc), so I don't have the ability to use that annotation without a bunch of extra gyrations that don't seem to be worth the effort. That's fine, though -- I was able to coerce the value into a Clojure map and access it values by key that way quite easily.

Appreciate the help!

**Comment by robertpanzer** [comment]
Then you might try this:
```groovy
class AnnotatedLongInlineMacroProcessor extends InlineMacroProcessor {

    public static final String SUBSECTION = 'subsection'
    public static final String SECTION = 'section'

    public AnnotatedLongInlineMacroProcessor() {
        super("man", )
        getConfig().put("pos_attrs", Arrays.asList(SECTION, SUBSECTION));
    }

    @Override
    Object process(ContentNode parent, String target, Map<String, Object> attributes) {
        assert attributes[SECTION] == '7' || ( attributes[SECTION] == '8' || attributes[SUBSECTION] == '1')

        Map<String, Object> options = new HashMap<String, Object>()
        options['type'] = ':link'
        options['target'] = "${target}.html"
        createPhraseNode(parent, 'anchor', target, attributes, options).convert()
    }
}
```

That is, the difference here is that you configure the positional attributes in the constructor of the processor.
