### ISSUE TITLE
Upgrade to latest Tilt

### ISSUE THREAD

**Issue by msgilligan** [asciidoctor/asciidoctorj#655]
It looks like https://github.com/asciidoctor/asciidoclet/issues/45 has been fixed upstream in Tilt. See:

* https://github.com/rtomayko/tilt/pull/276
* https://github.com/rtomayko/tilt/blob/master/CHANGELOG.md#205-2016-06-02

I believe we need this fix made in asciidoctorj, not in Asciidoclet.

**Comment by robertpanzer** [comment]
Would you like to create a PR for this?

**Comment by msgilligan** [comment]
I'll try...

**Comment by msgilligan** [comment]
PR created. We an discuss it further over [there](https://github.com/asciidoctor/asciidoctorj/pull/656).

**Comment by robertpanzer** [comment]
Released with 1.5.7
