### ISSUE TITLE
asciidoctorj fails on macOS when run from ~ and using relative path to input file

### ISSUE THREAD

**Issue by apjanke** [asciidoctor/asciidoctorj#662]
Consider the following test invocation, where you're operating on a file in the current directory, and giving a relative path to it:

```
$ asciidoctorj test.adoc
```

This works fine on most situations. But on macOS, if you run it from your home directory, it will fail, and complain about not being able to find the input file under the installation location of AsciidoctorJ.

```
[~/tmp/asciidoctor]
$ pwd
/Users/janke/tmp/asciidoctor
[~/tmp/asciidoctor]
$ asciidoctorj test.adoc
[~/tmp/asciidoctor]
$ cd
[~]
$ pwd
/Users/janke
[~]
$ asciidoctorj test.adoc
asciidoctor: FAILED: input file(s) '/usr/local/Cellar/asciidoctorj/1.5.7/libexec/bin/test.adoc' missing or cannot be read
Exception in thread "main" java.lang.IllegalArgumentException: asciidoctor: FAILED: input file(s) '/usr/local/Cellar/asciidoctorj/1.5.7/libexec/bin/test.adoc' missing or cannot be read
	at org.asciidoctor.cli.AsciidoctorInvoker.renderInput(AsciidoctorInvoker.java:138)
	at org.asciidoctor.cli.AsciidoctorInvoker.invoke(AsciidoctorInvoker.java:65)
	at org.asciidoctor.cli.AsciidoctorInvoker.main(AsciidoctorInvoker.java:183)
```

I suspect it has something to do with this stanza in the `asciidoctorj` wrapper script, lines 167-170.

```
# by default we should be in the correct project dir, but when run from Finder on Mac, the cwd is wrong
if [ "$(uname)" = "Darwin" ] && [ "$HOME" = "$PWD" ]; then
  cd "$(dirname "$0")"
fi
```

Is that `cd` really necessary? Seems the `$APP_HOME` variable set earlier on should take care of locating the AsciidoctorJ installation.

This is using AsciidoctorJ 1.5.7.

**Comment by robertpanzer** [comment]
😖 Looks like this came in with our upgrade to Gradle 4.4...
1.5.6 didn't have this problem which was still built with Gradle 2.4
It looks like this change came in with Gradle 3.0: https://github.com/gradle/gradle/commit/a2b76dff7d879e6f0997f9a4fe746216e05011a6

It's probably best to not rely on undocumented parts of Gradle and host the template ourselves
 (which seems to be documented)
I really have no clue how such a breaking, unpredictable change could come in...

**Comment by robertpanzer** [comment]
Thanks for reporting this issue and the good analysis, @apjanke !
