### ISSUE TITLE
Nested content blocks seem to be unstructured when using readDocumentStructure()

### ISSUE THREAD

**Issue by eriwen** [asciidoctor/asciidoctorj#668]
As a developer, I would like to be able to extract _nested_ structured information from my asciidoc document so that I can do a bunch of interesting things with it. This may be related to #139.

My specific use cases are testing examples embedded within a document and extracting a list of examples and their metadata

Given the asciidoc document:

```adoc
= Doc Title

Preamble

== Subsection title

Subsection description

.Sample title
====
[.inline-sample]
=====
.build.gradle
[source,groovy]
----
task compile {
    doLast {
        println "compiling source"
    }
}
----

[.sample-command,allow-disordered-output=true]
----
\$ gradle -I init.gradle build
Some output
----
=====
====
```
</details>

## Expected Behavior

```java
Asciidoctor asciidoctor = Asciidoctor.Factory.create();
StructuredDocument document = asciidoctor.readDocumentStructure(myFileOrString, new HashMap<String, Object>());
// I'd love for this to have nested ContentParts that I can extract. 
List<ContentPart> sampleContents = document.getPartsByRole("inline-sample"); 
```

## Current Behavior

Something like the following Java code to process it:

```java
Asciidoctor asciidoctor = Asciidoctor.Factory.create();
 StructuredDocument document = asciidoctor.readDocumentStructure(myFileOrString, new HashMap<String, Object>());
 List<ContentPart> sampleContents = document.getPartsByStyle("example"); // This is empty
 List<ContentPart> sampleContents = document.getPartsByRole("inline-sample"); // Also empty  
```

It looks as though the content is already rendered, because `document.getParts().get(1).getContent()` returns generated HTML. 

Similarly, any attempt I make to have some call chain like `document.getParts().get(i).getParts()` is always null.

**Comment by mojavelinux** [comment]
readDocumentStructure is a deprecated API. It was just an experiment and has been replaced by a proper AST. Most of the work is in AsciidoctorJ 1.6.0. See this package: https://github.com/asciidoctor/asciidoctorj/tree/asciidoctorj-1.6.0/asciidoctorj-api/src/main/java/org/asciidoctor/ast

**Comment by eriwen** [comment]
Ah, excellent. I was able to achieve this using asciidoctorj-api 1.6.0.alpha.7. 

Perhaps the appropriate follow up actions here would be:
 * Mark `readDocumentStructure` as deprecated in the 1.5.x docs
 * Make more folks aware of this much nicer API

I can touch on the 2nd piece in a blog post announcing this Gradle project, but I'm not sure how to go about point 1. 

You are also welcome to close this issue @mojavelinux. Thanks again for the quick response.

**Comment by mojavelinux** [comment]
That's great news!

> Mark readDocumentStructure as deprecated in the 1.5.x docs

100% agreed.

> Make more folks aware of this much nicer API

We're going to make a lot of noise about it as soon as 2.0.0 is release (which is what 1.6.0 is going to become). I owe @robertpanzer some info about these plans.

> I can touch on the 2nd piece in a blog post announcing this Gradle project, but I'm not sure how to go about point 1.

We really appreciate that!

> You are also welcome to close this issue @mojavelinux. Thanks again for the quick response.

I'll leave that up to @robertpanzer.

**Comment by robertpanzer** [comment]
🎉 
@eriwen In case you missed it here are also some docs about the AST classes: https://github.com/asciidoctor/asciidoctorj/blob/asciidoctorj-1.6.0/docs/integrator-guide.adoc#understanding-the-ast-classes

Looking forward to the 2.0 development! :)

**Comment by eriwen** [comment]
I had not seen this integrator guide before. This is very useful — thank you!
