### ISSUE TITLE
Unable to prevent messages from showing in console using LogHandler

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#669]
Asciidoctorj: 1.5.7

As title suggests I'd like to prevent ERROR, WARN, etc. messages from showing in the console.
The idea is to have a `LogHandler` that "swallows" messages, but even when doing so, messages are shown. This also has the side effect that when redirecting the messages to another logger, they appear twice.

I also tried (to experiment, not as final solution) to set Verbose to false in case is was releated to the change we did, but no luck.

I wrote this code to show it: https://github.com/abelsromero/asciidoctorj-gradle/blob/master/src/main/java/org/asciidoctor/demos/AsciidoctorLogHandlerRunner.java

When run the console shows this:
```
$VERBOSE: true
$VERBOSE: false
ago 04, 2018 8:41:33 PM <script> convertFile
GRAVE: document-with-errors.adoc: line 3: include file not found: C:/Users/asalgadr/github/asciidoctorj-gradle/src/asciidoc/unexistingdoc.adoc
ago 04, 2018 8:41:33 PM <script> convertFile
GRAVE: document-with-errors.adoc: line 5: include file not found: C:/Users/asalgadr/github/asciidoctorj-gradle/src/asciidoc/unexistingdoc.adoc
ago 04, 2018 8:41:33 PM <script> convertFile
GRAVE: document-with-errors.adoc: line 9: include file not found: C:/Users/asalgadr/github/asciidoctorj-gradle/src/asciidoc/unexistingdoc.adoc
ago 04, 2018 8:41:33 PM <script> convertFile
ADVERTENCIA: document-with-errors.adoc: line 25: no callout found for <1>
```

*Note: GRAVE and ADVERTENCIA are Spanish for ERROR and WARNING.*

**Comment by robertpanzer** [comment]
AsciidoctorJ forwards everything that is logger by Asciidoctor, there's no filtering in that part so it's really just a very thin adaption layer that takes Ruby LogRecords and pushes them out synchronously to all registered LogHandlers.
If you want to filter them, your implementation of the LogHandler needs to implement this.

The global variable `$VERBOSE` only controls if Asciidoctor logs warnings for invalid refs (plus that it controls warnings messages from JRuby as I just learned). All other warning or error log entries are independent of this variable.

**Comment by abelsromero** [comment]
> If you want to filter them, your implementation of the LogHandler needs to implement this.

Afaik, I am doing so here https://github.com/abelsromero/asciidoctorj-gradle/blob/master/src/main/java/org/asciidoctor/demos/AsciidoctorLogHandlerRunner.java#L27.
Instead of printing the messages I am doing nothing with them, so nothing should appear in the console, right?

**Comment by robertpanzer** [comment]
Ah ok, now I understand.
Java Util Logging is always registered as a LogHandler, and the default configuration of JUL adds a ConsoleHandler.
If you want to prevent JUL from logging to the console you have to configure the `asciidoctor` logger and remove the ConsoleHandler.

**Comment by abelsromero** [comment]
I think we are passed this now.
