### ISSUE TITLE
Release Notes 1.6.7 - reference to JRuby version wrong?

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctorj#678]
In the release notes it states https://github.com/asciidoctor/asciidoctorj/releases/tag/v1.5.7

`Upgrade JRuby to 9.1.6.0`

but in build.gradle it states `jrubyVersion = '9.1.16.0'`

I suppose the build.gradle is correct and the release notes need to be updated?

**Comment by robertpanzer** [comment]
Thanks for the pointer. 
I updated the release notes accordingly.

**Comment by ahus1** [comment]
release notes have been updated by Robert, closing ticket.
