### ISSUE TITLE
Published API docs for 1.6 are incomplete

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctorj#686]
The API docs for 1.6 that get published to http://www.javadoc.io/doc/org.asciidoctor/asciidoctorj/1.6.0-alpha.7 are incomplete. In particular, most of the classes in the ast package are missing (see http://static.javadoc.io/org.asciidoctor/asciidoctorj/1.6.0-alpha.7/org/asciidoctor/ast/package-summary.html). It seems like the API docs from one of the jars (perhaps the API jar) is not getting picked up.

Given that the best APIs are in 1.6, this omission makes it tough to promote the new APIs.

**Comment by robertpanzer** [comment]
Thanks for the pointer! I’ll check that. I can imagine we lost that while moving the AST classes to the -api module.

**Comment by mojavelinux** [comment]
I agree I think the API docs should be combined.
