### ISSUE TITLE
Remove the StructuredDocument AST from AsciidoctorJ 1.6

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctorj#694]
The StructuredDocument AST was a competing effort to create an AST in AsciidoctorJ. While it served its purpose (namely to motivate the project to create an official AST), its presence is now just causing confusion. It's time to remove it (along with any related API).

Any functionality it provides should be integrated into the official AST or the main Asciidoctor interface. Though I believe the findBy method covers most of the methods it provided.

We'll leave this AST in 1.5.x so any existing code that relies on it will continue to work. But we've already told users of 1.6 to avoid these APIs, so they can be safely removed in that version.

**Comment by austek** [comment]
AST Builders should live in ast package and provide a way of creating AST objects independent of JRuby

**Comment by robertpanzer** [comment]
StructuredDocuments don't exist anymore in AsciidoctorJ 1.6.x with #699
