### ISSUE TITLE
asciidoctorj-api not published 

### ISSUE THREAD

**Issue by IRus** [asciidoctor/asciidoctorj#716]
Thanks for great work!

I'm trying version `1.6.0-RC.1` of `asciidoctorj`, but there are unresolved dependency to `asciidoctorj-api`. Looks like it's not published to bintray.

**Comment by robertpanzer** [comment]
Oh wow, thanks for the pointer.
I just pushed the artifacts, I hope it works now.

**Comment by IRus** [comment]
Yes, now it's ok
