### ISSUE TITLE
Trouble accessing attributes

### ISSUE THREAD

**Issue by lxsli** [asciidoctor/asciidoctorj#728]
AsciiDoctorJ 1.5.8.1

I'm loading docs with code a bit like this:

```
engine = Asciidoctor$Factory.create()
doc = engine.load("text", {"safe" org.asciidoctor.SafeMode/SECURE
                           "toFile" false})
```

I'm actually writing Clojure, I found a StackOverflow from someone trying to do similar from Scala.

Example doc:

```
:foo: bar

Meow.
```

Note I've included some text (otherwise you don't get a block within the section) and I've put the attribute before the text (otherwise it gets ignored). It seems like attributes are associated with the following block? Which seems weird, I expected them to be their own thing. That's secondary.

The real issue is that `.getAttributes` on the "Meow." block gives me this awful RubyHash thing. The key is :attribute_entries (as a RubySymbol). The value is a RubyHash$BaseCollection, containing a RubyArray, containing a RubyVar2 for each attribute on the block. I have to call `.var1` for the key and `.var2` for the value. This is the worst.

I'd prefer `.getAttributes` to return a java.util.HashMap or at least for the keys and values to be directly in the RubyHash. I found issue #692 which may be related?

**Comment by robertpanzer** [comment]
Do you have an example that you can share?
The return type of `Document.getAttributes()` and `AbstractNode.getAttributes()` is `java.util.Map<String,Object>`.
Relying on any particular implementation generally is a bad idea.

AsciidoctorJ 1.6.0, for which you can already get a release candidate, should better hide the details of the JRuby implementation.
Nevertheless I would think that it should be possible to get the value of the attribute.
(Actually I couldn't find out from your description what problem you are facing...)

In fact this test works for me:
```java
Document document = asciidoctor.load(":foo: bar\n\nMeow", OptionsBuilder.options().safe(SafeMode.SAFE).asMap());
Map<String, Object> documentAttributes = document.getAttributes();
assertEquals("bar", documentAttributes.get("foo"));
```
The translation to Clojure should be trivial.

**Comment by lxsli** [comment]
Yeah I should have said - on Document directly, it works great. I get a simple map. This RubyHash stuff is only an issue when I get attributes on blocks. A RubyHash does implement the Map interface and I suspect Clojure would deal with that fine, it's the junk inside that's the problem.

The issue is that AsciiDoctorJ should aspire to present a better Java API (as it does for `document.getAttributes`).

I can try 1.6.0 on Monday though, maybe this has already been cleaned up.

**Comment by mojavelinux** [comment]
Document attributes that are set in the flow (after the document header) are not supposed to be available via the API. This is likely to change in the future, but it has to happen in core first.

There are currently two publicly accessible locations for attributes.

1) In the document header via document.getAttributes()

```
= Document Title
:foo: bar
```

2) Directly on a block via block.getAttributes()

```
[foo=bar]
Meow
```

No other attributes should be visible via the API.

**Comment by abelsromero** [comment]
This is resolver with main branch version, could be closed.

**Comment by robertpanzer** [comment]
Thanks for checking this! 😊
