### ISSUE TITLE
Testing an AsciidoctorJ extension

### ISSUE THREAD

**Issue by bmuschko** [asciidoctor/asciidoctorj#729]
I am using [1.6.0-RC1](https://github.com/bmuschko/asciidoctorj-tabbed-code-extension/blob/master/build.gradle.kts#L20-L21) to write an [extension for AsciidoctorJ](https://github.com/bmuschko/asciidoctorj-tabbed-code-extension). The extension works functionality but I also tried to [write tests](https://github.com/bmuschko/asciidoctorj-tabbed-code-extension/blob/master/src/test/java/com/bmuschko/asciidoctorj/tabbedcode/TabbedCodeBlockDocinfoProcessorTest.java#L16-L29) for the extension. The code looks something like this:

```
Asciidoctor asciidoctor = Asciidoctor.Factory.create();
asciidoctor.javaExtensionRegistry().docinfoProcessor(TabbedCodeBlockDocinfoProcessor.class);
OptionsBuilder optionsBuilder = OptionsBuilder.options().headerFooter(true);
String html = asciidoctor.convert(getAsciiDoc(), optionsBuilder);
```

When executing the test it seems like the process method of my `DocinfoProcessor` implementation is never triggered. Am I using the API incorrectly or is this a bug of some sort? Any pointers would be highly appreciated.

**Comment by robertpanzer** [comment]
Docinfo processors aren't called when rendering with the default safe mode.
If you render with `SafeMode.SERVER` the extension should be called. (It was for me)
I.e. this should do the trick:
```java
OptionsBuilder optionsBuilder = OptionsBuilder.options()
    .headerFooter(true)
    .safe(SafeMode.SERVER);
```

**Comment by bmuschko** [comment]
That works. Thanks! Might be worth documenting in some way.

**Comment by mojavelinux** [comment]
It's true that docinfo processor extension are only called when the safe mode is secure or less. But I wonder if that's actually correct. No other extension is controlled by the safe mode. I'll open an issue in core to discuss.

**Comment by mojavelinux** [comment]
Generally speaking, you almost **always** want to set the safe mode when using the AsciidoctorJ API anyway. You lose access to a lot of features by not setting it (since the default is practically paranoid).
