### ISSUE TITLE
Render methods should be marked deprecated

### ISSUE THREAD

**Issue by bmuschko** [asciidoctor/asciidoctorj#730]
As [indicated by the documentation](https://github.com/asciidoctor/asciidoctorj#converting-documents), the `render` methods shouldn't be used anymore. When looking at the API I was confused about the difference between `render` and `generate`. Only recently did I see the note about `render`.

> Prior to Asciidoctor 1.5.0, the term render was used in these method names instead of convert (i.e., render, renderFile, renderFiles and renderDirectory). AsciidoctorJ continues to support the old method names for backwards compatibility.

The API should annotate the `render` methods with `@Deprecated` and also provide the replacement as a `@deprecated` description in the Javadocs.

**Comment by robertpanzer** [comment]
render() has been marked as deprecated.
