### ISSUE TITLE
Use the Asciidoctor logger from a Java Extension

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctorj#737]
With https://github.com/asciidoctor/asciidoctor/issues/44 a proper logger infrastructure has been added to Asciidoctor (ruby).

The logs can be accessed in AsciidoctorJ:
https://github.com/asciidoctor/asciidoctorj#logs-handling-api

> AciidoctorJ (v1.5.7+) offers the possibility to capture messages generated during document rendering

I was wondering if the AsciidoctorJ extension I am writing can access the Logger and add an entry.

Quoting @robertpanzer:

> While it's possible to receive the log entries that Asciidoctor logs, it's not possible yet for an extension to log using the same Logger that Asciidoctor is using.
I agree that it would make sense to expose this to extensions as well.

**Comment by abelsromero** [comment]
I am curios about the use case, to see how best approach this.

**Comment by mojavelinux** [comment]
From the Ruby side, the design is to simply include the Asciidoctor::Logging module into any class. For example, here's how it's done in Asciidoctor PDF (ignore the shim logic).

https://github.com/asciidoctor/asciidoctor-pdf/blob/db8d3bf3a58103d178901de4fac6977fa50aa1d2/lib/asciidoctor-pdf/converter.rb#L33

I'm not sure what the equivalent would be in Java.

**Comment by robertpanzer** [comment]
> I am curios about the use case, to see how best approach this.

If logged warnings let the build fail in the asciidoctor-maven-plugin it would be just logical for me that an extension should also be able to emit such warnings. 
Besides extensions converters should be able to log too. 
Just like Ruby code, Java code should be able to do the same.

**Comment by abelsromero** [comment]
But the maven plugin captures logs messages. Here we are talking about publishing, I see this as a different thing.
Publishing totally makes sense, but either we have a 'getLogger()' in the extensions API or a static 'AsciidoctorLogger.gerLogger()'. At least that keeps things independent, which is aligned with the current efforts.

**Comment by jmini** [comment]
`getLogger()` is exactly something I would expect.

Personally I do not care if I get the same logger than the ruby one or if this is a pure Java implementation.

As long as the warning I log in my extension go in the same list as the Ruby one, this is OK for me.

**Comment by jmini** [comment]
I am trying the feature from an `InlineMacroProcessor`:

```java
String warningMessage;
//... set value of warningMessage
log(new LogRecord(Severity.WARN, warningMessage));
```

I am wondering if there is a possibility to get access to the `Cursor` in order to use an other `LogRecord` constructor.
What did I miss?
