### ISSUE TITLE
plantuml and data-uri don't work together ?

### ISSUE THREAD

**Issue by bric3** [asciidoctor/asciidoctorj#738]
Hi,

I'd like to inline plantuml diagrams in my html5 document, however I cannot seem to get it right.
Either I have difficulty to find the right way to use the `data-uri` scheme to inline images for images generated by asciidoctorj-diagram in plantuml format. And even using inline SVG don't results in inlined document.

```
:doctype: book
:icons: font
:source-highlighter: coderay
:toc: left
:toclevels: 4
:sectlinks:
:sectanchors:
:docinfo:
:nofooter:
:data-uri:

:description: documentation

:logo: images/xxxxxxxxxxx.png

image:{logo}[text]

[plantuml, "flow", svg, opts="inline", height="100%", width="100%"]
----
title flow
autonumber

user -> client : access
----


[plantuml, "flow2", png]
----
title flow
autonumber

user -> client : access
----
```

## With `:data-uri:`

The real png image used in `image:{logo}` is correctly transformed as a `data-uri`. But the images generated for the plantuml diagram don't work. I got the following warnings.

```
/absolute/path/to/src/docs/asciidoc/index.adoc: SVG does not exist or cannot be read: /absolute/path/to/src/docs/asciidoc/flow.svg
```

```
image to embed not found or not readable: /absolute/path/to/src/docs/asciidoc/flow2.png
```

## without `:data-uri:`

The inlined SVG doesn't work anyway the generated HTML looks like that 

```
<div class="imageblock">
<div class="content">
<span class="alt">flow</span>
</div>
</div>
```

## Versions

I'm generating the doc within a gradle build :

```
buildscript {
    dependencies {
        classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.8.1'
    }
}

dependencies {
    asciidoctor "org.asciidoctor:asciidoctorj-diagram:1.5.10"
}

asciidoctorj {
    version = "1.5.7"
}

asciidoctor {
    requires 'asciidoctor-diagram'
    options doctype: 'book'
    attributes = ['source-highlighter': 'coderay',
                  'encoding'          : 'utf-8',
                  'version'           : project.version,
                  'build-timestamp'   : Instant.now().toString(),
                  'commit'            : commit.id ]
    sources {
        include 'index.adoc'
    }

    // enforce asciidoc processing
    // outputs.upToDateWhen { false }
}
```

## References

* https://github.com/asciidoctor/asciidoctor/issues/1301#issuecomment-222620678
* https://github.com/asciidoctor/asciidoctor-diagram/issues/64
* https://github.com/asciidoctor/asciidoctor-diagram/issues/110

**Comment by bric3** [comment]
It seems that this issue is similar to mine but it's related to the ruby version of asciidoctor-diagram : https://github.com/asciidoctor/asciidoctor-diagram/issues/198

It seems asciidoctorj-diagram has been moved from this repo to its own project, so I created a ticket hoping this will fix my issue : https://github.com/asciidoctor/asciidoctorj-diagram/issues/1
Because at this time it's a bit confusing.

**Comment by robertpanzer** [comment]
Closing as asciidoctor/asciidoctorj-diagram#1 has been closed.
