### ISSUE TITLE
"include file not found" error after recrusive include

### ISSUE THREAD

**Issue by joaoe** [asciidoctor/asciidoctorj#739]
Hi.

I'm building my project with gradle and using `asciidoctor` to handle my spring rest docs generated snippets.

My `build.gradle` looks like this
```
buildscript {
    dependencies {
        classpath("org.asciidoctor:asciidoctor-gradle-plugin:1.5.3")
    }
}

plugins {
    id "org.asciidoctor.convert" version "1.5.3" 
}

ext {
    snippetsDir = file('build/generated-snippets')
}
dependencies {
    asciidoctor 'org.springframework.restdocs:spring-restdocs-asciidoctor:2.0.2.RELEASE'
}

test {
    outputs.dir snippetsDir
}

asciidoctor {
    inputs.dir snippetsDir
    sourceDir = file('src/docs/asciidoc')
    sources {
        include 'index.adoc'
    }
    outputDir = file('build/docs')

    dependsOn test
}
```
My `src/docs/asciidoc` folder contains a `index.adoc`:
```
= Snippets
include::{snippets}/spring-rest-docs-index.adoc[]
```
The `build/generated-snippets/spring-rest-docs-index.adoc` file is generated as my API is being documented by SRD and it looks like
```
include::{snippets}/some-id/curl-request.adoc[curl]
include::{snippets}/some-id/httpie-request.adoc[httpie]
include::{snippets}/some-id/http-request.adoc[http request]
include::{snippets}/some-id/http-response.adoc[http response]
include::{snippets}/some-id/request-body.adoc[json request]
include::{snippets}/some-id/response-body.adoc[json response]
```

When building with gradle `gradlew asciidoctor`, the following error is produced (i'm using cygwin although:
```
> Task :asciidoctor
io/console not supported; tty will not be manipulated
asciidoctor: WARNING: ippets/spring-rest-docs-index.ado line 2: include file not found: /<path>/workspace/build/generated-snippets/some-id/curl-request.adoc
asciidoctor: WARNING: ippets/spring-rest-docs-index.ado line 3: include file not found: /<path>/workspace/build/generated-snippets/some-id/httpie-request.adoc
asciidoctor: WARNING: ippets/spring-rest-docs-index.ado line 4: include file not found: /<path>/workspace/build/generated-snippets/some-id/http-request.adoc
asciidoctor: WARNING: ippets/spring-rest-docs-index.ado line 5: include file not found: /<path>/workspace/build/generated-snippets/some-id/http-response.adoc
asciidoctor: WARNING: ippets/spring-rest-docs-index.ado line 6: include file not found: /<path>/workspace/build/generated-snippets/some-id/request-body.adoc
asciidoctor: WARNING: ippets/spring-rest-docs-index.ado line 7: include file not found: /<path>/workspace/build/generated-snippets/some-id/response-body.adoc
```
So, the very first include in  `index.adoc` resolves correctly into the snippets folder, but the `include` in the `spring-rest-docs-index.adoc` does not. The thing that is weird is that `{snippets}` is a variable with value `/<path>/workspace/project-name/build/generated-snippets` but if you notice in the last case, with the errors `project-name` is not present in the path.

If I run gradle with `--debug` it produces the following 
```
14:28:37.400 [DEBUG] [org.asciidoctor.internal.JRubyAsciidoctor] asciidoctor -B /<path>/workspace/project-name/src/docs/asciidoc -S UNSAFE -b html5 -a projectdir=../../.. -a rootdir=../../.. -a project-name=my-project -a project-group=io.mypackage -a project-version=0.0.1 /<path>/workspace/project-name/src/docs/asciidoc/index.adoc
```

So, so far this seems like a bug when resolving double includes.
Thank you.

**Comment by robertpanzer** [comment]
Hi Joao,

Thanks for creating this issue.
It would be great if you could provide a project to reproduce this problem.
Maybe you could also provide some hints on your environment, i.e. Windows/OSX/Linux, Java version etc.

**Comment by joaoe** [comment]
Hi !
a) a project that reproduces the problem https://github.com/joaoe/asciidoc-issue
b) Java 1.8, both using linux (Ubuntu 18) and Windows 10 (with or without cygwin)

**Comment by robertpanzer** [comment]
Hm... Besides recursive includes there's also the thing that the documents are loaded from multiple locations.
The base document under `src/docs/asciidoc` includes sth that is in `build/generated-snippets` which again includes sth from this file using the same attribute.

If I see it correctly in Asciidoctor the path is relativized to the `docdir`, i.e. `src/docs/asciidoc`, so that it doesn't match anymore on the second inclusion from `build/generated-snippets`
.
I got it working by defining another variable `recsnippetsdir` with the same value and using this in the doc under `build`.
(If spring rest docs generates documents including `{snippetsdir}` you might want to use the new variable in your docs under `src`)

Maybe @mojavelinux or @ysb33r have a better solution

**Comment by joaoe** [comment]
Hi!

> This is not actually a bug, but expected behaviour.

If you read a bit into my explanation, you'll see that the project folder name is removed, while the `snippetDir` variable IS absolute already (as set in the gradle file). So, I'm very confused how that could be regarded as expected behavior.

> 
> For 1.5.x set something like `attributes snippets : snippetsDir.absolutePath`. Normally this should be enough. If not, you need to look at setting `baseDir`.
> 
> In 2.0-alpha.5 there might just work if the attribute is set, but I have not tested spring-rest-docs compatibility as yet.

1. The attribute is already absolute
2. This is unrelated with spring rest docs, I just mentioned it because that's how I arrived at this setup

> 
> If your problem is not resolved please raise an issue against the Gradle plugin.

I'm calling asciidoc from gradle but this does not seem like a gradle plugin issue, unless you confirm that.

Thank you for your time :)

**Comment by JacquesLeRoux** [comment]
Hi,

We cross an issue in Apache OFBiz that could be related. It was working correctly before we switched from org.asciidoctor.gradle.AsciidoctorTask (and related) to org.asciidoctor.gradle.jvm.AsciidoctorTask:
https://github.com/apache/ofbiz-framework/commit/e248654735.

Should I rather ask at https://asciidoctor.org/docs/asciidoctor-gradle-plugin/ ?

TIA
