### ISSUE TITLE
Migrate build to Gradle 5

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#747]
Now that Gradle 5 is out our build should also be migrated to it.

**Comment by jmini** [comment]
In Gradle 5.0, the [OSGi Plugin](https://docs.gradle.org/5.0/userguide/osgi_plugin.html) was deprecated.
A migration to the BND plugin is described here: [Replacing use of Gradle's deprecated OSGi Plugin](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md#replacing-use-of-gradles-deprecated-osgi-plugin)

**Comment by Fiouz** [comment]
Beside making the build work with Gradle 5, what is the exact scope of this issue:
- Do we need to address deprecations (such as OSGi or `@Deprecated` APIs)?
- Do we need to implement new Gradle 5 recommendations such as [lazy configuration](https://docs.gradle.org/current/userguide/lazy_configuration.html) or [task configuration avoidance](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html)?

(obviously, if the answers to those questions if "no", it does not prevent creating new issues to address those points later if deemed necessary)

**Comment by robertpanzer** [comment]
That's a good question and I am not 100% sure either.

> Do we need to address deprecations (such as OSGi or @Deprecated APIs)?

We definitely need support for OSGi.
I don't really care whether this happens via an official OSGi plugin or some other external plugin.
(Even though it looks like these frequent breaks in Gradle don't make things easier if you use external plugins...)
I am ok with still using Deprecated APIs, we can still change that later.
If we get run with Gradle 5 and see the respective deprecation warnings we can still follow up and work on these later.

> Do we need to implement new Gradle 5 recommendations such as lazy configuration or task configuration avoidance?

That doesn't tell me much.
Whatever works should be fine.
