### ISSUE TITLE
RubyExtensionRegistry references Impl

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#749]
While refactoring the RubyExtensionRegistry to interfaces the implementation of this interface slipped through and appears as the return type:
https://github.com/asciidoctor/asciidoctorj/blob/15fd95849ad7f236a34a3e7a38321093ea741283/asciidoctorj-core/src/main/java/org/asciidoctor/extension/RubyExtensionRegistry.java#L8

Instead all methods should return just RubyExtensionRegistry.

This cannot be fixed on 1.6.0 as this would result in a binary incompatibility.

**Comment by mojavelinux** [comment]
> This cannot be fixed on 1.6.0 as this would result in a binary incompatibility.

This is a perfect example of what we left room to fix in 2.0.0.
