### ISSUE TITLE
AsciidoctorJ fails when registering a block processor instance while passing the name as a parameter

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#754]
To reproduce:
Register a Block processor passing the name as an argument, i.e. by calling this method:

```java
javaExtensionRegistry.block("yell", new MyBlockProcessor());
```

Rendering a document fails because Asciidoctor calls the `name` accessor of the extension when classes are registered.
This error affects AsciidoctorJ 1.6.0 only as previously extension instances were registered to Asciidoctor as instances.
This changed with 1.6.0 as now instances are wrapped in a Ruby class per registration.

**Comment by mojavelinux** [comment]
Will this require a change in Asciidoctor? (either to fix it or to remove unused code?)

**Comment by robertpanzer** [comment]
I have to admit though I don't fully understand this part of the code:
https://github.com/asciidoctor/asciidoctor/blob/1bf20fc2e8054e7724dc12d0aa26e2a04b871a5a/lib/asciidoctor/extensions.rb#L1397-L1400

First Asciidoctor instantiates the extension passing in the name, and then it calls the accessor again.

**Comment by robertpanzer** [comment]
While working on this I was wondering if we really want users to implement `getName()` and `setName()` on processors.
My understanding is that this was used to interface with Asciidoctor/Ruby as it uses these properties and this bridge called them.
But we should probably deprecate them and require block name registration:
- explicitly in the call to `JavaExtensionRegistry.block(name, (instance|class))`
- Implicitly via the `@Name` annotation.

As there are proxies between Asciidoctor/Ruby and the users implementation, there is actually no need for these methods anymore.

**Comment by mojavelinux** [comment]
> I have to admit though I don't fully understand this part of the code:
asciidoctor/asciidoctor:lib/asciidoctor/extensions.rb@1bf20fc#L1397-L1400

The name is optional. The implementation can provide it. The implementation must also self-identify with the same name that was used to create. That's all the code is doing there. It's a lot of edge cases. Some may not apply to AsciidoctorJ.
