### ISSUE TITLE
API design: StructuralNode.getBlocks() may return null

### ISSUE THREAD

**Issue by jensnerche** [asciidoctor/asciidoctorj#761]
Returning 'null' for Collections or Arrays is widly seen as a Bad Practice in API design. Please consider returning an empty list of blocks instead. I saw it in org.asciidoctor.ast.impl.ListImpl
and org.asciidoctor.ast.impl.DescriptionListImpl implementations.

**Comment by mojavelinux** [comment]
I'd be fine with returning an empty list. Even the Ruby API always returns a non-null object, so it's consistent.

**Comment by robertpanzer** [comment]
I just saw that In Asciidoctor List#items is an alias for List#blocks.
I'll probably just mirror that behavior.
