### ISSUE TITLE
How to set default charset in 1.6?

### ISSUE THREAD

**Issue by cjbrooks12** [asciidoctor/asciidoctorj#763]
This issue was raised to my attention by @polzak in JavaEden/OrchidStarter#3. 

Using Asciidctorj 1.6.0 (transitive dependency of OrchidAsciidoc 0.15.4) on Windows 10 with what looks like the Korean `x-windows-949` charset throws an error with the following message:

```
org.jruby.exceptions.MainExitException: unknown encoding name - x-windows-949
```

Using Asciidctorj 1.5.7 (transitive dependency of OrchidAsciidoc 0.14.0) seemed to be working fine, all other things equal.

Is there a way in 1.6 to manually set the default charset, for example to UTF-8? Or is there some other way to handle these kinds of encoding errors that I'm missing?

**Comment by mojavelinux** [comment]
I believe you can set the encoding globally in Java using the following flag:

```
-Dfile.encoding=UTF-8
```

Can you try that?

See https://stackoverflow.com/questions/361975/setting-the-default-java-character-encoding

**Comment by cjbrooks12** [comment]
That seems to do the trick, thanks!
