### ISSUE TITLE
Includeprocessor to transform a file to asciidoc

### ISSUE THREAD

**Issue by uniqueck** [asciidoctor/asciidoctorj#770]
I would like to implement a include processor to transform a refenrenced xml file to an asciidoc table representation. Is that possible?

**Comment by uniqueck** [comment]
The xml file the saved representation of a decision table. So my idea is to create a include processor to transform the xml file content to asciidoc code of a table and than let asciidoc do the rest.

**Comment by mojavelinux** [comment]
Yes, that's possible. You can see a similar example here: https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/textql-block.rb. You'd take advantage of the parse_content helper (there's a similar method mapped in AsciidoctorJ).

**Comment by robertpanzer** [comment]
If you want to write an extension in Java you additionally might want to check out this example from the test suite: 
https://github.com/asciidoctor/asciidoctorj/blob/asciidoctorj-1.6.x/asciidoctorj-core/src/test/groovy/org/asciidoctor/extension/GithubContributorsBlockMacro.groovy

It creates a table from information obtained from a rest endpoint. 
It’s in groovy but it should be pretty simple to translate it to Java.

**Comment by uniqueck** [comment]
where is the differenc between the way to create a table like the example from @mojavelinux and @robertpanzer . I would like to know, if it is better to create a table directly in html, or with the create methods, or better in asciidoc.
especially to be target format neutral.

**Comment by robertpanzer** [comment]
The Ruby example from @mojavelinux doesn't create HTML, but Asciidoc as an intermediate step and uses `parseContent` to create the Asciidoctor AST objects from it, which can in turn be rendered to anything.
The Java example directly creates the AST objects, which is surely a bit more work to do.
You can also use `parseContent()`  in Java, if you want to go for Java: https://github.com/asciidoctor/asciidoctorj/blob/d187987ea98b49ed3d30d60f70a7ff8bfe420f70/asciidoctorj-api/src/main/java/org/asciidoctor/extension/Processor.java#L114
That means in your block you would construct Asciidoc source content as you would write it manually, and then let Asciidoctor do its magic.

**Comment by mojavelinux** [comment]
As Robert points out, both ways are possible. There's no right or wrong way, just what is right for you. Sometimes it's easier to create the AST nodes, and sometimes it's easier to create the AsciiDoc and (sub)parse it. That's why we offer both strategies.

**Comment by uniqueck** [comment]
Thx for your help. I thought that it is better to create asciidoc to be independent for the choosen target format (PDF, HTML, epub and so one). So i try the way described by @robertpanzer.

**Comment by mojavelinux** [comment]
To be clear, we were both suggesting creating an output-agnostic representation. In fact, that's the best practice. It's just a matter of whether you create AsciiDoc then parse it or create the AST nodes directly (skipping the parsing step).

**Comment by uniqueck** [comment]
Ok thx for the clarification. Only for the next extension. I should work the same way if i generate plantuml asciidoc code, or?

**Comment by uniqueck** [comment]
Ok i finished my first extensions. Your hints and thoughts helped me to speed up my decision to generate direct asciidoc markup and do it with Java.

It is a great and simple API. Afterwards I can say it is very easy to write asciidoc extensions.
