### ISSUE TITLE
Bundle-SymbolicName is not unique between asciidoctorj and asciidoctorj-api

### ISSUE THREAD

**Issue by benradey** [asciidoctor/asciidoctorj#772]
When trying to install bundles into Apache Karaf 4.2.2, I get the following:

karaf@root()> bundle:install mvn:org.asciidoctor/asciidoctorj/1.6.2
Bundle ID: 46
karaf@root()> bundle:install mvn:org.asciidoctor/asciidoctorj-api/1.6.2                                                                                                                                            
Bundle IDs: 
Error executing command: Error installing bundles:
	Unable to install bundle mvn:org.asciidoctor/asciidoctorj-api/1.6.2: org.osgi.framework.BundleException: Bundle symbolic name and version are not unique: org.asciidoctor:1.6.2

The issue seems to be that in the MANIFEST.MF in both jars, the Bundle-SymbolicName only includes the package but not the bundle name, resulting in 'org.asciidoctor' being shared between both bundles.

**Comment by benradey** [comment]
Seems like the issue might be a bit trickier than a simple rename within the manifest. I just built the project locally after tweaking the symbolicName in the build.gradle files, and while that allows the bundles to be loaded into Karaf, there is still a class resolution issue.

I have the following code in my bundle:
        logger.info("Asciidoctor: " + Asciidoctor.class.toString());
        logger.info("Asciidoctor: " + NodeCache.class.toString());
        logger.info("DocumentHeader: " + DocumentHeader.class.toString());
The first and second lines succeed, while the third fails with the following:
java.lang.NoClassDefFoundError: org/asciidoctor/ast/DocumentHeader

I'm not an OSGI expert, but I believe this is because both the asciidoctorj and asciidoctorj-api bundles have "org.asciidoctor.ast" in their export-package headers. Although NodeCache and DocumentHeader are both part of the org.asciidoctor.ast package, NodeCache is provided by the asciidoctorj jar, while DocumentHeader is provided by the asciidoctorj-api jar. When attempting to resolve classes from the org.asciidoctor.ast package, the OSGI container searches for the first bundle to provide it and searches that bundle alone. Thus, NodeCache is able to be resolved, but DocumentHeader is not.

**Comment by robertpanzer** [comment]
We're currently working on separating the archives so that packages no longer overlap in #760 
This will be an effort for AsciidoctorJ > 1.6.x though.

**Comment by benradey** [comment]
Ah, that's great to know. Thanks! I'll close the issue.
