### ISSUE TITLE
asciidoctor sbt plugin

### ISSUE THREAD

**Issue by austek** [asciidoctor/asciidoctorj#781]
I've started to port the maven plugin to sbt, https://github.com/austek/asciidoctor-sbt-plugin/pull/1. I know @ktoso had a plugin project https://github.com/ktoso/asciidoctor-sbt-plugin but it seems to be dormant and I am not sure if I raise a PR against it.

I was thinking that any one of the sbt plugin project should be move to asciidoctor organisation where it should be.

**Comment by mojavelinux** [comment]
That's great news. I'd like to see it a mature a bit before extending an invitation to join the organization, but I definitely look forward to that being a goal.

**Comment by austek** [comment]
I created a project and we've started using it at Medidat
https://github.com/mdsol/asciidoctor-sbt-plugin

**Comment by robertpanzer** [comment]
I think it is safe to close this issue in this repo.
