### ISSUE TITLE
Update JCommander to the latest version

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#782]
Currently we're using org.jbeust:jcommander:1.35.
The latest version is org.jbeust:jcommands:1.72.
Simply upgrading the dependency results in some test failures, so it seems like there is some work to do,

**Comment by ysb33r** [comment]
Is it time to switch to picocli instead?

**Comment by mojavelinux** [comment]
I still think we should consider whether it makes sense to reuse the CLI class from Asciidoctor itself. That would avoid the code duplication. It might turn out to be a bad idea, but I think we should at least know why we don't.

**Comment by robertpanzer** [comment]
I think there is at least the `--classpath` option that is only available in AsciidoctorJ and not in Asciidoctor.
Also some parameters like `--loadpath` require processing before any Ruby code is called because they affect how the JRuby instance is created.

Maybe we can filter out these parameters, handle them and remove them from the call, and then invoke the original Asciidoctor CLI runner.

**Comment by robertpanzer** [comment]
I don't know picocli, or any other good alternative.
That said I am open for any other solution, it just looks like some users are complaining about the age of the version of jcommander that we currently use.
Unfortunately it looks like this does not follow semver so that we cannot simply update the version.
