### ISSUE TITLE
Registering LogHandlers in 2.0.0.RC1

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctorj#790]
I want to register a log handler using 

    Asciidoctor asciidoctor = Asciidoctor.Factory.create();
    asciidoctor.registerLogHandler(logHandler);

It seems that my log handler is not called at all, although there are log messages on a the console. It seems to me this changed in either AsciidoctorJ 1.6.x or 1.7.x

**Comment by robertpanzer** [comment]
Do you possibly have a reproducer?
There are tests for this, so I am really wondering why this doesn’t work.

**Comment by robertpanzer** [comment]
This PR is not yet released, that’s why the entries might be missing: https://github.com/asciidoctor/asciidoctorj/pull/786
I’ll try to create a new RC on Monday latest.

**Comment by ahus1** [comment]
Thanks for pointing me a the PR. I'll have a look a the test cases later today and see that I get them running on my local machine.

**Comment by ahus1** [comment]
I loooked into the tests. The changes in the PR to JavaLogger seem to have fixed it. I'm closing the ticket. Thanks for pointing me to the PR. Looking forward to the next RC, as a workaround I parse the console for now.

**Comment by ahus1** [comment]
I upgraded to RC.2 and still had a problem. Trying out different things I switched "Asciidoctor.Factory.create()" to "JRubyAsciidoctor.create()" [here](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/daee3166be39acaa317d640ac93d7f83244a8564/src/main/java/org/asciidoc/intellij/AsciiDoc.java#L119) - and now it works. 

Probably a classloader problem? Anyway, I'm keeping this issue closed.

**Comment by robertpanzer** [comment]
That sounds really strange.
`Asciidoctor.Factory.create()` tries to find the Asciidoctor implementation on the current class loader or TCCL.
I'll check if we were missing sth.

**Comment by robertpanzer** [comment]
Created #799 to fix the logger registration when Asciidoctor is created with Asciidoctor.Factory.create().
Thanks for finding this!
