### ISSUE TITLE
CLI reports asciidoctor version instead of Asciidoctorj

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#791]
After installing 1.6.0, 1.6.1 and 1.6.2 versions of Asciidoctorj with sdkman I noticed they all report v 1.5.8 like this when using `-V` argument:
```
AsciidoctorJ 1.5.8 [http://asciidoctor.org]
Runtime Environment: jruby x.x.x.x (x.x.x)
```
I checked the code and this is the gem version.

The CLI should probably report both AsciidoctorJ and asciidoctor gem versions to avoid confusing users.

**Comment by mojavelinux** [comment]
Here's what I recommend:

```
AsciidoctorJ 2.0.0 (Asciidoctor 2.0.6) [https://asciidoctor.org]
Runtime Environment (JRuby x.x.x.x (...))
```
