### ISSUE TITLE
Converting to html files is very slow

### ISSUE THREAD

**Issue by Allurx** [asciidoctor/asciidoctorj#793]
When I try to convert swagger to adoc and convert adoc to html,It took me 5 minutes,The version I am using is 2.0.0-RC.1，How to improve speed? thanks.

**Comment by mojavelinux** [comment]
Something seems seriously wrong. Asciidoctor should be absurdly fast at
converting to HTML. Can you profile it to see where it's getting stuck?

>

**Comment by Allurx** [comment]
`        long t1 = System.currentTimeMillis();
        Swagger2MarkupConfig config = new Swagger2MarkupConfigBuilder()
                .withMarkupLanguage(MarkupLanguage.ASCIIDOC)
                .withOutputLanguage(Language.ZH)
                .withPathsGroupedBy(GroupBy.TAGS)
                .withGeneratedExamples()
                .withoutInlineSchema()
                .build();
        // json to adoc
        String document = Swagger2MarkupConverter.from(new URL("http://localhost:8084/v2/api-docs"))
                .withConfig(config)
                .build()
                .toString();
        System.setProperty("jruby.compat.version", "RUBY1_9");
        System.setProperty("jruby.compile.mode", "OFF");
        File output = new File(CommonUtil.getTemporaryDirectory() + File.separator + "test.html");
        // adoc to html
        Asciidoctor.Factory.create().convert(document, OptionsBuilder.options()
                .backend("html")
                .headerFooter(true)
                .safe(SafeMode.UNSAFE)
                .docType("book")
                .attributes(AttributesBuilder.attributes()
                        .tableOfContents(true)
                        .tableOfContents(Placement.LEFT)
                        .sectNumLevels(3)
                        .sectionNumbers(true)
                        .hardbreaks(true)
                        .setAnchors(true))
                .toFile(output));
        long t2 = System.currentTimeMillis();
        System.out.println("耗時：" + (t2 - t1));`



this is my java code，Is there a problem，thanks

**Comment by Allurx** [comment]
> Something seems seriously wrong. Asciidoctor should be absurdly fast at converting to HTML. Can you profile it to see where it's getting stuck?
> […](#)

        long t1 = System.currentTimeMillis();
        Swagger2MarkupConfig config = new Swagger2MarkupConfigBuilder()
                .withMarkupLanguage(MarkupLanguage.ASCIIDOC)
                .withOutputLanguage(Language.ZH)
                .withPathsGroupedBy(GroupBy.TAGS)
                .withGeneratedExamples()
                .withoutInlineSchema()
                .build();
        // json to adoc
        String document = Swagger2MarkupConverter.from(new URL("http://localhost:8084/v2/api-docs"))
                .withConfig(config)
                .build()
                .toString();
        System.setProperty("jruby.compat.version", "RUBY1_9");
        System.setProperty("jruby.compile.mode", "OFF");
        File output = new File(CommonUtil.getTemporaryDirectory() + File.separator + "test.html");
        // adoc to html
        Asciidoctor.Factory.create().convert(document, OptionsBuilder.options()
                .backend("html")
                .headerFooter(true)
                .safe(SafeMode.UNSAFE)
                .docType("book")
                .attributes(AttributesBuilder.attributes()
                        .tableOfContents(true)
                        .tableOfContents(Placement.LEFT)
                        .sectNumLevels(3)
                        .sectionNumbers(true)
                        .hardbreaks(true)
                        .setAnchors(true))
                .toFile(output));
        long t2 = System.currentTimeMillis();
        System.out.println("耗時：" + (t2 - t1));

this is my java code，Is there a problem，thanks

**Comment by Allurx** [comment]
> profile it to see where it's getting stuck?

**Comment by mojavelinux** [comment]
Can you document which version of Java, AsciidoctorJ, and JRuby you are using.

Also, you very likely should not be setting these:

```
System.setProperty("jruby.compat.version", "RUBY1_9");
System.setProperty("jruby.compile.mode", "OFF");
```

**Comment by Allurx** [comment]
<dependency>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctorj</artifactId>
                <version>2.0.0-RC.1</version>
            </dependency>

only this one depends in my pom.xml,and my jdk version is 1.8

**Comment by Allurx** [comment]
> Can you document which version of Java, AsciidoctorJ, and JRuby you are using?
> 
> Also, you very likely should not be setting these:
> 
> ```
> System.setProperty("jruby.compat.version", "RUBY1_9");
> System.setProperty("jruby.compile.mode", "OFF");
> ```

            <dependency>
                <groupId>org.asciidoctor</groupId>
                <artifactId>asciidoctorj</artifactId>
                <version>2.0.0-RC.1</version>
            </dependency>

only this one depends in my pom.xml,and my jdk version is 1.8

**Comment by mojavelinux** [comment]
You shared the code, but not the results. What is the elapsed time? Also, can you exclude the call to Swagger2Markup. We can only help with the line that starts with Asciidoctor.Factory.create().

If you are calling Asciidoctor a lot, then you should store the Asciidoctor instance in a shared location so that you aren't loading JRuby each time you convert a document.

**Comment by mojavelinux** [comment]
Also, did you get different results with 1.5.8? You need to share as many details as possible if you want us to be able to help you.

**Comment by Allurx** [comment]
> Also, did you get different results with 1.5.8? You need to share as many details as possible if you want us to be able to help you.

thank you very much，now  I have found the problem.due to the virtual machine startup parameters I set, for example -Xms 64m -Xmx128m,when I remove parameters, it normal work,Anyway, thank you very much for your help.

**Comment by mojavelinux** [comment]
:+1: Glad to hear it!
