### ISSUE TITLE
IncludeProcessor: clarification of PreprocessorReader.push_include(..)

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctorj#800]
I am trying to implement a custom IncludeProcessor and am trying to figure out how `PreprocessorReader.push_include(..)` is supposed to be used.

https://github.com/asciidoctor/asciidoctorj/blob/9955e3a96a84f8a143435f878ab3f5d347929999/asciidoctorj-api/src/main/java/org/asciidoctor/extension/PreprocessorReader.java#L7-L10

There is some documentation in the Integrator Guide (Include Processors section).
https://github.com/asciidoctor/asciidoctorj/blob/master/docs/integrator-guide.adoc#include-processors

For the `LsIncludeProcessor` example: 

https://github.com/asciidoctor/asciidoctorj/blob/9955e3a96a84f8a143435f878ab3f5d347929999/asciidoctorj-documentation/src/test/java/org/asciidoctor/integrationguide/extension/LsIncludeProcessor.java#L19-L37

The docs says:

> `<4>` Finally the call to the method `push_include` inserts the contents.
> The second and third parameters contain the 'file name' of the include content.
> In our example this will be basically the name `ls` and the path of the current directory.
> The parameter `1` is the line number of the first line of the included content.
> This makes the most sense when partial content is included.

What I got by reading the code.

* In `data` all the file-names that must be included
* In `file` the `target` is passed `"ls"` in this case.
* In `path` the folder absolute path is set
* In `attributes` the attribute parameter of the `process(..)` is passed.

I had also a look at the ruby sources.

https://github.com/asciidoctor/asciidoctor/blob/2dbbb04f6cd3c4728a2e24918814e30d642a6305/lib/asciidoctor/reader.rb#L662-L676

----
My questions:

1) What is expected for the 3 first parameters:

* String `data`
* String `file`
* String `path`

2) Can I call `reader.push_include(..)` multiple times in the same `process(..)` method? 
It seems that it is working as a stack, so I need to start with the included document that I want to have at the end.

----
Related issues:

* https://github.com/asciidoctor/asciidoctorj/issues/672
* https://github.com/asciidoctor/asciidoctorj/issues/770

**Comment by jmini** [comment]
Ok now I understand better how it works.

The first parameter is the raw AsciiDoc content that will be included.

In my opinion it would be better if the `LsIncludeProcessor` would do:

```java
        for (File f: new File(".").listFiles()) {
            sb.append("* `").append(f.getName()).append("`\n");
        }
```

The other parameters (`file`, `path`, `lineNumber`) help asciidoctor to understand what is currently parsed, for example if a warning needs to be reported. Like this:

> WARNING: [filename]: line [lineNumber]: [message]

**Comment by abelsromero** [comment]
Added javadocs in PR https://github.com/asciidoctor/asciidoctorj/pull/1020. I think we can close this issue.
