### ISSUE TITLE
Missing package org.asciidoctor in jar?

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctorj#802]
Follow this link:
http://dl.bintray.com/asciidoctor/maven/org/asciidoctor/asciidoctorj/2.0.0-RC.1/asciidoctorj-2.0.0-RC.1.jar
then open the download in archive manager.
Folder org/asciidoctor contains only jruby
but when I download the source I can see
org.asciidoctor.Asciidoctor.java in folder asciidoctor-api which I expect to see that folder.
Confused...

**Comment by robertpanzer** [comment]
The interface org.asciidoctor.Asciidoctor moves to the asciidoctorj-api module with 2.0.0. 
This is for 2 reasons:
- moving the interface to this module allows alternative implementations like AsciidoctorG which will run asciidoctor.js on GraalVM
- to support running AsciidoctorJ as Java 9+ modules the packages of the jars asciidoctorj-api.jar and asciidoctorj.jar have to be disjoint. 

Already with asciidoctorj 1.6.x we still added asciidoctorj-api as a source for the asciidoctorj javadocs, to allow presenting all docs at a single hosted site. 
I can check if asciidoctorj-api also leaked into the sources as part of this configuration.

**Comment by rockyallen** [comment]
I don't think this is about the package name change.
The documentation says 
"AsciidoctorJ is a standard .jar file. To start using it, you need to add the library to your project’s classpath." 
I did this, but it didn't work, I believe because the jar [asciidoctorj-2.0.0-RC.1.jar] does not contain the org.asciidoctor.Asciidoctor class.
So either the class was accidentally left out of the jar in this build, or the documentation is wrong and you need more than one jar.
Or I am really confused.

**Comment by robertpanzer** [comment]
The documentation is not updated properly yet.
I wasn't fully aware of this sentence and thought that the README only mentioned the use of a Dependency Management solution like Maven or Gradle.

The package name was not changed, but it completely moved into the asciidoctorj-api module, including org.asciidoctor.Asciidoctor.
Only some classes in the package org.asciidoctor that are internal to the JRuby based implementation moved into a different package.
