### ISSUE TITLE
Add support for source highlighters implemented in Java

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#805]
Now that Asciidoctor allows to plug in source highlighters it should also be possible to register Source Highlighters implemented in Java.

Proposal:

To allow registration of a SourceHighlighter the Asciidoctor interface could provide this:

```java
public interface Asciidoctor {
  SourceHighlighterRegistry sourceHighlighterRegistry();
}

public interface SourceHightlighterRegistry {
  public void register(String name, Class<? extends SourceHighlighter> sourceHighlighter);
}

public interface SourceHighlighter {
  Location getDocInfoLocation();
  boolean isHighlight();
  ??? highlight(AbstractBlock node, String lang, Map<String, Object> opts);
  boolean isWriteStylesheet(Document doc); 
  void writeStylesheet(Document doc, String to_dir);
}
```

I am not fully clear yet about the return type of `highlight()`, Java doesn't have native Tuples, the safest bet is probably to create a class with the properties `String highlightedSource` and `int lineOffset`.

Similar to the RubyExtensionRegistry it should also be possible to register a Ruby implementation, that is requiring it and registering it.

**Comment by mojavelinux** [comment]
> the safest bet is probably to create a class with the properties String highlightedSource and int lineOffset.

Yes, that I recommend that.

**Comment by abelsromero** [comment]
I assume this will also be possible with SPI right?

**Comment by mojavelinux** [comment]
It would be exactly the same as converters (however those get registered).

**Comment by abelsromero** [comment]
Checking the interfaces, I see we are being hit but the return type again like in the `PostProcessor`. Non-text formats like PDF won't be supported.

**Comment by mojavelinux** [comment]
The syntax highlighter API is exclusively for HTML outputs.

**Comment by ysb33r** [comment]
> The syntax highlighter API is exclusively for HTML outputs.

I would have hoped that it can be used for special cases like Leanpub as well. So for now we'll have to stick with the workaround that we have

**Comment by mojavelinux** [comment]
That's not exactly what I meant. I should have said "text-based outputs". As an example, we could definitely support Asciidoctor EPUB3.

I'm confused about Leanpub though. Isn't the output Markdown? So why would you want to syntax highlight into Markdown? Or are you still arriving at HTML in the end? If you could clarify, I think we could certainly support it.

**Comment by ysb33r** [comment]
Woth Leanpub the source block has to be cpnverted to a Leanpub-style source block. The callouts have to be extracted and places as a second block below teferring to the line numbers in the source block.

So it is not a syntax highlighter, but it will benefit from the API.

**Comment by ysb33r** [comment]
To illustrate my comments above.

If we start with this Asciidoc

```asciidoc
[source,groovy]
----
@InputFiles  // <1>
FileCollection getDocuments() {
    project.files(this.documents)
}

void setDocuments(Object... docs) {
    this.documents.clear()
    this.documents.addAll(docs as List)
}

void documents(Object... docs) {
    this.documents.addAll(docs as List)
}

private List<Object> documents
----
```

we end with this Leanpub transformation

```markdown
{lang="groovy",linenos="yes"}
~~~~~~~~
@InputFiles
FileCollection getDocuments() {
    project.files(this.documents)
}

void setDocuments(Object... docs) {
    this.documents.clear()
    this.documents.addAll(docs as List)
}

void documents(Object... docs) {
    this.documents.addAll(docs as List)
}

private List<Object> documents
~~~~~~~~

**Line #1:** Create a getter and annotate with `@InputFiles` or `@OutputFiles`. The purpose of the getter is to translate upon access
to a `FileCollection` object.
```

**Comment by mojavelinux** [comment]
> So it is not a syntax highlighter, but it will benefit from the API.

I'm not opposed to this. Like I said, since the output is text, it still conforms.

Where you're going to run into a problem is that core assumes the syntax highlighter is only used for html. (See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/document.rb#L1229) We could find another way to determine what activates it. However, this is a rather deep rooted assumption. Maybe you could set the basebackend to html and it would work out.

**Comment by robertpanzer** [comment]
Support for syntax highlighting is part of AsciidoctorJ now and is also documented at docs.asciidoctor.org.
