### ISSUE TITLE
OptionsBuilder: support for sourcemap

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctorj#808]
From https://asciidoctor.org/docs/user-manual/#ruby-api-options

> `:sourcemap`
> Keeps track of the file and line number for each parsed block. (Useful for tooling applications where the association between the converted output and the source file is important). 
> default value: `false`
> Allowed values: boolean

Unless it is set to `true`, `StructuralNode#getSourceLocation()` returns `null`.

---
There is no support in `OptionsBuilder`.

Is it just missing (in this case I can create a PR to add it), or is there a reason why it is not present?

---
Workaround:
```java
OptionsBuilder.options()
                .option("sourcemap", true)
```

**Comment by mojavelinux** [comment]
Since this option was introduced later than the others, it's likely it just never got added to the AsciidoctorJ API.

**Comment by robertpanzer** [comment]
Yes, I think we can add a dedicated setter for this.
There are already tests that verify that the option is correctly processed.
Then it probably makes even more sense to have a setter for this.

@jmini Would you like to create a PR for this? Otherwise I can also do it.

If I read semver.org correctly this would be a backwards compatible addition to the public API that requires a new minor version, i.e. it has to go into a 2.1.0.

**Comment by jmini** [comment]
> Would you like to create a PR for this? Otherwise I can also do it.

Yes I will be happy to contribute it.

> If I read semver.org correctly this would be a backwards compatible addition to the public API that requires a new minor version, i.e. it has to go into a 2.1.0.

Have you a corresponding branching model?

I guess it would make sense to have a branch where all changes for the next `2.1.0` release can be accumulated.

By the way I have opened issue #810 to investigate semver enforment in the build

**Comment by mojavelinux** [comment]
> I guess it would make sense to have a branch where all changes for the next 2.1.0 release can be accumulated.

The model we're following (at least for core) is that changes for the next minor release go to master. The current minor gets siphoned off to a branch (in this case 2.0.x). I choose this model because I don't like the temptation of letting improvements accumulate on secondary branch because it makes it harder for people to see the activity in the project.

The branch for a minor release line should be created once the "cool off" period is over (a week or two) after a release and the project is ready to start accepting commits that are not just bug fixes. I find that if you branch too soon then you end up having to merge a lot into master despite there not being any other activity.

**Comment by mojavelinux** [comment]
Btw, we're discussing this model here: https://github.com/asciidoctor/asciidoctor/issues/3249

**Comment by jmini** [comment]
I took the [table from the doc](https://asciidoctor.org/docs/user-manual/#ruby-api-options) and I have tried to map the Java method in `OptionsBuilder`:

| Ruby CLI Option          | Description                                                                                                                                                                                                                                                     | Java OptionsBuilder method |
|--------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------|
| :attributes              | Sets additional document attributes, which override equivalently-named attributes defined in the document unless the name or value ends with @. When using the Hash form, a nil value unsets the attribute and a false value soft unsets the attribute.         | attributes(..)             |
| :backend                 | Selects the converter to use (as registered with this keyword).                                                                                                                                                                                                 | backend(String)            |
| :base_dir                | Sets the base (aka working) directory containing the document and resources.                                                                                                                                                                                    | baseDir(File)              |
| :catalog_assets          | If true, tells the parser to capture images and links in the reference table. (Normally only IDs, footnotes and indexterms are included). The reference table is available via the references property on the document AST object. (Experimental).              |                            |
| :converter               | Specifies a user-supplied Asciidoctor::Converter instance, used in place of the converter that is automatically resolved from the backend value.                                                                                                                |                            |
| :doctype                 | Sets the document type.                                                                                                                                                                                                                                         | docType(String)            |
| :eruby                   | Specifies the eRuby implementation to use for executing the converter templates written in ERB.                                                                                                                                                                 |                            |
| :extensions              | A Ruby block that registers (and possibly defines) Asciidoctor extensions for this instance of the processor.                                                                                                                                                   |                            |
| :extensions_registry     | Overrides the extensions registry instance. Instead of providing a Ruby block containing extensions to register, this option lets you replace the extension registry itself, giving you complete control over how extensions are registered for this processor. |                            |
| :header_footer           | If true, add the document header and footer (i.e., framing) around the body content in the output. NOTE: The default value for this option is opposite of the default value for the CLI.                                                                        | headerFooter(boolean)      |
| :mkdirs                  | If true, the processor will create the necessary output directories if they don’t yet exist.                                                                                                                                                                    | mkDirs(boolean)            |
| :parse                   | If true, the source is parsed eagerly (i.e., as soon as the source is passed to the load or load_file API). If false, parsing is deferred until the parse method is explicitly invoked.                                                                         |                            |
| :safe                    | Sets the safe mode.                                                                                                                                                                                                                                             | safe(SafeMode)             |
| :sourcemap               | Keeps track of the file and line number for each parsed block. (Useful for tooling applications where the association between the converted output and the source file is important).                                                                           |                            |
| :template_cache          | If true, enables the built-in cache used by the template converter when reading the source of template files. Only relevant if the :template_dirs option is specified.                                                                                          | templateCache(boolean)     |
| :template_dir            | Specifies a directory of Tilt-compatible templates to be used instead of the default built-in templates. Deprecated. Please use :template_dirs instead.                                                                                                         | templateDir(File)          |
| :template_dirs           | An array of directories containing Tilt-compatible converter templates to be used instead of the default built-in templates.                                                                                                                                    | templateDirs(File...)      |
| :template_engine         | Template engine to use for the custom converter templates. The gem with the same name as the engine will be loaded automatically. This name is also used to build the full path to the custom converter templates.                                              | templateEngine(String)     |
| :template_engine_options | Low-level options passed directly to the template engine.                                                                                                                                                                                                       |                            |
| :timings                 | Capture time taken to read, parse, and convert document. Internal use only.                                                                                                                                                                                     |                            |
| :to_file                 | The name of the output file to write, or true to use the default output file (docname + outfilesuffix).                                                                                                                                                         | toFile(..)                 |
| :to_dir                  | Destination directory for output file(s), relative to base_dir.                                                                                                                                                                                                 | toDir(File)                |

Some of the option are really ruby specific, but maybe more options than just `sourcemap` are missing.

**Comment by mojavelinux** [comment]
The following I believe don't apply for AsciidoctorJ.

* converter - AsciidoctorJ has it's own converter registration mechanism
* eruby - this is just deprecated across the board
* extensions / extensions_registery - AsciidoctorJ has it's own extension registration mechanism
* timings - this one really only applies for the CLI, but could be useful in AsciidoctorJ I suppose

I agree the rest are missing.
