### ISSUE TITLE
AsciidoctorUtils.toAsciidoctorCommand() signature not compatible with paths containing spaces

### ISSUE THREAD

**Issue by Fiouz** [asciidoctor/asciidoctorj#817]
When attempting to build the master branch ([`e348c9a12b54c33fea7b05d70224c007e2ee75a9`](https://github.com/asciidoctor/asciidoctorj/tree/e348c9a12b54c33fea7b05d70224c007e2ee75a9)) in a working directory path that contains a space character, the build fails with
```
java.lang.AssertionError: 
Expected: iterable over ["C:\Some directory\Projects\Asciidoctor\asciidoctorj\asciidoctorj-core\a", "C:\Some directory\Projects\Asciidoctor\asciidoctorj\asciidoctorj-core\b"] in any order
     but: Not matched: "C:\Some"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.asciidoctor.jruby.cli.WhenAsciidoctorAPICallIsCalled.api_parameters_should_be_transformed_to_cli_command(WhenAsciidoctorAPICallIsCalled.java:45)
```

The problems comes from the `AsciidoctorUtils.toAsciidoctorCommand()` method signature https://github.com/asciidoctor/asciidoctorj/blob/e348c9a12b54c33fea7b05d70224c007e2ee75a9/asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/AsciidoctorUtils.java#L39-L40 which, by serializing the command-line into a single String value without escaping, creates a clash between path values and arguments separators.

This causes the test to wrongly assume the space character is only used for delimiting arguments
https://github.com/asciidoctor/asciidoctorj/blob/e348c9a12b54c33fea7b05d70224c007e2ee75a9/asciidoctorj-core/src/test/java/org/asciidoctor/jruby/cli/WhenAsciidoctorAPICallIsCalled.java#L32-L39
At this point, the `parameters` array is incorrectly filled with partial path values.

That assumption triggers the passing of wrong arguments to JCommander https://github.com/asciidoctor/asciidoctorj/blob/e348c9a12b54c33fea7b05d70224c007e2ee75a9/asciidoctorj-core/src/test/java/org/asciidoctor/jruby/cli/WhenAsciidoctorAPICallIsCalled.java#L41-L43 which then causes `asciidoctorCliOptions.getTemplateDir()` to have an unexpected truncated value which breaks the assertion https://github.com/asciidoctor/asciidoctorj/blob/e348c9a12b54c33fea7b05d70224c007e2ee75a9/asciidoctorj-core/src/test/java/org/asciidoctor/jruby/cli/WhenAsciidoctorAPICallIsCalled.java#L45

**Comment by johanhammar** [comment]
Would a solution, where a template path without whitespace is created, be accepted?

Create a path without whitespace based on the current directory

```
String templatePath = new File("").getAbsolutePath().replaceAll("\\s", "");
```

Use the template path when creating the template dirs
```
OptionsBuilder optionsBuilder = OptionsBuilder.options()
                .backend("docbook").templateDirs(new File(templatePath, "a"), new File(templatePath, "b"))
                .safe(SafeMode.UNSAFE).attributes(attributesBuilder.get());
```

Use the template path for the current directory 
```
String currentDirectory = templatePath + File.separator;
```

So that we can assert here
```
assertThat(asciidoctorCliOptions.getTemplateDir(), containsInAnyOrder(currentDirectory+"a", currentDirectory+"b"));
```

Note that I've only tested this on Windows so far.

**Comment by mojavelinux** [comment]
The whole point of this method is to show you what AsciidoctorJ is running. If you change the path, then it defeats the point of the method.

The method could accept an escape argument that would escape the spaces so that it can be copy-pasted verbatim.

**Comment by johanhammar** [comment]
I see. My intention was not to change the path but to control it so it wouldn't contain spaces when setting the templateDirs. I'll see if I can do something using an escape argument.

Thanks for the quick response!
