### ISSUE TITLE
Implement -R in the CLI

### ISSUE THREAD

**Issue by rockyallen** [asciidoctor/asciidoctorj#818]
In the Ruby CLI, -R in conjuntion with -D allows multiple file (ie **/*.adoc) conversion, retaining the folder structure. It should be the same in asciidoctorj.

**Comment by ysb33r** [comment]
Thank you @4lber10 for contributing this fix.

**Comment by robertpanzer** [comment]
I guess this is resolved as the PR was merged, right?
Will be fixed in 2.1.0

**Comment by alshain** [comment]
Thanks a lot, looking forward to this!
