### ISSUE TITLE
problem with uber jar

### ISSUE THREAD

**Issue by JurrianFahner** [asciidoctor/asciidoctorj#820]
When adding the following to the pom.xml:

```xml
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj-api</artifactId>
            <version>2.0.0</version>
        </dependency>
```

It will run and functionally well until the application is package as an uberjar. Which is commonly the case with spring-boot when building with `mvn package`. 

If I run the jar I get the following stacktrace:
```
Caused by: org.jruby.exceptions.LoadError: (LoadError) no such file to load -- asciidoctor
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:987) ~[jruby-core-9.2.7.0.jar!/:na]
	at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54) ~[na:na]
	at RUBY.<main>(<script>:12) ~[na:na]
```

To circumvent this problem a work around is extracting the jar and run it directly.

**Comment by abelsromero** [comment]
SpringBoot uses a custom packaging system that does not work well with jRuby (https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/#packaging-executable-configuring-unpacking).

If you are using maven, the plugin also has the same `requiresUnpackage` option https://docs.spring.io/spring-boot/docs/current/maven-plugin/repackage-mojo.html.

Disclaimer: there's an open issue similar to these one, so it could be something else is going on https://github.com/asciidoctor/asciidoctorj/issues/666

**Comment by htmfilho** [comment]
I'm facing the same issue in a SpringBoot application - htmfilho/digger#14 . I'm trying to repackage it with the following SpringBoot Maven Plugin configuration:

    <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <executions>
            <execution>
                <id>repackage</id>
                <goals>
                    <goal>repackage</goal>
                </goals>
                <configuration>
                    <requiresUnpack>
                        <dependency>
                            <groupId>org.jruby</groupId>
                            <artifactId>jruby-core</artifactId>
                        </dependency>
                    </requiresUnpack>
                </configuration>
            </execution>
        </executions>
    </plugin>

It didn't work. I'm trying other dependencies, but no success yet. If you happen to know exactly the impacted dependencies, it would be helpful.

Thank you very much in advance.

**Comment by htmfilho** [comment]
Problem solved unpacking asciidoctorj:

    ...
    <requiresUnpack>
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj</artifactId>
        </dependency>
    </requiresUnpack>
    ...

Ref.: https://github.com/htmfilho/digger/blob/master/pom.xml

**Comment by robertpanzer** [comment]
The repository now contains an example showing how to package AsciidoctorJ in a Spring Boot application.
Kudos to @abelsromero for that!
