### ISSUE TITLE
2.0.0: InlineMacroProcessor returning a String

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctorj#821]
Inspired by the Ruby Test suite, the java implementation for the “say” macro (usage `say:yo[]`) could be an `InlineMacroProcessor` like this:

```java
public class SayMacroProcessor extends InlineMacroProcessor {

    public SayMacroProcessor(String macroName, Map<String, Object> config) {
        super(macroName, config);
    }

    @Override
    public Object process(ContentNode parent, String target, Map<String, Object> attributes) {
        return target;
    }
}
```

This was valid with earlier version of Asciidoctor/AsciidoctorJ.

Due to the change introduced in `2.0.0.rc.3` returning a String is no longer the expected way to do this. 
A INFO log entry is raised:
```
INFO: expected substitution value for custom inline macro to be of type Inline; got String: say:yo[]
```

See the corresponding code in [substitutors.rb lines 333-343](https://github.com/asciidoctor/asciidoctor/blob/66ae48db19fc8f7d17df78a67e9b1208014f9de8/lib/asciidoctor/substitutors.rb#L333-L343).

---
All example in this repository of macro extending `InlineMacroProcessor` are calling `createPhraseNode(..)`

https://github.com/asciidoctor/asciidoctorj/blob/45857eccb6ae90f5e41b9f41c73cf47dbc87f670/asciidoctorj-core/src/test/java/org/asciidoctor/extension/ManpageMacro.java#L19-L26

But I did not find the way to return an `Inline` that contains just some text as `String`.

I have tried:

```java
return createPhraseNode(parent, "text", target, attributes, options);
```

But this creates an Error:

```
org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `convert_inline_text' for #<Asciidoctor::Converter::Html5Converter:0x10b4e7f8>
Did you mean?  convert_inline_button
               convert_inline_quoted
               convert_inline_menu
               convert_inline_image
               convert_inline_break
               convert_inline_kbd
```

Can you tell me what I should use?

I think the [Migrating from AsciidoctorJ 1.6.x to 2.0.x](https://github.com/asciidoctor/asciidoctorj/blob/master/docs/extension-migration-guide.adoc#migrating-from-asciidoctorj-16x-to-20x) section could be extended. I am ready to help when I know how to solve this.

**Comment by robertpanzer** [comment]
Oh yes, looks like I screwed this.
I remember that I was seeing the return type Object before heading for the 2.0.0 release and changed it.

I think `"quoted"` should be the closest to what you want.

Thinking about the API I think it is not very nice to have a return type of Object.
Just as I stumbled over it everyone else will either.
Too bad there are no sum types or at least an Either type available in the Java platform.

Thinking about the impact, it should probably be possible to fix it in a backward compatible way. 
Existing InlineMacro extensions that return a PhraseNode should be allowed to implement a method that returns Object.

**Comment by robertpanzer** [comment]
Oh I see, I didn't change the signature of the method, instead Asciidoctor Core now expects a PhraseNode.
Is that what you mean?
In that case we should probably change the signature to make `process()` return a `PhraseNode`.
And that means this issue rather belongs into Asciidoctor Core, or AsciidoctorJ should at least enhance the documentation.

**Comment by jmini** [comment]
In this project I will propose a PR with:

* Update the examples/tests and docs so that a `String` is no longer returned (appending `.convert()` is no longer necessary) 
* Add a section to "Migrating from AsciidoctorJ 1.6.x to 2.0.x"

----
I think that as long as the ruby core can still handle "String", we should let the Java signature the way it is.
If people look at the INFO log, they will know they need to return an `Inline` instead of a `String`.

----
Using:
```java
return createPhraseNode(parent, "quoted", target, attributes, new HashMap<>());
````

Is the solution.

**Comment by jmini** [comment]
See PR #823

**Comment by mojavelinux** [comment]
To be clear, it's not technically broken. It just issues a deprecation warning. So this is the right move forward.
