### ISSUE TITLE
Undiscoverable CLI version

### ISSUE THREAD

**Issue by alshain** [asciidoctor/asciidoctorj#827]
It seems to me that the CLI version isn't advertised enough in the readme. Is that a conscious decision to promote the gradle and maven based converters instead?

The CLI version is the most simple thing to get started and just play around with asciidoctor. 

It would be nice if the `-bin` artifacts were also mentioned in the readme, not just within the context of chocolatey.

**Comment by robertpanzer** [comment]
Agreed. Would make sense to list the `asciidoctorj-bin.zip` in the Distributions section.

**Comment by mojavelinux** [comment]
@alshain More like a legacy docs issue, since the README and library predated the CLI.

**Comment by alshain** [comment]
Cool, I'll submit a PR soon to address this.

**Comment by mojavelinux** [comment]
Thanks!

**Comment by abelsromero** [comment]
Closing, bin/cli package is mentioned in current READMe and in the new docs https://docs.asciidoctor.org/asciidoctorj/latest/cli/.
