### ISSUE TITLE
Make -R the default in the CLI

### ISSUE THREAD

**Issue by alshain** [asciidoctor/asciidoctorj#828]
I realize changing defaults is a dangerous road, but I'm a big believer in things should "just work".

However, considering `asciidoctorj "**/*.adoc -D build"` will output all files into the same directory structure, relative links to images, other articles etc will all stop working unless the author deliberately places the files into directories but wrote all links as if the adoc files were inside the same directory.

I had only discovered that files in subdirectories weren't processed "properly" (i.e. as expected) after our documentation grew into actually using subfolders.

Thoughts?

**Comment by abelsromero** [comment]
For building whole directories, specially if you want to process resources and ensure the target directory contains everything, I recommend using a build tool which better covers such use cases. If you are feel more comfortable in Java you can use the [maven-plugin](https://github.com/asciidoctor/asciidoctor-maven-plugin) or the [gradle-plugin](https://github.com/asciidoctor/asciidoctor-gradle-plugin).

**Comment by mojavelinux** [comment]
Though, to @alshain's point, this is supported in the Ruby version of the CLI: https://github.com/asciidoctor/asciidoctor/issues/1394#issuecomment-331357310. It's not (and should not be) the default. You do have to specify it for reasons I cited in that comment.

Currently, `-R` isn't supported by the asciidoctorj command as far as I can tell. If it were, the command would be:

```
asciidoctorj -R . "**/*.adoc -D build
```

I agree with @abelsromero that are limits to what the CLI can and should handle and you should consider a build tool once you cross that limit.

**Comment by alshain** [comment]
It will be supported in the next release in asciidoctorj as well: #818 

I just think the default should do what the user expects. A user does not expect that the glob will find files in subdirectories but not preserve the folder structure. What's the benefit of having asciidoctorj do that by default if the user specifies a glob and an output directory?

**Comment by mojavelinux** [comment]
It's not the default because we don't all agree on what the user expects.
As I pointed out, you need to be explicit. And, frankly, that's a good
thing.

**Comment by mojavelinux** [comment]
If you feel very strongly there is another path forward you'll need to:

1. work upstream in Asciidoctor Ruby (since AsciidoctorJ needs to stay in alignment with Asciidoctor Ruby)
2. propose a flag that would flatten the output
3. implement the changes and test them

;)

**Comment by mojavelinux** [comment]
I added some docs to the user manual about the -R flag.

https://asciidoctor.org/docs/user-manual/#process-multiple-source-files-from-the-cli (see end of section)

As I was writing those docs, it did occur to me that using `-D` and not using `-D` in some respects produces different results. Having thought about it more, I am more open to the idea. But we still need some sort of "flatten" flag so that the existing behavior can still be achieved.

My offer still stands.

**Comment by mojavelinux** [comment]
zip uses `--junk-paths`. yarn uses `--flat`. I'm thinking perhaps `--flatten-path` (or `--flatten-paths`). rsync uses `--no-R` (which is a strange convention).

**Comment by robertpanzer** [comment]
I think it's safe to close this ticket.
`-R` is a supported option now, and a user can set it when needing it.
