### ISSUE TITLE
asciidoctorj-api v2.1.0 not available in central

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#829]
Asciidoctorj v 2.1.0 points to asciidoctorj-api 2.1.0 which does not seem to be available in maven central https://search.maven.org/search?q=g:org.asciidoctor

**Comment by slonopotamus** [comment]
To be more exact, it wasn't deployed to jcenter: https://jcenter.bintray.com/org/asciidoctor/asciidoctorj-api/

**Comment by slonopotamus** [comment]
Possibly that's because Travis build for 2.1.0 tag has failed? https://travis-ci.org/asciidoctor/asciidoctorj/builds/549145634

**Comment by robertpanzer** [comment]
I forgot to upload asciidoctorj-api.
It is on bintray now and should hit Maven central soon.

**Comment by slonopotamus** [comment]
@robertpanzer: have you thought about automating release procedure using Gradle+Travis? I could provide some assist with it.

[Here's](https://github.com/bozaro/git-lfs-java/blob/master/build.gradle.kts) a multi-module Gradle project that publishes to Maven repository (including signing, if you want to). A cool feature is that publication is atomic, either all modules publish or build fails and nothing gets into repository.

**Comment by abelsromero** [comment]
It's working now :smile:

**Comment by robertpanzer** [comment]
@slonopotamus I didn't do that yet for two reasons:
1. Simply lack of time
2. I am not sure if I really trust travis-ci enough to give it my private pgp key that is required to sign the artifacts.

**Comment by robertpanzer** [comment]
Closing the ticket for now as I guess the original issue is resolved.
Don't hesitate to open a new one if you'd like to continue the discussion about releasing from Travis.
