### ISSUE TITLE
[CLI] java.lang.ClassNotFoundException: org.asciidoctor.cli.AsciidoctorInvoker

### ISSUE THREAD

**Issue by anb0s** [asciidoctor/asciidoctorj#831]
I'm new with asciidoctorj and want to use it as CLI tool with "java -jar asciidoc.jar". So it does not work. Also with the "org.asciidoctor.cli.AsciidoctorInvoker" it shows "java.lang.ClassNotFoundException: org.asciidoctor.cli.AsciidoctorInvoker".

**Comment by anb0s** [comment]
Is there some info about how to use asciidocj CLI in ANT?

**Comment by robertpanzer** [comment]
> Is there some info about how to use asciidocj CLI in ANT?

There is https://github.com/asciidoctor/asciidoctor-ant, but I guess it is not aligned with asciidoctorj 2.x.x yet.
You will have the best experience with the asciidoctor maven plugin and the asciidoctor cradle plugin, but if you are forced to use ant, I can't tell right now if it works.

**Comment by mojavelinux** [comment]
Yes, asciidoctor-ant is well maintained by @binout. It doesn't use the CLI, it's a regular Ant task. You're right, though, that it hasn't made the jump to AsciidoctorJ 2 yet. I'm sure he'd welcome assistance.

**Comment by anb0s** [comment]
Thanks, we do not have Maven and no Gradle supported yet in company, only ANT (JVM) and Python.
So i'm using AsciidoctorJ 2.1.0 CLI from ANT now for testing.

I've created issue for this: https://github.com/asciidoctor/asciidoctor-ant/issues/76

**Comment by binout** [comment]
Hi @anb0s
I missed the release train of asciidoctor 2.0 😅
I will try to catch up with him in the coming weeks 💪

**Comment by robertpanzer** [comment]
The ticket can be closed from this repo as it's rather related to the asciidoctor-ant plugin.
