### ISSUE TITLE
Include logger name for java util log handler

### ISSUE THREAD

**Issue by lread** [asciidoctor/asciidoctorj#833]
**Current behavior**
I am using [logback](https://logback.qos.ch/) in my application and [a bridge handler](https://www.slf4j.org/api/org/slf4j/bridge/SLF4JBridgeHandler.html) so that JUL (java.util.logging) messages are logged.

As is common in a java application, my logging pattern includes the logger name.  For log messages from asciidoc, I get `unknown.jul.logger` as the logger name for log messages from asciidoc.

**Preferred behavior**
After a look at the asciidoctorj code, I only one logger named `asciidoctor`.  
It would be nice if I saw `asciidoctor` in my logs rather than `unknown.jul.logger`.

**Action**
I've tested a fix locally for this will be happy to submit a PR.

**Comment by robertpanzer** [comment]
Hi Lee!

Thank you! 
Interesting, I thought that logging a LogRecord would use its name like all other log methods do.
Just saw in the sources that this is apparently not the case.
It would be great if you could provide a PR.

**Comment by lread** [comment]
You are most welcome, thanks for all the hard work on asciidoctor!
