### ISSUE TITLE
LogHandler errors not protected in `AbstractConverter`

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#842]
While messing with a LogHandler I noticed that exceptions in `JRubyAsciidoctor` are protected with a try-catch.

```java
    @Override
    public void log(LogRecord logRecord) {
        for (LogHandler logHandler : logHandlers) {
            try {
                logHandler.log(logRecord);
            } catch (Exception e) {
                LOGGER.log(Level.WARNING, "Unexpected exception while logging Asciidoctor log entry", e);
            }
        }
    }
```

However, this is not the case for `AbstractConverter`, which just has 

```java
    @Override
    public void log(LogRecord logRecord) {
        if (logHandler != null) {
            logHandler.log(logRecord);
        }
    }
```

Is this on purpose?

**Comment by abelsromero** [comment]
Also, I'd like to be able to abort the conversion of a document from a LogHandler based on certain messages. That means that the fact that exceptions are protected kind of leaves me without options here.

**Comment by robertpanzer** [comment]
I agree, the call of the Loggers should not be protected against exceptions.

**Comment by abelsromero** [comment]
While it's convenient I don't want to just too quick. What the original behavior of asciidoctor in case of logger exception? I could not find any docs :/

**Comment by mojavelinux** [comment]
There's no relationship between the logger and exception handling in core. A log message is just a message to the user. If you then want to raise an exception, the result should be just like any other code. Nothing special.

**Comment by abelsromero** [comment]
Do you think it makes sense to remove the protection then? I tested it locally to see if it worked fine to fail a maven build and it worked. I can send the PR.

**Comment by robertpanzer** [comment]
Yes, that would be awesome!
