### ISSUE TITLE
No warnings when running CLI

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#845]
While testing #841 I realized that I didn’t see the warnings for unknown block type when converting a document with a plantuml Block but without requiring the asciidoctor-diagram gem. 
I would have expected to see this. 
Check why this message did not show up.

**Comment by abelsromero** [comment]
I tested versions 2.0.0, 2.1.0 & master branch with https://github.com/asciidoctor/asciidoctor-maven-examples/tree/master/asciidoctor-diagram-example comenting the <require>, and DO get the message as DEBUG.
Not sure this is a bug or I am missing something.

```
[INFO] --- asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc (generate-html-doc) @ asciidoctor-diagram-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] asciidoctor: DEBUG: example-manual.adoc: line 17: unknown style for literal block: ditaa
[INFO] asciidoctor: DEBUG: example-manual.adoc: line 37: unknown style for literal block: plantuml
[INFO] asciidoctor: DEBUG: example-manual.adoc: line 46: unknown style for listing block: graphviz
[INFO] Rendered /home/asalgadr/github/asciidoctor-maven-examples/asciidoctor-diagram-example/src/docs/asciidoc/example-manual.adoc

```

**Comment by robertpanzer** [comment]
Thanks for checking this @abelsromero!
It seems like there is sth wrong in the mapping of the log levels.

**Comment by abelsromero** [comment]
I still don't follow, I don't see any issue. I run the same doc in the ruby cli (2.0.10) and got the same result:

```
[----@---- asciidoc] (master)
$ asciidoctor -v example-manual.adoc
asciidoctor: DEBUG: example-manual.adoc: line 17: unknown style for literal block: ditaa
asciidoctor: DEBUG: example-manual.adoc: line 37: unknown style for literal block: plantuml
asciidoctor: DEBUG: example-manual.adoc: line 46: unknown style for listing block: graphviz
```

Just in case, don't get confused by the `[INFO]` that's the maven log level to where asciidoctor messages are redirected.

**Comment by robertpanzer** [comment]
I just would have expected this to be a warning. 
I never tested this with asciidoctorj but I remember seeing an error message when running asciidoctor from the CLI and I forgot to require asciidoctor-diagram. 
Maybe it really works as expected but I was definitely surprised not seeing it.

**Comment by robertpanzer** [comment]
Just retested with the asciidoctor Ruby CLI and indeed the messages have the log level debug.
Looks like I was chasing ghosts.

**Comment by abelsromero** [comment]
Well, according to the definition of WARNING in the manual https://asciidoctor.org/docs/user-manual/#app-messages

**WARNING**
*Warnings do not stop conversion, but they indicate possible problems, and the output may not be what you were expecting.*

Maybe you are right and should be WARNING. wdyt @mojavelinux ?
