### ISSUE TITLE
Destination directory ignored in Asciidoctorj

### ISSUE THREAD

**Issue by ccleve** [asciidoctor/asciidoctorj#853]
In Java:

```
Options options = new Options();
options.setDestinationDir("../foo/");
asciidoctor.convertFile(new File("./docs/userguide.adoc"), options);
```

Does not place the output in ../foo. It produces it in-place.

If I add `options.setInPlace(false);` it has no effect.

I'm using Asciidoctorj 2.1.0.

**Comment by robertpanzer** [comment]
It looks like the `destination_dir` option is only evaluated by the Asciidoctor CLI which puts the value into the `to_dir` option.
Using `options.setToDir("../foo")` seems to do the trick.
Also please set the safe mode to avoid security errors.

**Comment by adaussy** [comment]
Yes I can confirm that `options.setInPlace(false)` seems to be broken in 2.1.0

**Comment by hoxu** [comment]
Would be nice if this was documented in the README.

**Comment by abelsromero** [comment]
I'm nore inclined to understand what should be the expected behauviour and if it makes sense to keep that if the same can be achieved with another option.

/cc @mojavelinux any suggestion for this one and https://github.com/asciidoctor/asciidoctorj/issues/941?

**Comment by mojavelinux** [comment]
It seems like there are two options, one of which is ignored. I would pick one and deprecate the other. And, according to Robert, `options.setToDir("../foo")` is the one that works. So perhaps stick with that one.

The `:to_dir` option is documented here: https://asciidoctor.org/docs/user-manual/#ruby-api-options

The Ruby API has no `:destination_dir` option.

**Comment by robertpanzer** [comment]
Agreed.
I am not sure right now how that method made it into AsciidoctorJ.
A fix would be to "redirect" it to the same option that the Asciidoctor and AsciidoctorJ CLI do.

But as Asciidoctor also does not seem to support this option via the API, I think it would be best to not "fix" this in AsciidoctorJ, but instead keep the current – admittedly useless – behavior, and tell users to use the `toDir` option (and `sourceDir`which is also set by the AsciidoctorJ CLI right now)
