### ISSUE TITLE
CLI does not support reading input from STDIN

### ISSUE THREAD

**Issue by nicerloop** [asciidoctor/asciidoctorj#865]
The corresponding code in commented out in AsciidoctorInvoker.java due to JCommander inability to handle '-' as a parameter. JCommander limitation lifted by newer version already included in master.

**Comment by AlexCzar** [comment]
is there a workaround for 2.5.4, which I understand is the latest release?

**Comment by robertpanzer** [comment]
Are you saying that you are still facing this issue with the latest version?
The latest is 2.5.5, but 2.5.4 should be fine too.

**Comment by AlexCzar** [comment]
Yep, the same issue on 2.5.4, I don't have 2.5.5, I haven't had the time to investigate how to install it without sdkman.

**Comment by abelsromero** [comment]
Hi :wave: What OS is it?

**Comment by robertpanzer** [comment]
I can reproduce in OSX. 
It generates the output and dumps it to stdout, but also throws an exception.

**Comment by robertpanzer** [comment]
This is a new issue. I'll create another ticket for it.
