### ISSUE TITLE
[question] What happened to the Asciidoctor.Factory.create() method with List<String> argument?

### ISSUE THREAD

**Issue by jasal82** [asciidoctor/asciidoctorj#873]
It seems that the function is no longer there in AsciidoctorJ 2.1.0. How do I create an instance in OSGi environment now?

**Comment by robertpanzer** [comment]
These methods that assume that there is a Ruby based implementation were removed from the base API with AsciidoctorJ 2.0.0.

Please use AsciidoctorJRuby.Factory.create() instead if you need to set JRuby specific options: https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-core/src/main/java/org/asciidoctor/jruby/AsciidoctorJRuby.java

**Comment by jasal82** [comment]
Thanks!
