### ISSUE TITLE
Removed AsciiDoctor.Factory.create() Overloads still in documentation

### ISSUE THREAD

**Issue by ijt-fr** [asciidoctor/asciidoctorj#879]
The overload for AsciiDoctor.Factory.create() where the gem path could be provided was removed in commit d2209e2e7bb2e5a6d0c6cac25bcbb8053180a969. The documentation file integrator-guide.adoc still talks about this overload as if it exists. This overload should be added back in or the documentation updated to reflect the new functionality.

**Comment by abelsromero** [comment]
This can be closed, the references to the String method point correctly to `AsciidoctorJRuby.Factory`.

* https://github.com/asciidoctor/asciidoctorj/blob/master/docs/modules/ROOT/pages/asciidoctor-interface.adoc
* https://github.com/asciidoctor/asciidoctorj/blob/master/docs/modules/guides/pages/gem-path.adoc

**Comment by robertpanzer** [comment]
Thanks for working through the issues!
