### ISSUE TITLE
Updating from 1.6.X to 2.X breaks due to change of method create

### ISSUE THREAD

**Issue by SElab2019** [asciidoctor/asciidoctorj#887]
When I try to upgrade asciidoctorj from 1.6.X to version 2.X.  The following code also breaks due to the change of method create. The issue starts from the version 1.7.0-RC.1. 

```
public class Demo {
	
    public void run() {
		Asciidoctor doctor = Asciidoctor.Factory.create(Arrays.asList(
		        "gems/asciidoctor-1.5.2/lib",
		        "gems/coderay-1.1.0/lib",
		        "META-INF/jruby.home/lib/ruby/1.9"));
    }

}
```

It throws an error:
```
Demo.java:[14,42] error: method create in class Factory cannot be applied to given types;
```

**Comment by robertpanzer** [comment]
With Asciidoctor 2.x.x the API was split into a "core" part that is independent of JRuby, and another part that is dependent on JRuby.
As such the functionality to get an Asciidoctor instance using a certain gem path moved into the JRuby specific part and has to be done now like this:
```java
Asciidoctor doctor = org.asciidoctor.jruby.AsciidoctorJRuby.Factory.create(Arrays.asList(
		        "gems/asciidoctor-1.5.2/lib",
		        "gems/coderay-1.1.0/lib",
		        "META-INF/jruby.home/lib/ruby/1.9"));
```

That said unless you are using other directories in your gempath I don't think that your concrete example will work.
I don't know your actual use case, so I can't say much about it, but AsciidoctorJ > 2.0.0 should also require Asciidoctor core >= 2.0.0.

If you just want to just convert documents the simple create() should already do it:
```java
Asciidoctor doctor = org.asciidoctor.Asciidoctor.Factory.create();
```

**Comment by robertpanzer** [comment]
I want to update the documentation to fix this, but I did not find the time yet.
There have been just too many curveballs recently.

**Comment by robertpanzer** [comment]
I updated the docs in #891 to clarify how to create an Asciidoctor instance with a gem path.
Therefore I am going to close this issue.
The decision to move these factory methods into another class is a preparation for other implementations that do not use Asciidoctor with JRuby, but for example asciidoctor.js, where things like a gem path don't make sense.
