### ISSUE TITLE
New in 2.2.0: Unable to find an implementation of Asciidoctor in the classpath

### ISSUE THREAD

**Issue by iovuio** [asciidoctor/asciidoctorj#892]
Worked well in 2.1.0
Fails in 2.2.0

**Suggested steps to reproduce**
1. Open maven project in attachment.
2. Run `com.mycompany.Main` class. -> Runs successfully, as expected.
3. Edit file `pom.xml`. 
 Uncomment line 17.
 Comment line 19.
4. Run `com.mycompany.Main` class again.

**Expected result**
Successful conversion from adoc to html.

**Actual result**
Exception thrown:
Exception in thread "main" java.lang.RuntimeException: Unable to find an implementation of Asciidoctor in the classpath (using ServiceLoader)
	at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:500)

[project.zip](https://github.com/asciidoctor/asciidoctorj/files/4014357/project.zip)

**Comment by robertpanzer** [comment]
I tried your example but cannot really reproduce.
How did you run the class and how did you set the class path?
Running it with the Maven exec plugin worked for me:
```console
$ mvn exec:java -Dexec.mainClass="com.mycompany.Main"
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.mycompany:adrj-2.2.0-error >-------------------
[INFO] Building adrj-2.2.0-error 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj/2.2.0/asciidoctorj-2.2.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj/2.2.0/asciidoctorj-2.2.0.pom (2.6 kB at 4.7 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj-api/2.2.0/asciidoctorj-api-2.2.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj-api/2.2.0/asciidoctorj-api-2.2.0.pom (1.9 kB at 30 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj/2.2.0/asciidoctorj-2.2.0.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj-api/2.2.0/asciidoctorj-api-2.2.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj-api/2.2.0/asciidoctorj-api-2.2.0.jar (60 kB at 188 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj/2.2.0/asciidoctorj-2.2.0.jar (1.7 MB at 3.4 MB/s)
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ adrj-2.2.0-error ---
html is: <div class="paragraph">
<p>this is some text</p>
</div>
```

**Comment by iovuio** [comment]
@robertpanzer thank you for your prompt reply.

I now ran it clean with `mvn:exec` and could not reproduce anymore.
Originally the issue occurred when executed from IntelliJ (please see attachment for command it ran)

For some reason, as I ran `mvn:exec` it downloaded 2.2.0 and all its dependencies again.
After that, cannot reproduce in either the project provided, nor in the project I originally spotted the problem in.

I suspect IntelliJ messed up the 2.2.0 jar. 
Going forward I intend to run `mvn:exec` before logging issues.


[commandlne.txt](https://github.com/asciidoctor/asciidoctorj/files/4016770/commandlne.txt)
