### ISSUE TITLE
Update rubygems-proxy to official URL

### ISSUE THREAD

**Issue by headius** [asciidoctor/asciidoctorj#896]
This issue is filed because you have code referencing a deprecated RubyGems-to-Maven proxy server: rubygems-proxy.torquebox.org. The JRuby team has decided to officially support this proxy at a new official address: mavengems.jruby.org.

Please update your links, as the torquebox.org hostname will eventually be shut down.

Thank you from the JRuby and Torquebox teams!

Found references:

* https://github.com/asciidoctor/asciidoctorj/blob/44a599b0913e1ae696d6a0b21728c7bdff665008/asciidoctor-gem-installer.pom
* https://github.com/asciidoctor/asciidoctorj/blob/44a599b0913e1ae696d6a0b21728c7bdff665008/asciidoctor-pdf-gem-installer.pom

**Comment by robertpanzer** [comment]
We moved from torquebox with https://github.com/asciidoctor/asciidoctorj/pull/884
