### ISSUE TITLE
Diferent versions of `rouge`gem packaged in asciidoctorj and asciidoctorj-pdf

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#899]
I think that just to avoid possible issues both versions should be aligned.

- asciidoctorj 2.2.0 uses 3.12
- asciidocotrj-pdf 1.5.9-rc.2 uses 3.14

**Comment by mojavelinux** [comment]
Ideally, the asciidoctorj-pdf jar wouldn't bundle rouge. It should load it from asciidoctorj (if that's possible).

**Comment by robertpanzer** [comment]
That's of course possible.
The reason for having rouge in asciidoctorj-pdf is historical.
asciidoctorj-pdf is currently still built against asciidoctorj 1.5.8.1 and iirc at that time asciidoctorj did not support rouge in the html converter.
And asciidoctor-pdf also states that it runs with asciidoctor 1.5.3.

So how should we handle this?
Remove rouge from asciidoctorj-pdf in the next release and therefore drop support for it for users that still run on 1.5.x?
Or should we state that asciidoctorj-pdf only works properly with asciidoctorj 2.x?

I am open to any alternative, we should just be prepared that either way would hurt some people.

**Comment by mojavelinux** [comment]
This would be a good change to make in AsciidoctorJ PDF 2.0.0. Once 1.5.0 is out, 2.0.0 should soon follow, so it won't be long from now. And like other projects have done, Asciidoctor PDF 2.0.0 will require at least Asciidoctor 2.

**Comment by abelsromero** [comment]
We can continue the work on https://github.com/asciidoctor/asciidoctorj-pdf/issues/87
