### ISSUE TITLE
asccidoctorj logs multiple "possible invalid reference"

### ISSUE THREAD

**Issue by bric3** [asciidoctor/asciidoctorj#901]
I've setup a project that uses asciidoctor-gradle-plugin 3.1.0. And I always get these INFO / warning log messages. I'm not sure those are actual warnings.

```
> Task :asciidoctor
Jan 30, 2020 3:30:48 PM uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/substitutors.rb sub_macros
INFO: possible invalid reference: numbered
Jan 30, 2020 3:30:48 PM uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/substitutors.rb sub_macros
INFO: possible invalid reference: first
Jan 30, 2020 3:30:48 PM uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/substitutors.rb sub_macros
INFO: possible invalid reference: purpose
Jan 30, 2020 3:30:48 PM uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/substitutors.rb sub_macros
INFO: possible invalid reference: another_term
```

Here's the setup, I'm using Gradle 6.1.1. As far as I understand asciidoctorj to 2.2.0 still packages the 2.0.10 gem lib.

```gradle
plugins {
    id 'org.asciidoctor.jvm.convert' version '3.1.0'
}

repositories {
    jcenter()
}

asciidoctor {
    asciidoctorj {
        version '2.2.0'
        modules.diagram.version '2.0.1'
        options doctype: 'book', ruby: 'erubis'
    }

    resources {
        from(sourceDir) {
            include 'images/**'
            include '*.css'
            include 'js/**'
        }
    }

    sources {
        include 'demo.adoc'
    }
    baseDirFollowsSourceDir()

    inputs.files("${sourceDir}/*.css")
    inputs.dir("${sourceDir}/js")
}
```

**Comment by bric3** [comment]
The only similar issue I've seen is there : https://gitter.im/asciidoctor/asciidoctor?at=5d2b58f63b41924785bb0413

After searching I noticed this commit https://github.com/asciidoctor/asciidoctorj/commit/a04f2cf074a0a45fdb90bff91086b301037a041a which forces the logging to verbose, which is probably why I'm seeing those logs in the first place.

The document I'm converting has the references that are being complained about : 

```adoc
[[numbered]]
.Bullet points
. one
. two

[[purpose]]
.Purpose of the tool
****
...
****

[[another_term]]aka::
...

Then reference to <<numbered>> ...

[[first,First Contact]]
== First Contact

Later ... xref:first[] with this <<purpose,Purpose>>.

<<another_term>>
```

**Comment by bric3** [comment]
After seeing this [file](https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/ca89250ef2ae989202f04e255adc6c4175bfc5da/jvm/src/main/groovy/org/asciidoctor/gradle/remote/ExecutorBase.groovy) (asciidoctor-gradle-plugin 3) and this [one](https://github.com/asciidoctor/asciidoctorj/blob/b694e023ff2e726e2d6aa7fb4344d10815c259e2/asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorInvoker.java) I wonder if this is something that is missing onthe gradle plugin.

**Comment by mojavelinux** [comment]
> And I always get these INFO / warning log messages. 

The problems were always there. Asciidoctor 2 just tells you about them now.

**Comment by mojavelinux** [comment]
If I try your sample with Asciidoctor core 2.0.11, I don't see any warnings.

```
asciidoctor -w -v test.adoc
```

**Comment by mojavelinux** [comment]
Your document must be running in compat mode somehow:

```
asciidoctor -v -a compat-mode test.adoc
asciidoctor: INFO: possible invalid reference: numbered
asciidoctor: INFO: possible invalid reference: first
asciidoctor: INFO: possible invalid reference: purpose
asciidoctor: INFO: possible invalid reference: another_term
```

But these shouldn't be warnings. I'll look into it.

**Comment by mojavelinux** [comment]
Yep, that's a bug in the compat mode logic. The condition is reversed. A valid reference is being logged as an invalid reference. Oops. I'll fix in 2.0.11.

**Comment by bric3** [comment]
thanks

**Comment by sgarfinkel** [comment]
@mojavelinux To clarify, is this an actual issue or can I just ignore it. Encountering the same problem, I assume due to using `:sectlinks:`

**Comment by mojavelinux** [comment]
@sgarfinkel I'd have to see your document to know for sure, but likely these are warnings due to the inverted condition. A fix has been made to the master branch and will be included in the 2.0.11 release.

> I assume due to using :sectlinks:

This has nothing to do with sectlinks. That's a setting that affects how section titles are displayed.

**Comment by sgarfinkel** [comment]
Yes, I should have edited my original comment, I was getting a similar warning but it was actually a bug in my asciidoc due to a _actual_ invalid references.

**Comment by robertpanzer** [comment]
This issue seems to be normal behavior if I understand correctly and is not directly related to AsciidoctorJ.

**Comment by mojavelinux** [comment]
..and it was fixed in Asciidoctor core. See https://github.com/asciidoctor/asciidoctor/issues/3555
