### ISSUE TITLE
Automatically handle include macro attributes when using custom IncludeProcessor

### ISSUE THREAD

**Issue by cjbrooks12** [asciidoctor/asciidoctorj#903]
This might be a question that needs to be addressed on the main Asciidoctor repo, but since I am only using Asciidoctorj and am not sure if this behavior is the same on the Ruby-side, I'm posting it here first.

Is it possible to create a custom `IncludeProcessor`, but still let the Asciidoctor library handle partial includes with attributes like `tags`, `indents`, `lines`? From [these lines in reader.rb](https://github.com/asciidoctor/asciidoctor/blob/32a269e71723ba10537a13b2b3dfa611b0131566/lib/asciidoctor/reader.rb#L1035-L1039), it looks like if a custom processor can handle an include statement, then it expects that processor to also handle implementing the tags for that statement, exiting that method early. The reader will not attempt to further process the included content to filter for lines, tags, or the other attributes normally supported by the include macro. This is a problem because there are [a lot of intricacies](https://asciidoctor-docs.netlify.com/asciidoc/1.5/directives/include-lines-and-tags/) to that include macro, and it seems like it would be difficult for custom processors to exactly match the behavior.

I would propose moving all the code from `reader.rb` that deals with including content from tags, lines, etc. into another helper function, and exposing that function through the `PreprocessorReader` interface. Then, custom `IncludeProcessors` can use the call that method from `process()`, passing in an arbitrary block of text (which might have been looked up from a database, a different file, provided as an argument to the processor, etc.), and know that only the appropriate portions of that text will actually get included into the main document.

---

For context: I'm developing an SSG, [Orchid](https://github.com/orchidhq/Orchid), which has support for processing Asciidoctor content through this library. But Orchid processes content using its own resource-loading abstraction layer and is not tied to working only on files. Using a custom `IncludeProcessor` allows me to hook includes into Orchid's resource-loader to find the appropriate file, but it then seems to ignore the `tags` attribute of the include statement. In particular, [this test](https://github.com/orchidhq/Orchid/blob/dev/languageExtensions/OrchidAsciidoc/src/test/kotlin/com/eden/orchid/languages/asciidoc/AsciidocTest.kt#L285) passes when Orchid's custom processor does not handle the `include` statement but fails when it does. This custom processor was implemented using the example in the [integrator's guide](https://github.com/asciidoctor/asciidoctorj/blob/master/docs/integrator-guide.adoc#includeprocessor). Unless I'm missing something, it seems like the only way for Orchid to support those tags is to re-implement them myself and hope that I get it handling the exact syntax and behavior correctly.

**Comment by mojavelinux** [comment]
> Is it possible to create a custom IncludeProcessor, but still let the Asciidoctor library handle partial includes with attributes like tags, indents, lines

What you are asking for has been proposed here: https://github.com/asciidoctor/asciidoctor/issues/571 (Antora has the same need, so I understand your point).

**Comment by cjbrooks12** [comment]
Great, I'll go ahead and close this issue and pick up the conversation on that other thread. Thanks!
