### ISSUE TITLE
question (or bug): is it expected that style macros  are expanded on .load() ? 

### ISSUE THREAD

**Issue by maxandersen** [asciidoctor/asciidoctorj#910]
I'm trying to use asciidoctorj to process asciidoc files without transforming them.

meaning if a title says:

```
== This is a title with a `bash` 
```

I would expect `node.getTitle()` to return "This is a title with a `bash`" but instead I get "This is a title with a <code>bash</code>" 

Is there a way to not see these things expanded and get a more "Raw" AST ?

**Comment by mojavelinux** [comment]
Yes, `getTitle()` always returns the converted content.

To get the raw title, you'd need to access the low-level instance variable named `title`. However, we still haven't mapped that in core. See https://github.com/asciidoctor/asciidoctor/issues/1146

**Comment by maxandersen** [comment]
thanks for the quick reply, but *dangit* :) was hoping to use asciidoctorj to traverse a doc and split it up so it fits red hats doc process but without having source material chopped to pieces.

*any* chance of these raw elements could be made accessible ? (I see the #1146 is ~5 years old :)

**Comment by LightGuard** [comment]
I have worked around this by dropping to the internal API:

```
((SectionImpl) section).getProperty("@text")
```

**Comment by mojavelinux** [comment]
Thanks Jason!

**Comment by abelsromero** [comment]
Since low level (even if not nice) access is available for such corner cases I don't feel we need to add changes to current API. Closing then.
