### ISSUE TITLE
Error in SPI example path for converters in integrator-guide

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#914]
The examples says `META-INF/services/META-INF/services/org.asciidoctor.jruby.converter.spi.ConverterRegistry`
 but I assume the correct path should be `META-INF/services/org.asciidoctor.jruby.converter.spi.ConverterRegistry`.

**Comment by robertpanzer** [comment]
Thanks for the pointer. 
I’ll fix as soon as possible
