### ISSUE TITLE
How to create a list

### ISSUE THREAD

**Issue by glisicivan** [asciidoctor/asciidoctorj#916]
I am trying to create BlockMacroProcessor (using Java) that will return block that contains a list of items. However, I am not sure how to create a list. There is a createListItem method that takes List object as parameter, but there is not a method to create list itself.
Is it possible to create list from scratch?

Note: I can see that in Ruby it is possible to instantiate List object and then add list items to it.
Note #2: I apologize for creating an issue, but wasn't sure where to ask for help.

**Comment by robertpanzer** [comment]
Good catch. This seems to be missing indeed.

**Comment by robertpanzer** [comment]
I'll try to create a fix for this as soon as possible.

And please don't apologise for creating an issue, that's the best way to get my attention ;)

**Comment by robertpanzer** [comment]
Fixed with 2.3.0
