### ISSUE TITLE
Support later version of rouge

### ISSUE THREAD

**Issue by roganjoshua** [asciidoctor/asciidoctorj#925]
org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.NameError: (NameError) asciidoctor: FAILED: /index.adoc: Failed to load AsciiDoc document - uninitialized constant Rouge::Lexers

As I understand it, rouge needs to be updated to 3.19.0+ in asciidoctorj

**Comment by mojavelinux** [comment]
Here are the related issues to understand why this is necessary:

* https://github.com/asciidoctor/asciidoctor/issues/3623
* https://github.com/asciidoctor/asciidoctor/issues/3625

Both libraries were at fault, but fortunately rouge got a release out first that fixes the issue.

**Comment by robertpanzer** [comment]
I just released 2.3.1 which should contain the fix for this. /cc: @ahus1

**Comment by ahus1** [comment]
Thanks @robertpanzer. The fix works and no longer throws the error.
