### ISSUE TITLE
Rename master branch

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctorj#930]
In the light of recent events we also should consider renaming our "master" branch.
Possible options include 

- main seems to be popular right now
- trunk also makes sense to me.

Are there any other options?
What are your thoughts?

**Comment by abelsromero** [comment]
Other repos have already moved to `main`, I think this is as good as any moment to change it :+1:

**Comment by mojavelinux** [comment]
I'm in favor of `main`. It's the name both GitHub and GitLab are moving forward with as a default. And having used it now for several months, I can report that it feels very natural. It's also probably best if the Asciidoctor repositories remain consistent.

**Comment by robertpanzer** [comment]
Awesome! I'll try to make this change tomorrow 👍

**Comment by robertpanzer** [comment]
The default branch is "main" now.
