### ISSUE TITLE
StructuralNode#setLevel is missing

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctorj#931]
Unless I'm missing something, I think that `setLevel` is missing from `StructuralNode` right?

`level` is defined as an attribute accessor so it should be possible to set the value:
https://github.com/asciidoctor/asciidoctor/blob/cb7c20593344bda9bc968a619b02065d3401ad29/lib/asciidoctor/abstract_block.rb#L18-L19

In Ruby, I can do:

```rb
section.level = 1
```

If the method is indeed missing, is there a workaround? (i.e. casting the objet to access low-level methods?)

**Comment by robertpanzer** [comment]
Honestly I never considered this property to be set by anybody else but the parser (or to be it simply computed from the level in the AST).
It looks like I was wrong and I'll add a setter soon.

Until then you can set the level like this:
```java
        RubyObjectWrapper rubyBlock = (RubyObjectWrapper) block;
        Ruby ruby = rubyBlock.getRubyObject().getRuntime();
        rubyBlock.setRubyProperty("@level", ruby.newFixnum(42));
```

**Comment by Mogztter** [comment]
For reference, I'm using this method to "flatten" a document in order to have only first level sections (i.e. not nested sections).
Basically, the following:

```
= Document

== Section 1

=== Section 1.1

== Section 2
```

gets transformed into:

```
= Document

== Section 1

== Section 1.1

== Section 2
```

(can be useful when you convert an AsciiDoc document into slides)

**Comment by robertpanzer** [comment]
I see, `@level` is set when a block is created.
