### ISSUE TITLE
Version-2.3.1 can not find in Maven Central Repository

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctorj#936]
[org.asciidoctor : asciidoctorj - Official search of Maven Central Repository](https://search.maven.org/artifact/org.asciidoctor/asciidoctorj).

The last version is 2.3.0 in Maven Central Repository.

![image](https://user-images.githubusercontent.com/2121467/87220702-c70a2e80-c398-11ea-9bca-4f5d3ae1cfaf.png)

**Comment by abelsromero** [comment]
Yes, 2.3.1 is not available. There was some issue and Robert reached Maven Central support, but there was no clear answer of what happened.
At the end it will be easier to do another release and forget about 2.3.1 than keep digging.

@robertpanzer may correct me if I say anything worng.

**Comment by robertpanzer** [comment]
Yes, exactly. I'll push out a new version this week which will hopefully find its way to Maven central. Until then you can resolve 2.3.1 from jcenter.

**Comment by abelsromero** [comment]
2.4.0 is already in maven central, I guess this issue can be closed.

**Comment by robertpanzer** [comment]
Awesome, glad it worked this time
