### ISSUE TITLE
Deprecation of Options destinationDir

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#941]
I am confused about the use of `destinationDir` vs `toDir`, I suspect they are the same and maybe the first one could be marked as deprecated to avoid confusion to users.
Seeing this code
https://github.com/asciidoctor/asciidoctor/blob/1d61da9ee0aba63711c415fa629a80f275036aa4/lib/asciidoctor/cli/invoker.rb#L59 and the user manual https://asciidoctor.org/docs/user-manual/#ruby-api-options, seems pretty obvious but I wanted to contrast and maybe check if this has some history reason.

**Comment by robertpanzer** [comment]
Interesting. We definitely need to do some investigation on this.
For the command line option we follow the behavior of the Asciidoctor Ruby Invoker and set to_dir: https://github.com/asciidoctor/asciidoctorj/blob/7456234b598d037cf3689ad75c3567825d7f7b05/asciidoctorj-core/src/main/java/org/asciidoctor/jruby/cli/AsciidoctorCliOptions.java#L321-L322

But I can imagine that calling Options.setDestinationDir() could be completely useless, just looking at the code it seems like Asciidoctor would never look at this option when set from the API.

**Comment by abelsromero** [comment]
It seems to me *destinationDir* is just a front-end for *to_dir*. I suspect for Python compatiblity https://github.com/asciidoc/asciidoc-py3/search?q=destination%3A&unscoped_q=destination%3A. While there's a mention of *destinationDir* and *destination_dir* in the code, there's no *to_dir*.
