### ISSUE TITLE
Re-structure extensions documentation in integrators-guide

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#950]
In a recent issue I found out the use of `ExtensionGroups`, and saw it's not documented.
I wanted to add it, but then though it could be a chance to improve the overall section to accomodate the new docs.

Right now, to me how it's explained is a bit confusing.
At the beginning of the section we say:
```
To create an extension two things are required:

1. Create a class extending one of the extension classes from above
2. Register your class using the JavaExtensionRegistry class
```

But, then we jump into the AST stating knowing about it is also a pre-requisit.
After that, we explain at the same section depth:

* Each extension type and for each how to register directly using `asciidoctor.javaExtensionRegistry()`.
* How register with SPI automatically

This is the tree as seen in Intellj plugin (excuse the bug showing the cols and note as sections):
![image](https://user-images.githubusercontent.com/5781153/92657550-52e6fb00-f2f5-11ea-8ea4-ea3b06ec007a.png)

I think it would be easier if we beging saying there are "three steps":
* Briefly understand how Asciidoctor converts documents -> we can talk about AST + how extension plug into it without much detail since extensions are explained later on it's own section. We should not make this cumbersome or overly complex not to discourage people, I can imagine that hearing AST right at the start can be dauning for some.
* How to create an AsciidoctorJ extension -> here we aggregate the extension types, and remove the duplicated examplations about `asciidoctor.javaExtensionRegistry()` from each.
* How to register your extension -> here, in 3 subsections (level 4 in depth) we explain:
  * Manual registering (so we remove duplciation in previous section)
  * SPI
  * ExtensionGroups

I tend to have this rule in which if an introduction mentions a list of key elements, then each point/number should map to a sub-section. wdyt?

Related to this I have some questions:
* Should we recomend `ExtensionGroups` above the other methods? It seems to me this is simpler and more flexible since it allows un-registering, and also does not leak the java implementation. Are there any pros-cons of using manual vs the groups? _For SPI there's a clear advantage of automatic detection_
* Is there a set of JVM languages we can mention with confidence other than Java and Groovy? This is OSS so I don't think we need to fully commit or talk about "support", but i'd be nice if we can mantion some that we feel confident about.

**Comment by robertpanzer** [comment]
> I tend to have this rule in which if an introduction mentions a list of key elements, then each point/number should map to a sub-section. wdyt?

That's a very good idea.

> Should we recomend ExtensionGroups above the other methods? It seems to me this is simpler and more flexible since it allows un-registering, and also does not leak the java implementation. Are there any pros-cons of using manual vs the groups? For SPI there's a clear advantage of automatic detection

About this I am unsure and it probably depends on what you are doing.
For a simple one-off task I would always prefer the version without ExtensionGroup because it is less code.
But I agree, in server environments that might be different.
So it would be great to document both approaches.

> Is there a set of JVM languages we can mention with confidence other than Java and Groovy? This is OSS so I don't think we need to fully commit or talk about "support", but i'd be nice if we can mantion some that we feel confident about.

You mean about using AsciidoctorJ in Scala or Kotlin?
Definitely sth to test and document.

Thanks for creating this issue! 🚀

**Comment by abelsromero** [comment]
> Definitely sth to test and document.

:sweat_smile: I was hoping to avoid delving too much.
I'll stick with Java and groovy which are well known and in some future see if I can find time for the others.

**Comment by abelsromero** [comment]
I just noticed docs seem duplicated under _/docs_ an in _asciidoctorj-documentation_ project. How should I update?
