### ISSUE TITLE
Don't check for a specific version of highlight.js in the tests

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctorj#953]
The version of highlight.js in core changes gets updated from time to time. The tests should be able to handle this change without having to update the test each time. Leave the highlight.js version as a wildcard in the test.

**Comment by mojavelinux** [comment]
This test is still too fragile. I think it should be checking just that highlight.js is somewhere in the HTML. It's the the responsibility of AsciidoctorJ to put it there, so it shouldn't care where it is or what the exact text is. Every time we change something in core, this test seems to fail. But there's no reason it should.

**Comment by robertpanzer** [comment]
The intention of this test was to prove that it's possible to write a syntax highlighter in Java that produces an identical result to the counterpart in Ruby. 

Just checking if the word highlightjs is part of the result doesn't really meet that expectation imo. 

Maybe we could decouple the test entirely from the Ruby version and just check against a fixed, expected result instead.

**Comment by mojavelinux** [comment]
Ah, I understand. Sounds like a good plan. :+1:
