### ISSUE TITLE
Spring boot.jar running failed, but Application running OK

### ISSUE THREAD

**Issue by Robot-L** [asciidoctor/asciidoctorj#957]
If I start by running Application, everything is normal, but I run gradle command `bootjar`, and the program reported an error after starting with `java -jar`

Exception information:

```java
2020-09-28 12:17:24.413 ERROR 21401 --- [io-10000-exec-1] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/swagger] threw exception [Handler dispatch failed; nested exception is java.util.ServiceConfigurationError: org.asciidoctor.Asciidoctor: Provider org.asciidoctor.jruby.internal.JRubyAsciidoctor could not be instantiated] with root cause

org.jruby.exceptions.LoadError: (LoadError) no such file to load -- asciidoctor
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:974) ~[jruby-core-9.2.13.0.jar!/:na]
        at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54) ~[na:na]
        at RUBY.<main>(<script>:12) ~[na:na]

```
build.gradle:

```groovy
dependencies {
    compile 'org.springframework.boot:spring-boot-starter-web'
    compile 'org.springframework.boot:spring-boot-starter-actuator'
    compile 'io.swagger:swagger-annotations:1.5.6'
    implementation "io.github.swagger2markup:swagger2markup:1.3.3"
    compile "org.asciidoctor:asciidoctorj:2.4.1"
    // don't work
    // compile "org.jruby:jruby-complete:9.2.13.0"
    compile "org.springframework.boot:spring-boot-configuration-processor"

    testCompile 'org.springframework.boot:spring-boot-starter-test'
    testCompile 'junit:junit'
    testCompile 'org.springframework.restdocs:spring-restdocs-mockmvc'
    testCompile 'com.fasterxml.jackson.module:jackson-module-jsonSchema:2.6.5'
}
```

I searched the previous issues and try using the latest jruby-complete package, but it didn’t work.

The exception information is the same as above:
```java
org.jruby.exceptions.LoadError: (LoadError) no such file to load -- asciidoctor
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:974) ~[jruby-complete-9.2.13.0.jar!/:na]
        at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54) ~[na:na]
        at RUBY.<main>(<script>:12) ~[na:na]
```

Thx!

**Comment by abelsromero** [comment]
SpringBoot uses a custom packaging jar format and classloader, and it doesn't work well for jRuby.
You need to tell it to "unpack" AsciidoctorJ, and maybe also JRuby, have a look at this
https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/#packaging-executable-configuring-unpacking

If you can, please, let us know what dependencies dees need, so we can have ot recorded here.

**Comment by Robot-L** [comment]
I tried it many times, but it didn’t work. Finally, I unzipped the jar and started it with `java -cp` 😔

**Comment by abelsromero** [comment]
SpringBoot is something I personally want to suppor. To build a reproducer I need:
* Version of SpringBoot
* Component description: is a rest endpoint that converts a doc I assume?

**Comment by abelsromero** [comment]
@Robot-L I build an example with the latest SpringBoot version and your dependencies and so far is working fine.
https://github.com/abelsromero/asciidoctorj-springboot-server

The trick setting the appropiate packaging in gradle.

```groovy
bootJar {
    requiresUnpack('**/asciidoctorj-*.jar')
}
```

**Comment by abelsromero** [comment]
@robertpanzer I think this issue could be closed as question. At least I could not find any problem on my side.

**Comment by robertpanzer** [comment]
Thanks @abelsromero for finding this out! 🚀 

I think it would make sense to document this or even create some small example project demonstrating Spring Boot plus AsciidoctorJ.

**Comment by abelsromero** [comment]
> I think it would make sense to document this or even create some small example project demonstrating Spring Boot plus AsciidoctorJ.

I am more inclined to have some integration tests for cases like this. I think it would be easier to mantain and we can point to it if people asks.
The thing is how to integrate it in the build? Have a subproject with intependent projects and run/validate with bash?

**Comment by robertpanzer** [comment]
Even better!

We already have an integration test for wildfly. Maybe sth similar would work for Spring Boot?
We would just need to make sure that the test really represents the real world behavior.

**Comment by rob-stoecklein** [comment]
Information in this link allowed us to solve this problem:

https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.build.extract-specific-libraries-when-an-executable-jar-runs

Then in our Maven POM file, we extracted `asciidoctorJ` like this:

```
  <configuration>
    . . .
    <requiresUnpack>
        <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj</artifactId>
        </dependency>
    </requiresUnpack>
  </configuration>
```
