### ISSUE TITLE
Consider Making it Clearer That Docs are Generated

### ISSUE THREAD

**Issue by lread** [asciidoctor/asciidoctorj#961]
A small idea which might save newcomers like me some time in the future:

A comment header could be added when generating adocs.

For example:

```asciidoctor
// THIS FILE IS GENERATED - DO NOT EDIT
// Edit here: asciidoctorj-documentation/src/main/asciidoc/extension-migration-guide.adoc
// And then run: ./gradlew asciidoctorj-documentation:build
```

Happy to make the change if folks agree it would be helpful.

**Comment by robertpanzer** [comment]
Great idea imo👍

**Comment by lread** [comment]
Cool, will create PR.

**Comment by lread** [comment]
I have something ready but, to avoid confusing and overwhelming, will hold off submitting until #964 and #960 are merged.
