### ISSUE TITLE
`OptionsBuilder.toFile(OutputStream)` not available

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#965]
This is more a question.

`OptionsBuilder` allows to pass a String or a File to the `toFile` method. However, in JRubyAsciidoctor a conversion is done in case it is an `OutputStream`.
https://github.com/asciidoctor/asciidoctorj/blob/818f617ce9cde4cb131bf1e9659e281dd5d44d25/asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JRubyAsciidoctor.java#L301

¿Is OutputStream supported? and is so ¿Shoudn't it be also allowed in OptionsBuilder?

**Comment by robertpanzer** [comment]
There is a method `setToStream()` for this:
https://github.com/asciidoctor/asciidoctorj/blob/818f617ce9cde4cb131bf1e9659e281dd5d44d25/asciidoctorj-api/src/main/java/org/asciidoctor/OptionsBuilder.java#L187-L190
I think that even though it ends up in the same option name, it better represents what it does.

**Comment by abelsromero** [comment]
> I think that even though it ends up in the same option name, it better represents what it does.

Your are right, I could not find it because I was matching the underlying asciidoctor cli options, but it totally makes sense.
