### ISSUE TITLE
Allow Reader input for Asciidoctor.load

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#969]
Currently to convert we have:
* `convert` which supports passing a String or Reader.
* `convertFile` & `convertFiles` which support passing a File.

But if we only want the AST, we have:
* `load` which supports a String only.
* `loadFile` which supports a File.

Would it make sense to allow `load` to also acces a Reader.

PS: It just happens that it would be handy to me :P

**Comment by robertpanzer** [comment]
Yes, that would make sense imo. 
Good catch!

**Comment by abelsromero** [comment]
I see the implementation converts to String https://github.com/asciidoctor/asciidoctorj/blob/c1edcb94c6d41d4e44c09fa41228c531861b6636/asciidoctorj-core/src/main/java/org/asciidoctor/jruby/internal/JRubyAsciidoctor.java#L351.
I'll do some research to see of there's a way to stream data, honestly I'd like to avoid creating big memory buffers.

**Comment by abelsromero** [comment]
After some digging I don't see any good worth the effort. My goal was to avoid loading full file as String, but under-the-hood Asciidoctor does that anyway. https://github.com/asciidoctor/asciidoctor/blob/1c2d678a6dc58ff057508f3826fc74d44c07511d/lib/asciidoctor/load.rb#L55-L68

AsciidoctorJ internally reads to String and even when outputing to a Writer it internally converts to String and then creates a writter from it.

I also run some tests (converting a few hundred docs of 1.4MB each in sequence) and there's not much improvement in memory usage. I even tested passing a RubyFile for methods that use File as input (currently we pass the filePath to Asciidoctor) but there's no difference that I can see.

With RubyFile

![image](https://user-images.githubusercontent.com/5781153/115122568-ce5e0880-9fb8-11eb-83fd-68ca8b2115d1.png)


With path as RubyString
![image](https://user-images.githubusercontent.com/5781153/115122574-db7af780-9fb8-11eb-9466-3e26a37cff0c.png)



As a side note, passing a string is clearle less efficient, I check the RubyMethod to build a String and it copies the original bytes to a new array, so that's to be expected.

![image](https://user-images.githubusercontent.com/5781153/115122717-b0dd6e80-9fb9-11eb-9b34-911176c98b02.png)

**Comment by abelsromero** [comment]
After some extra though, I am convinced to keep things as they are now.

**Comment by robertpanzer** [comment]
Thanks for the great analysis!
