### ISSUE TITLE
Expose AST's document authors as class

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj#970]
The core API exposes authors with a struct which is quite convenient:
https://github.com/asciidoctor/asciidoctor/blob/a9d828ae05abf8eaf9eea554c8390e4019a45567/lib/asciidoctor/document.rb#L730

The current alternative is to traverse document's attributes looking for these attributes (where # is index starting from 1) if there's more than one author:
* author_# (for full name)
* email_#
* firstname_#
* middlename_#
* lastname_#
* authorinitials_#

or just these if there's one author

* author (for full name)
* email
* firstname
* middlename
* lastname
* authorinitials

**Comment by abelsromero** [comment]
I saw there's already an [Author](https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-api/src/main/java/org/asciidoctor/ast/Author.java) class, but it's only used when using `Asciidoctor::readDocumentHeader` making it of little use in extensions, and furthermore it does not support multiple authors.

I was think we can add the `DocumentHeader` instance to the `Document` interface so users can acces authors and the other information already contained. We can reuse the current implementation and hold a private instance of DocumentHeader and add getters in Document that delegate to Header. This will be aligned with thr Ruby structure.
Also, going further I would deprecate the Heather methods, the fact that that information can be obtained from the header is incidental and to me it seems to leak internal details.


Side note, started working on it but found out I cannot run the test from IDE (it says that there're no tests in the class) and running individually from console (`./gradlew clean :asciidoctorj:test --tests "org.asciidoctor.WhenGlobExpressionIsUsedForScanning"`) fails.
```
org.asciidoctor.WhenGlobExpressionIsUsedForScanning > all_files_with_given_extension_of_current_directory_should_be_returned FAILED
    java.lang.NullPointerException at WhenGlobExpressionIsUsedForScanning.java:29

org.asciidoctor.WhenGlobExpressionIsUsedForScanning > all_files_with_given_extension_should_be_returned_recursively FAILED
    java.lang.NullPointerException at WhenGlobExpressionIsUsedForScanning.java:43

org.asciidoctor.WhenGlobExpressionIsUsedForScanning > no_should_be_returned_if_glob_expression_does_not_match FAILED
    java.lang.NullPointerException at WhenGlobExpressionIsUsedForScanning.java:57
```

What should be the process for an optimal dev cycle?

**Comment by robertpanzer** [comment]
> Side note, started working on it but found out I cannot run the test from IDE (it says that there're no tests in the class) and running individually from console (./gradlew clean :asciidoctorj:test --tests "org.asciidoctor.WhenGlobExpressionIsUsedForScanning") fails.

I just updated IntelliJ to the latest version and the tests are also not working anymore for me at all. :(
Sorry about that. 
For me it's rather that classes from Arquillian are not available, even though the tests run on the command line.
Working with "non-trivial" Gradle builds and IntelliJ really seems to be a constant source of frustration. (I remember when IntelliJ did not pick up the ruby gems that were packaged by the Gradle build and added to the source paths)
I am not quite sure what to do right now, it definitely worked fine for me until recently.

It would definitely be great if we could access the information that the DocumentHeader provides also directly or indirectly from the Document itself.
There is some overlap between Document and DocumentHeader, so the question would be if we also add a DocumentHeader property to Document and deprecate the old Document.docTitle, or if we add these properties directly to the Document.
I don't have a strong opinion for either possibility.

**Comment by abelsromero** [comment]
Also updated to 2021.1 Ultimate today and just found out that if I run all test in the folder, at least thi one gets executed. Is not convenient, but at least I can debug wich is what I needed to see the jruby objects under-the-hood. That's enough for now.

Rolled back latest gradle's commits and still the same, so it seems an IntelliJ issue to me, if I find some time I can dig Jetbreains issues to see if it's a known thing, but it's odd that removing Arquillian components also misses to find test method. 

> There is some overlap between Document and DocumentHeader, so the question would be if we also add a DocumentHeader property to Document and deprecate the old Document.docTitle, or if we add these properties directly to the Document.
> I don't have a strong opinion for either possibility.

Repeating myself I know I see this arguments for exposing the properties directly from Document:
* Interoperabilty between Asciidoctor implementations: my -opinionated- philosophy is to stay close to original Asciidoctor Ruby to simplify switching between implementations. Plus header implies being at the top and that to me is an implementation detail not related to AST concepts. If we were to conceptualize from scratch in a different class I'd rather call it metadata/descriptor...
It's true however that documentation acknowledges the concept of Header https://docs.asciidoctor.org/asciidoc/latest/document/header/ and it's properties https://docs.asciidoctor.org/asciidoc/latest/document/header-ref/, they are exposed from document https://github.com/asciidoctor/asciidoctor/blob/a9d828ae05abf8eaf9eea554c8390e4019a45567/lib/asciidoctor/document.rb#L749-L772.
* Ease of use: it is also more conveninent for developers to get all methods in the `Document`interface, otherwise someone looking for author would have to get they need to do `getHeader().getAuthor()`.
* Consistency with current approaches: we already have `getDoctitle()` and `doctitle()` in `Document` interface

So to me I would have:
* List<Author> getAuthors() in Document: it will abstract the different `author, author_<n>` properties in a consistent collection.
* Deprecate `readDocumentHeader()` methods and DocumentHeader class: implementation calls `.callMethod("load_file", rubyRuntime.newString(file.getAbsolutePath()), rubyHash)` anyway, so it's not like it provides any advantage in performance.

**Comment by robertpanzer** [comment]
Sounds great!
