### ISSUE TITLE
Issue with content pushed by IncludeProcessor with version 2.4.2

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctorj#978]
When I have have tried to migrate to version `2.4.2` of asciidoctorj, I am experiencing following issue.$
The issue does not occur with version `2.4.1`.

I am using a custom `IncludeProcessor` called [dynamic-include](https://jmini.github.io/asciidoctorj-dynamic-include/), but I have simplified the problem:

Given this `LoremIncludeProcessor` that just push some content to replace `include::lorem[]` :

```java
import java.util.Map;

import org.asciidoctor.ast.Document;
import org.asciidoctor.extension.IncludeProcessor;
import org.asciidoctor.extension.PreprocessorReader;

public class LoremIncludeProcessor extends IncludeProcessor {
    private static final String LOREM = "lorem";

    public LoremIncludeProcessor() {
        super();
    }

    public LoremIncludeProcessor(Map<String, Object> config) {
        super(config);
    }

    @Override
    public boolean handles(String target) {
        return LOREM.equals(target);
    }

    @Override
    public void process(Document document, PreprocessorReader reader, String target, Map<String, Object> attributes) {

        String data2 = "\n"
                + "== Elit ullamcorper\n"
                + "\n"
                + "Dignissim cras tincidunt lobortis feugiat vivamus.\n"
                + "Dui accumsan sit amet nulla facilisi.\n"
                + "\n"
                + "\n";
        reader.push_include(data2, "file2.txt", "some/path/file2.txt", 0, attributes);

        String data1 = "\n"
                + "== Lorem ipsum dolor sit amet\n"
                + "\n"
                + "consectetur adipiscing elit\n"
                + "\n"
                + "* sed do eiusmod \n"
                + "* tempor incididunt \n"
                + "* labore et dolore\n"
                + "\n"
                + "\n";
        reader.push_include(data1, "file1.txt", "some/path/file1.txt", 0, attributes);

    }
}
```

I expect this asciidoctor source:
```adoc
This is a test.
include::lorem[]
```

To be transformed to:
```html
<div id="preamble">
<div class="sectionbody">
<div class="paragraph">
<p>This is a test.</p>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_lorem_ipsum_dolor_sit_amet">Lorem ipsum dolor sit amet</h2>
<div class="sectionbody">
<div class="paragraph">
<p>consectetur adipiscing elit</p>
</div>
<div class="ulist">
<ul>
<li>
<p>sed do eiusmod</p>
</li>
<li>
<p>tempor incididunt</p>
</li>
<li>
<p>labore et dolore</p>
</li>
</ul>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_elit_ullamcorper">Elit ullamcorper</h2>
<div class="sectionbody">
<div class="paragraph">
<p>Dignissim cras tincidunt lobortis feugiat vivamus.
Dui accumsan sit amet nulla facilisi.</p>
</div>
</div>
</div>
```

But with version `2.4.2` I get this:

```html
<div id="preamble">
<div class="sectionbody">
<div class="paragraph">
<p>This is a test.
== Lorem ipsum dolor sit amet</p>
</div>
<div class="paragraph">
<p>consectetur adipiscing elit</p>
</div>
<div class="ulist">
<ul>
<li>
<p>sed do eiusmod</p>
</li>
<li>
<p>tempor incididunt</p>
</li>
<li>
<p>labore et dolore
== Elit ullamcorper</p>
</li>
</ul>
</div>
<div class="paragraph">
<p>Dignissim cras tincidunt lobortis feugiat vivamus.
Dui accumsan sit amet nulla facilisi.</p>
</div>
</div>
</div>
```

The diff:
<img width="1270" alt="Diff between the HTML obtained with versions 2.4.1 and 2.4.2" src="https://user-images.githubusercontent.com/1222165/100878622-b888f480-34aa-11eb-81c9-99ce8056220d.png">

As you can see the titles are not processed.

The source code to run the test:
```java
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.HashMap;

import org.asciidoctor.Asciidoctor;
import org.asciidoctor.Asciidoctor.Factory;
import org.asciidoctor.AttributesBuilder;
import org.asciidoctor.OptionsBuilder;
import org.asciidoctor.SafeMode;
import org.asciidoctor.extension.JavaExtensionRegistry;
import org.junit.jupiter.api.Test;

public class SomeTest {
    @Test
    public void test() {
        Asciidoctor asciidoctor = Factory.create();

        JavaExtensionRegistry javaExtensionRegistry = asciidoctor.javaExtensionRegistry();
        javaExtensionRegistry.includeProcessor(new LoremIncludeProcessor(new HashMap<>()));

        AttributesBuilder attributesBuilder = AttributesBuilder.attributes()
                .setAnchors(false)
                .sectionNumbers(false)
                .attribute("nofooter", true);

        OptionsBuilder optionsBuilder = OptionsBuilder.options()
                .attributes(attributesBuilder)
                .docType("book")
                .safe(SafeMode.UNSAFE);

        String adoc = "This is a test.\n"
                + "include::lorem[]\n"
                + "\n";
        String html = asciidoctor.convert(adoc, optionsBuilder);

        String expected = "<div id=\"preamble\">\n"
                + "<div class=\"sectionbody\">\n"
                + "<div class=\"paragraph\">\n"
                + "<p>This is a test.</p>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "<div class=\"sect1\">\n"
                + "<h2 id=\"_lorem_ipsum_dolor_sit_amet\">Lorem ipsum dolor sit amet</h2>\n"
                + "<div class=\"sectionbody\">\n"
                + "<div class=\"paragraph\">\n"
                + "<p>consectetur adipiscing elit</p>\n"
                + "</div>\n"
                + "<div class=\"ulist\">\n"
                + "<ul>\n"
                + "<li>\n"
                + "<p>sed do eiusmod</p>\n"
                + "</li>\n"
                + "<li>\n"
                + "<p>tempor incididunt</p>\n"
                + "</li>\n"
                + "<li>\n"
                + "<p>labore et dolore</p>\n"
                + "</li>\n"
                + "</ul>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>\n"
                + "<div class=\"sect1\">\n"
                + "<h2 id=\"_elit_ullamcorper\">Elit ullamcorper</h2>\n"
                + "<div class=\"sectionbody\">\n"
                + "<div class=\"paragraph\">\n"
                + "<p>Dignissim cras tincidunt lobortis feugiat vivamus.\n"
                + "Dui accumsan sit amet nulla facilisi.</p>\n"
                + "</div>\n"
                + "</div>\n"
                + "</div>";
        assertEquals(expected, html);

    }
}
```

**Comment by mojavelinux** [comment]
This could be due to a change in Asciidoctor 2.0.12, but I'm having difficulty seeing what that change is.

As a side note, why is the method named push_include instead of pushInclude?

**Comment by mojavelinux** [comment]
Aha. I think I know what it is. When you push an include, it removes leading and trailing blank lines. A quick fix is to use a comment line to force the two blocks apart.

I'll see if I can think of a better approach.

**Comment by mojavelinux** [comment]
Another approach to disable this behavior is to change the file extension on the name of the file you are pushing (2 and 3 arguments) to something other than an AsciiDoc file extension. .txt is an AsciiDoc file extension (according to the parser), so use something like .text.

**Comment by jmini** [comment]
Thank you a lot for this feedback, I will try the workaround with the comment you have suggested.

> change the file extension on the name of the file you are pushing (2nd and 3rd arguments) to something other than an AsciiDoc file extension

For my [dynamic include macro](https://jmini.github.io/asciidoctorj-dynamic-include/) this is not an option, because I collect all the files bases on a globbing expression (`folder/*.adoc`).

Side note: I just looked at my readme and I am surprise to see it empty. I thought I wrote some explanations.

The main idea is that instead of:

```adoc
= My book

include::content/chapter01.adoc[]

include::content/chapter02.adoc[]

include::content/chapter03.adoc[]
```

You can do:

```adoc
= My book

include::dynamic:content/*.adoc[]
```

The macro has some configuration possibilities to control stuff like the include order and is doing some additional content manipulation. The content of the file is read in Java `content/chapterXX.adoc` and before pushing it to the asciidoctor engine it does some changes (adding line breaks, transforming internal cross references, adding a link to the file, ...).

> As a side note, why is the method named `push_include()` instead of `pushInclude()`?

I have opened #980 to discuss that.

----
About https://github.com/asciidoctor/asciidoctor/issues/3470 :

I read the issue trying to understand if the approach of my macro is not valid at all… 
I think I will continue the discussion on that issue.

**Comment by mojavelinux** [comment]
> I collect all the files bases on a globbing expression (folder/*.adoc).

I'm not suggesting the input files need to change, but rather how you identify them to push_include. And that's just an option.

The idea for your macro is sound. You're just being bitten by a change that fixed a bug internally, but has proven to create an incompatibility externally.

> I think I will continue the discussion on that issue.

It would be best to open a new issue. There needs to be a way to specify that you don't want to compress the lines of the input. We could make this the default when push_include is called from an extension. Regardless of what we decide, it will require a change (unless you use the line comment workaround I mentioned, which I understand does not feel nice).

**Comment by mojavelinux** [comment]
I don't think this issue needs to stay open because, as we have discovered, this has nothing to do with AsciidcotorJ.

**Comment by jmini** [comment]
> this has nothing to do with AsciidcotorJ

Yes sorry I come to the project that I use (I never use the asciidoctor ruby directly).

---

This issue can be closed and replaced by https://github.com/asciidoctor/asciidoctor/issues/3875

**Comment by mojavelinux** [comment]
You followed the correct path. We just determined where the relevant code is located and thus have to relocate the conversation to where it can be addressed.
