### ISSUE TITLE
Rename push_include to pushInclude

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctorj#980]
From: https://github.com/asciidoctor/asciidoctorj/issues/978#issuecomment-737529649

>  why is the method named `push_include` instead of `pushInclude`?

I think this can be introduced in a non-breaking manner (by kepping the old `push_include` method with a Depreciation warning)

I can contribute a fix for this.

**Comment by robertpanzer** [comment]
Sure, let's fix it! 
It would be great if you could create a PR.

**Comment by abelsromero** [comment]
I think we could also add this one for next release?

**Comment by robertpanzer** [comment]
Yes, that would be a good occasion!
