### ISSUE TITLE
Consider documenting context and selectors

### ISSUE THREAD

**Issue by oliviercailloux** [asciidoctor/asciidoctorj#981]
The [Reading the document tree](https://asciidoctor.org/docs/asciidoctorj/#reading-the-document-tree) section indicates that it is possible to find elements of an Asciidoctor document by “selector”. But it does not document what a selector is. It only provides an example for searching “all blocks with context as image”. It also does not document what a context is. There is also no match for the words “context”, “selector” or “:image” with the relevant meaning in the whole [user manual](https://asciidoctor.org/docs/user-manual). The user manual provides an [example](https://asciidoctor.org/docs/user-manual/#tree-processor-example) involving a `:literal` context, with no apparent further explanation. I also tried to search in the [asciidoctor RubyDoc](https://www.rubydoc.info/gems/asciidoctor/), but I don’t speak Ruby, so this is quite difficult to understand.

 Therefore, I have no clue whether or how I can, for example, find all links in an Asciidoctor document using this apparently handy `findBy` method.

Please consider providing some pointers to help those poor non-Ruby speakers like me!

Sorry if I missed something obvious…

**Comment by mojavelinux** [comment]
This is a topic that needs to first be addressed in the core documentation. Then the documentation for AsciidoctorJ can reference it and elaborate. The current issue can be found here: https://github.com/asciidoctor/asciidoctor.org/issues/323 Once the new docs site rolls out, that will likely be moved to core.

**Comment by oliviercailloux** [comment]
Thanks for the pointer! I see [there](https://github.com/asciidoctor/asciidoctor-documentation-planning/issues/30) that it seems that those “selectors” do not permit to find all links in a document. Does AsciidoctorJ provide a way of finding them? Should I use rather a regexp? (This would seem rather fragile or difficult to make sure that it encompasses every situation…)

**Comment by abelsromero** [comment]
As you found, links do not appear as nodes in the AST and you cannot search them.

If you can tell us more about the problem you need to solver, we may be able to find an alternative solution.

**Comment by mojavelinux** [comment]
That's correct, the document model does not provide access to inline nodes since they aren't yet parsed at this point in the processing (nor are they ever appear in the document model). Inline nodes are only visible to the converter in a streaming fashion. It's something we are aiming to address in the AsciiDoc spec process.

**Comment by oliviercailloux** [comment]
> If you can tell us more about the problem you need to solver, we may be able to find an alternative solution.

I want to scan an asciidoctor document and find all HTTP hyperlinks contained in there in order to check for broken links. Similar to [this](https://github.com/gaurav-nelson/asciidoc-link-check) in spirit (except I’d run the code on files stored on my hard disk). I would like, if possible, to find only those that are really considered as links by a converter; in other words, those that will appear as links if the adoc gets converted to PDF or HTML; in order to only care about those that are intended to be links by the author. So a link in a line of code that is `//` commented out, for example, should not be matched.

> That's correct, the document model does not provide access to inline nodes since they aren't yet parsed at this point in the processing (nor are they ever appear in the document model). Inline nodes are only visible to the converter in a streaming fashion.

Would you perhaps recommend some (reasonably easy) approach for finding all links in an adoc? I’d like to avoid having to re-implement a full asciidoctor parser in Java, obviously; but I am not sure how to proceed, then. A naïve regexp capturing patterns such as `https://example.com[some link]` would be easy to design, but this will also catch links that are commented out, and I suppose the syntax allows for numerous ways of creating links, which such a regexp would miss, I suppose.

**Comment by mojavelinux** [comment]
If you're just doing link checking for validation, convert to HTML and use
an available library to check for broken links. It's not a wheel you want
to reinvent because it's a lot of effort to do it right with proper caching
and throttling.

>

**Comment by oliviercailloux** [comment]
> convert to HTML and use an available library to check for broken links

Good idea. Thanks.

> It's something we are aiming to address in the AsciiDoc spec process.

I wanted to mention, in passing, that I was very happy to see that this process has officially started this year. Congratulations! I am convinced that this is the start of a really robust, professional and easy way to typeset documents, that is much awaited. (As a researcher I use LaTeX, an undoubtedly very useful tool, but which, as a coder, feels quite an outdated language by nowadays standards, I must say.)

**Comment by mojavelinux** [comment]
I should also add that if you enable the CATALOG_ASSETS option, when you convert, you can find all the links the processor found in the document catalog (which is attached to the document).
