### ISSUE TITLE
[question] Abysmal documentation of extension API

### ISSUE THREAD

**Issue by jasal82** [asciidoctor/asciidoctorj#996]
I cannot figure out how to create a simple extension processor that transforms references because the documentation is practically non-existant. There is no description of the AST or document structure, virtually no documentation what the functions in a Treeprocessor do, no useful examples, nothing. It's not even possible to inspect the objects in the debugger at runtime because everything is stored in variables with generic, auto-generated names. Could you please point me to proper documentation or explain how to accomplish what I'm trying to do? Thanks.

**Comment by jasal82** [comment]
I managed to implement something similar with the InlineMacroProcessor, but now my users must learn a new syntax so it would still be nice to know how to transform existing references.

**Comment by robertpanzer** [comment]
The current documentation can be found here: https://docs.asciidoctor.org/asciidoctorj/latest/extensions/extensions-introduction/
There are also a couple of test cases in the sources that you might want to check.

**Comment by jasal82** [comment]
Thanks for the link, I already read that documentation. I'm still having a hard time figuring out what to do. For example, when creating nodes you can apply options via a HashMap but where does it say which options are allowed? A 'pass some key-value pairs' interface is not self-explanatory. The test cases cover some use-cases but for the majority of feature space there is simply not enough information. For example I want to add a CSS class for the PhraseNode I'm inserting, but where can it be set? Same goes for the Treeprocessor. The example shows how to modify a block but I need to get a hold of the inline cross references.

**Comment by robertpanzer** [comment]
> For example I want to add a CSS class for the PhraseNode I'm inserting, but where can it be set?

You are probably looking for `role`. If you add a role via `ContentNode.addRole()` it will end up as a CSS class in case the content is converted to HTML.

For references you might want to check https://github.com/asciidoctor/asciidoctorj/issues/958 and https://github.com/asciidoctor/asciidoctorj/pull/968

Please note that this is a community project depending on folks that dedicate their often rare, free time to work on this project.
There is no company behind this project that would drive the implementation or documentation.
If you feel the documentation needs to be enhanced, and yes, documentation can always be enhanced, then I'd happily accept PRs from your end.
